TryGhost/Admin

app/styles/layouts/main.css
no issue
- remove the outline that is shown on the search input once the dropdown box has closed
- remove unused styles for the old selectize-based search input
Before:
After:
=> Remove outline from search input

bower.json
no issue 
Update all of our bower dependencies to the latest compatible versions.
- codemirror@5.15.2
- google-caja@6005.0.0
- jquery-file-upload@9.12.3
- moment@2.13.0
- pretender@1.1.0
`validator-js` was skipped as it will move to an `npm` dependency.
=> Bower dependency updates

app/adapters/base.js, app/services/ajax.js, config/environment.js, package.json, tests/integration/services/ajax-test.js, tests/integration/services/store-test.js
no issue
- modifies the version info included in `env.APP.version` to only include the `major.minor` version numbers
- update base adapter to include `X-Ghost-Version` header
- update `ajax` service to include `X-Ghost-Version` header
=> Add version header to API requests

config/environment.js, tests/integration/services/store-test.js
refs #38
- use same version regex as `safeVersion` does on the server
- remove errant `console.log` from store service test
=> Minor version header fixes

app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/components/gh-profile-image.js, app/services/ajax.js, app/services/notifications.js, package.json, tests/integration/services/ajax-test.js
no issue
- update ember-ajax
- update error handling to match recommended approach
- update error normalization for handling a returned array of strings
~~This is currently failing because the current version of `ember-ajax` strips the trailing-slashes from provided URLs. I suggest holding off on the upgrade until https://github.com/ember-cli/ember-ajax/pull/96 is merged so that we don't lose performance through a 301 redirect on every API request.~~
=> deps: ember-ajax@2.4.1

app/components/gh-datetime-input.js, app/controllers/post-settings-menu.js, app/services/time-zone.js, app/utils/date-formatting.js, tests/integration/services/time-zone-test.js
refs https://github.com/TryGhost/Ghost/pull/6941#issuecomment-224553575
- `blogTimezone` and `timezone` better reflect their values (a string representing a timezone in the format `Europe/Dublin`) than `offset` which suggests a fixed value
This hopefully makes things a little easier to follow for now. Once the synchronous `settings` service is ready I imagine the `timeZone` service and it's `timeZone.blogTimezone` will disappear and it'll be replaced with `settings.activeTimezone`.
=> Rename "offset" to "blogTimezone"

app/utils/ghost-paths.js, bower.json, tests/acceptance/settings/tags-test.js, tests/acceptance/team-test.js
no issue
- bugfix & cleanup release https://github.com/emberjs/ember.js/releases/tag/v2.6.0
- fix tests that were relying on not having the `rootURL` prefixed in `href`s
=> deps: ember@2.6.0

app/templates/settings/labs.hbs
My first PR to Ghost-Admin 🎉 
Just updated the label next to the Subscribers checkbox in labs:
no issue
- changes wording to not indicate that we already send emails
- adds link to documentation
=> Labs Subscribers option clearer & with docs link

app/mirage/fixtures/settings.js, app/mirage/fixtures/timezones.js, app/models/setting.js, tests/acceptance/editor-test.js, tests/acceptance/settings/general-test.js
no issue
- Changes the default timezone from 'Europe/Dublin' to 'Etc/UTC' in setting model
- Updates acceptance test for settings general
- adds mirage fixtures values
=> Add UTC timezone as default in settings model

app/services/ajax.js
closes https://github.com/TryGhost/Ghost/issues/6884
- mark the `headers` method in the ajax service as "volatile" - it's dependent key was causing the auth headers to be cached on first use which would then cause 401 errors once the token had been refreshed externally
It would also be possible to add `session.authenticated.access_token` as a dependent key but the code-path and usage are minimal so I believe `.volatile()` is preferable as it means that it's not tied directly to the authorizer implementation.
=> Fix auth header caching in ajax service

app/routes/application.js, tests/acceptance/ghost-desktop-test.js
closes #51
- move the check into the `afterModel` hook so that it's always performed on app load (previously it would only be displayed after going through the sign-in process)
- change the alert type to `warn` so that it matches our existing types (success, warn, error)
- don't rely on the `.htmlSafe()` prototype extension
- add basic tests for the upgrade alert display
=> Fix and add tests for Ghost Desktop manual update notification

app/styles/layouts/content.css, app/templates/posts.hbs, app/templates/settings/labs.hbs
no issue
- improves internal-tags display on content page
- fix typo in settings/labs
Here is the screenshot of the new look:
=> internal-tags style followup

app/components/gh-editor-save-button.js, app/components/gh-posts-list-item.js, app/components/gh-spin-button.js, app/controllers/post-settings-menu.js, app/controllers/posts.js, app/helpers/gh-format-time-scheduled.js, app/helpers/gh-format-timeago.js, app/mirage/factories/post.js, app/mixins/editor-base-controller.js, app/models/post.js, app/services/clock.js, app/styles/components/notifications.css, app/styles/layouts/content.css, app/templates/components/gh-editor-save-button.hbs, app/templates/editor/edit.hbs, app/templates/post-settings-menu.hbs, app/templates/posts.hbs, tests/acceptance/editor-test.js, tests/acceptance/posts/post-test.js, tests/unit/helpers/gh-format-time-scheduled-test.js, tests/unit/models/post-test.js
refs TryGhost/Ghost#6413 and TryGhost/Ghost#6870
needs TryGhost/Ghost#6861
- **Post Settings Menu (PSM)**:'Publish Date' input accepts a date from now, min. 2 minutes to allow scheduler processing on the server. Also, there will always be some delay between typing the date and clicking on the 'Schedule Post' button. If the user types a future date for an already published post, the date will be reseted and he sees the message, that the post needs to be unpublished first. Once, the date is accepted, the label will change to 'Scheduled Date'.
- adds a CP 'timeScheduled' to post model, which will return `true` if the publish time is currently in the future.
- **Changes to the button flow in editor**:
- if the the CP `timeScheduled` returns true, a different drop-down-menu will be shown: …
=> Scheduler UI

Gruntfile.js
refs #7005
- add `grunt init` task that installs `npm` and `bower` dependencies
This task can be run from TryGhost/Ghost's Gruntfile so that bower does not need to be installed globally.
=> Add `grunt init` task

app/components/gh-trim-focus-input.js, app/templates/components/gh-navitem.hbs, app/templates/editor/edit.hbs, tests/integration/components/gh-trim-focus-input-test.js
no issue
- updates `gh-trim-focus-input` to extend from `gh-input`/`one-way-input` to get the auto-binding attribute behaviour for passed-in HTML attributes
- renames `focus` property to `shouldFocus` so that we're not overriding default DOM functions
- fixes signin page issues with missing placeholders and no autofocus
=> Fix un-bound HTML attributes for `gh-trim-focus-input`

.travis.yml
This prevents greenkeeper branches from being built as they will always by run in the PR.
=> Add greenkeeper branch ignores to travis

Gruntfile.js, package.json
refs TryGhost/Ghost#7039
- add bower dependency to client
split off of #90 to fix the above issue.
=> Add bower to client dependencies

app/templates/post-settings-menu.hbs
fix meta-data input field action calls
no issue
- fixed focus-out action calls in post-settings-menu meta fields which miss arguments metaDescriptionScratch and metaTitleScratch.
=> fix meta-data problem, which will cause SEO of post fail.

bower.json, ember-cli-build.js, package.json
no issue
- `ember-cli-node-assets@0.1.3`
- allows npm module assets to be loaded in a similar way to bower assets
- switching to npm deps means we get automated greenkeeper updates
- `codemirror@5.16.0` && bower->npm
- `ember@2.6.1`
- `jquery-deparam@0.5.2` && bower->npm
- `moment` bower->npm
- `moment-timezone` bower->npm
- `password-generator` bower->npm
- `blueimp-md5` bower->npm
This still leaves some bower dependencies, reasons for this include:
- the dependency only provides a bower component
- the dependency is pulled in through bower via another dependency (notably the `ember*`, `pretender`, `lodash`, and `Faker` deps)
- the dependency will be removed soon (`jquery-ui`, `jquery-file-upload`)
- the switch didn't work
- `validator.js` see #34
- `device.js` uses incompatible module …
=> update bower deps and start switch from bower to npm

ember-cli-build.js
refs TryGhost/Ghost#6149
- switches from a full import of jquery-ui to a partial build.
Filesize diff
| version | ghost.js | ghost.min.js | vendor.js | vendor.min.js |
|--------|-------:|-------:|--------:|--------:|
| master | 1,651,512 (1.6 M) | 855,384 (835 K) | 7,634,320 (7.2 M) | 1,950,683 (1.9 M) |
| with this PR | 1,651,512 (1.6 M)  | 855,384 (835 K) | 7,282,583 (6.9 M) | 1,773,896 (1.7M)
=> Only build parts of jquery-ui that we need

app/templates/post-settings-menu.hbs
no issue
- ensures that the current slug value is passed to the action instead of a `jQuery.event` object
=> fix `focusOut` event on slug input in PSM

package.json, tests/integration/components/gh-search-input-test.js
closes https://github.com/TryGhost/Ghost/issues/7073
- reverts `ember-wormhole` to 0.3.6
- adds working test that was broken under `ember-wormhole` 0.4.0
=> Revert to ember-wormhole@0.3.6

Gruntfile.js, package.json
refs #6977
- adds `grunt-contrib-clean` dependency
- adds `grunt clean` task that cleans the same client folders (plus `tmp`) as core's `grunt clean` ready to be used via subgrunt
=> Add `grunt clean` task

.travis.yml, package.json
Now that we're going to recommend v4, this means making it the default test environment.
Whilst I was looking around, I also updated the package.json file so the `engines` match Ghost's exactly. Not sure if there was a reason why they were different?
refs TryGhost/Ghost#7098
- Use Node v4 as our default build environment
- Change engines in package.json to match Ghost core
=> Recommend Node v4 & use as default

app/styles/components/notifications.css
closes TryGhost/Ghost#7100
Adds `:hover` pseudo-class to `gh-notification-schedule` that sets the curser to default to avoid having it as a pointer on hover.
=> Fixes curser changing to pointer on hover

.travis.yml
According to the docs, travis uses `exclude` in the matrix, but `except` in branches 😞
https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
- travis terminology is inconsistent :(
=> Fix: travis exception for greenkeeper branches

.gitignore, app/components/gh-upgrade-notification.js, app/routes/application.js, app/services/upgrade-notification.js, app/styles/layouts/about.css, app/templates/about.hbs, app/templates/components/gh-upgrade-notification.hbs, tests/unit/components/gh-upgrade-notification-test.js
Closes "Move the "update available" notification to the about page." part of #5071
Currently when a new upgrade is available, a banner displayed on top of the header, on all pages, which doesn't go away until the blog is upgraded. This message was moved to About page. The message won't go away till the blog is upgraded but it's far less annoying.
- New release notifications are shown only in About page instead of as a banner on the top
- Added `gh-upgrade-notification` component and `upgrade-notification` service 
- `app/routes/application.js` looks for notifications of type "upgrade" and invokes `upgrade-notification` service to render the message in `about.hbs`. 
- Added `gh-upgrade-notification` CSS classes to render message in red.
- Picked some fixes …
=> Added upgrade notification component to About page.

app/controllers/post-settings-menu.js, app/mirage/factories/post.js, app/mixins/editor-base-controller.js, app/services/notifications.js, tests/acceptance/editor-test.js, tests/unit/validators/subscriber-test.js
closes https://github.com/TryGhost/Ghost/issues/7099
- update editor base controller's `showErrorAlert` method to handle `AdapterError` or `AjaxError` objects
- update PSM's error handling so that we don't pass an error object wrapped in an array to `showAPIError` (this was causing the default error message to always be displayed and the global version mismatch/maintenance mode handling to be skipped if an error was encountered when changing a value in the PSM triggered a save)
- add missing title attribute to Mirage's Post factory
- remove some leftover `console.log`s
TODO:
=> Fix editor error handling

app/authenticators/oauth2.js
closes [#6868](https://github.com/TryGhost/Ghost/issues/6868) 
This improvement targets Ghost Admin users on unreliable internet connections. 
With intermittent internet connectivity, refreshing a token is a hit or miss. The library we use to handle OAuth authentication doesn't provide mechanisms to retry refreshing a token when a request to server fails. Also, currently there are [no provisions to catch/handle errors](https://github.com/simplabs/ember-simple-auth/issues/980) when Authenticator fails to connect to the server. 
The solution implemented in the PR is based on ideas presented [here](https://github.com/simplabs/ember-simple-auth/issues/980) and takes advantage of [navigator.online](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) event. Most [modern …
=> Fix for handling intermittent internet connectivity

app/mixins/editor-base-controller.js, tests/acceptance/editor-test.js
closes TryGhost/Ghost#7120
- fix error handling in editor-base-controller
- adds failing test fixed by this change
Note: this is a bit of a hack, but will be ultimately fixed by the validations refactor in #109
=> Ensure validation errors are shown on post save

app/components/gh-trim-focus-input.js, app/mirage/config.js, app/templates/signup.hbs, tests/acceptance/signup-test.js, tests/integration/components/gh-trim-focus-input-test.js
closes https://github.com/TryGhost/Ghost/issues/7117
- adds guard to `sanitizeInput` method of `gh-trim-focus-input` for null/undefined values
- adds acceptance test for successful signup screen flow
- removes unneeded validation/update handling for a non-editable email field
- adds "At least 8 characters" placeholder to password field
- fixes enter key not submitting the form when name or password field has focus
=> Fix blank signup screen

app/components/gh-image-uploader.js, app/templates/components/gh-ed-preview.hbs, app/templates/components/gh-image-uploader-with-preview.hbs, app/templates/components/gh-image-uploader.hbs, app/templates/post-settings-menu.hbs, tests/integration/components/gh-image-uploader-test.js
closes TryGhost/Ghost#7127
- image uploader now handles "text" and "alt text" differently
- adds quotes around alt text for readability
=> Fix image uploader text handling (again)

app/components/gh-timezone-select.js, app/controllers/settings/general.js, app/templates/components/gh-timezone-select.hbs, app/templates/settings/general.hbs, tests/integration/components/gh-timezone-select-test.js
refs https://github.com/TryGhost/Ghost/pull/7142, https://github.com/TryGhost/Ghost/pull/7143
- moves timezone selection template and logic into a component
- detect if the current `activeTimezone` is not in our pre-defined list of timezones, if it isn't:
- add a line indicating that there has been a manual override with the current `activeTimezone` value
- add a blank option to the timezone select list
=> Handle manual timezone override

package.json
Greenkeeper added it a `^` to walk-sync for some reason... 🤔
=> lock walk-sync version

LICENSE
noticed the MIT license file from the main Ghost repo hadn't been copied over.
Since this repo was only created this year, I changed the copyright date to start this year.
/cc @JohnONolan feel free to merge this if it looks good 👍
=> copy LICENSE from main Ghost repository

package.json
Greenkeeper.io created the branch but failed to open the PR.
Changes in 1.3.1 are minimal - backwards compatibility and docs updates.
=> chore(package): update ember-invoke-action to version 1.3.1

app/styles/layouts/subscribers.css
Closes TryGhost/Ghost#7163
* With flex-column, setting height to 100% will make the child the same
as the full height of the flex container, not fill up the remaining
space, so it was bleeding down below the viewport
=> Fix subscriber height being too tall for viewport

Gruntfile.js, package.json
refs TryGhost/Ghost#6977
- uses npm script's custom options to streamline ember commands
**NOTE** this will not work with npm versions < 2.0.0, due to the use of custom arguments to npm run scripts. However, as the latest maintenance releases of Node 0.10 ship with npm 2 as default, and node 0.10 support will be dropped in October, I think it's ok, especially as it only affects development.
=> Move ember build tasks over from main repository

app/styles/layouts/users.css, app/templates/team/index.hbs
Closes TryGhost/Ghost#7130
* Adds the user role to the invited users template
* Adjusts some css to keep the role on the right side
=> Add User Role to Invited Users

app/components/gh-navitem-url-input.js
Closes TryGhost/Ghost#7140
* Even if the url was blank, it was always appending a `/` at the end
which would cause isBlank to return false. Added logic that if the url
was blank, don’t try to then add the trailing slash.
=> Fix url field focus

app/components/gh-ed-preview.js, app/styles/components/splitbuttons.css, app/styles/components/uploader.css, tests/acceptance/ghost-desktop-test.js, tests/unit/components/gh-selectize-test.js, tests/unit/services/notifications-test.js, tests/unit/validators/nav-item-test.js, tests/unit/validators/slack-integration-test.js
This PR improves test success in all browsers, and fixes various issues with IE and Edge browsers.
Specific issues fixed:
- `<template>` element does not have a `content` property - closes TryGhost/Ghost#7149
- IE `flex` containers with a min-width property don't correctly vertically-align child elements - [bug](https://connect.microsoft.com/IE/feedback/details/816293/ie11-flexbox-with-min-height-not-vertically-aligning-with-align-items-center)
- Left side of split button in IE shows different height then the right side
=> Improve cross-browser support

app/controllers/post-settings-menu.js, app/templates/post-settings-menu.hbs
Closes TryGhost/Ghost#7138
* Fixes red error styling not showing up for meta title and meta
description on posts
=> Post meta error style fixes

tests/index.html
no issue
- with ember-cli 2.7 came the npm version of ember-cli-test-loader, making this line in `tests/index.html` throw 404 errors on tests
=> Remove test-loader asset from test html file

package.json
We could potentially use this to release new versions of Ghost-Admin; however, I feel like since that process is such a simple one for our use case, and Ghost-Admin doesn't really get released on its own, that this addon is a bit overkill. And given that there's no release config I didn't think it was being used.
This fixes one of the deprecation errors that occur at build-time.
=> Remove ember-cli-release dependency

app/mixins/editor-base-controller.js
- fixes travis test bug
This seems to happen fairly often in Travis tests, and causes them to need to be restarted incredibly often. I'm not sure if this points to a deeper issue, but as I cannot reproduce the issue locally my only thought was to figure out where the issue was coming from and ~~fix~~ work around it.
/cc @kevinansfield
=> Convert tagNames to use computed.mapBy

app/mirage/config.js, app/mirage/config/authentication.js, app/mirage/config/posts.js, app/mirage/config/roles.js, app/mirage/config/settings.js, app/mirage/config/slugs.js, app/mirage/config/subscribers.js, app/mirage/config/tags.js, app/mirage/config/users.js, app/mirage/utils.js
no issue
- moves mirage config for grouped endpoints into separate files to cleanup the `app/mirage/config.js` file
- endpoints are now mocked via a single `mockX(this)` call allowing for quick/easy mocking in the dev environment as well as the test environment without cluttering `config.js`
=> 💄 move grouped mirage config into separate files

app/styles/components/dropdowns.css, app/styles/components/settings-menu.css, app/styles/layouts/auth.css, app/styles/layouts/editor.css, app/styles/layouts/flow.css, app/styles/layouts/main.css, app/styles/layouts/users.css, app/styles/patterns/buttons.css, app/styles/patterns/global.css
Based on an increasingly popular trend and modern web typography capabilities, switch out Google Fonts for default native system fonts, tailored in a stack to suit every device. Also makes some very minor visual adjustments to suit.
Nixes all references to Google Fonts, and provides a faster rendering experience and fewer http requests. 💃 
Reference material:
- https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/
- https://medium.design/system-shock-6b1dc6d6596f#.rhqx5fmyz
Dependencies:
- https://github.com/TryGhost/Ghost-Admin/pull/211
- https://github.com/TryGhost/Ghost/pull/7219
- https://github.com/TryGhost/Ghost-Desktop/pull/190
=> Switch to new native system font stack

app/styles/layouts/apps.css
closes  TryGhost/Ghost#7222
Adds `right: 0` to `.apps-configured > i`, so the arrow doesn't overlap with the letters.
=> 🐛  Fix position of arrow in Apps UI

app/components/gh-file-upload.js, app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/controllers/settings/labs.js, app/templates/components/gh-file-upload.hbs, app/templates/components/gh-file-uploader.hbs, app/templates/components/gh-image-uploader.hbs, app/templates/settings/labs.hbs, tests/acceptance/subscribers-test.js, tests/acceptance/version-mismatch-test.js, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js
closes https://github.com/TryGhost/Ghost/issues/7144
- allow `gh-file-uploader`'s `accept` attr to be specified
- allows a `validate` action to be passed into `gh-image-uploader` and `gh-file-uploader` components that runs after a file is selected and before the upload starts
- adds a default `validate` action to `gh-image-uploader` and `gh-file-uploader` that triggers the normal `UnsupportedFileType` error when the selected file's mime-type does not match the `accept` attribute
=> ✨ validate file uploads against "accept" mime-type before uploading

package.json
closes Tryghost/Ghost#7245
Downgrades to `ember-one-way-controls` v0.9.2, as v1.0.1 had a bug when starting to type in the middle of the text inside of the input field.
=> ⬇️ 🐛  Downgrade to ember-one-way-controls 0.9.2

app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/components/gh-theme-table.js, app/components/modals/delete-theme.js, app/components/modals/upload-theme.js, app/controllers/settings/general.js, app/mirage/config.js, app/mirage/config/settings.js, app/mirage/config/themes.js, app/mirage/fixtures/settings.js, app/mixins/settings-save.js, app/router.js, app/routes/settings/general.js, app/routes/settings/general/uploadtheme.js, app/services/event-bus.js, app/styles/components/uploader.css, app/styles/layouts/settings.css, app/templates/components/gh-theme-table.hbs, app/templates/components/modals/delete-theme.hbs, app/templates/components/modals/upload-theme.hbs, app/templates/settings/general.hbs, app/templates/settings/general/uploadtheme.hbs, tests/acceptance/settings/general-test.js, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js, tests/integration/components/gh-theme-table-test.js, tests/integration/components/modals/upload-theme-test.js, tests/unit/controllers/settings/general-test.js, tests/unit/services/event-bus-test.js
refs https://github.com/TryGhost/Ghost/issues/7204, requires https://github.com/TryGhost/Ghost/pull/7209
- replaces theme dropdown with a table
- adds theme upload modal
- validates theme mime type
- prevents upload of `casper.zip` (default Casper theme can't be overwritten)
- warns if an upload will overwrite an existing theme
- gives option of immediately activating the uploaded theme or closing after successful upload
- adds theme activation link/action
- adds theme download link/action
- adds theme deletion modal
- warns about no undo possibility
- offers possibility to download theme
- modifies mirage config to handle theme changes
TODO:
=> Theme management

app/components/gh-theme-table.js, app/mirage/config/settings.js, app/mirage/config/themes.js, app/templates/components/gh-theme-table.hbs, app/templates/settings/general.hbs, tests/acceptance/settings/general-test.js, tests/integration/components/gh-theme-table-test.js
refs #210
- removes unused `activeTheme` property on `gh-theme-table`
- updates label generation in `gh-theme-table` to add folder names when there are duplicate package.json name+version combos
=> ✨ add folder names to tell duplicate themes apart 

app/mirage/config/settings.js, app/mirage/config/themes.js, tests/acceptance/settings/general-test.js
refs https://github.com/TryGhost/Ghost-Admin/pull/210
- adds missing acceptance tests for theme deletion
- adds theme deletion endpoint to mirage config
- fixes mirage settings update endpoint (was previously removing config that the client didn't send and also losing the `type` key for all entries preventing the `GET` request from working properly)
=> ✅ add final theme management acceptance tests

app/controllers/post-settings-menu.js
refs https://github.com/TryGhost/Ghost/issues/7255
- adds missing `slugGenerator` service injection
=> 🐛 fix post-settings-menu slug input

app/components/gh-task-button.js, app/styles/patterns/buttons.css
refs https://github.com/TryGhost/Ghost/issues/7255
- adds a `.appear-disabled` CSS class that doesn't prevent pointer events like `.disabled`
- updates `gh-task-button`:
- use `.appear-disabled` class instead of actually disabling button
- add check to guard against the button's assigned task being run multiple times whilst the spinner is running
This resolves the [user profile slug issue](https://github.com/TryGhost/Ghost/issues/7255) where clicking the Save button whilst the slug input has focus would only trigger the input's focus-out event due to it immediately disabling the button.
There is a simpler alternative where we use the button's `click` handler to disable the button then re-enable once the task finishes but this would mean that an external save event (eg. a keyboard …
=> 🐛 prevent task-buttons dropping clicks after focus-out events

app/styles/patterns/global.css
This splits out the font properties into individual rules to work around IE/Edge not following css font rule spec.
=> Fix font rendering in ie/edge

app/components/modals/upload-theme.js, app/services/ajax.js, app/styles/layouts/settings.css, app/templates/components/modals/upload-theme.hbs, tests/acceptance/settings/general-test.js
no issue
Display the detailed validation errors that we get back from gscan so that users know how to fix their theme
- add `ThemeValidationError` to custom ajax error types
- intercept failed theme uploads from the uploader component and switch to an "invalid theme" state if we have a theme validation error, otherwise display an error in the upload component as usual
TODO:
=> ✨ detailed theme validation errors

package.json
no issue
I've bumped the `package.json` version to `0.10.0` too early.
See https://github.com/TryGhost/Ghost-Admin/commit/a427aab11c9dd458a593094f6d1ee46c9203fed6
With this PR it gets reverted to `0.9.0`.
=> revert: package.json to 0.9.0

app/templates/settings/general.hbs
So we can link from inside of Ghost.org
=> 💄 Adding id to themes title for inter-linking

app/styles/layouts/settings.css
no issue
Theme uploader form in settings/general is now `max-width: 500px`, which is the same like any other form in settings.
=> 💄 Set max-width for theme uploader table

app/controllers/settings/labs.js
closes TryGhost/Ghost#7277
Adds `application/zip` to supported import file types.
=> 🐛  Allow .zip file upload for file import

app/models/notification.js, app/serializers/notification.js, app/styles/components/notifications.css, tests/unit/serializers/notification-test.js
closes https://github.com/TryGhost/Ghost/issues/7305
The `location` property of server-side notifications was being ignored by the client and so wasn't being used to de-duplicate alerts.
- adds `key` attribute to `Notification` model
- adds a serializer for notifications that renames the `location` key sent by the server to `key`
- set the default background color of alerts to white so that alerts with no `type` set do not inherit the background color (useful in Ghost Desktop which has a transparent background color set)
=> 🐛 fix duplicate server alerts + default alert bg color

app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/components/modals/upload-theme.js, tests/acceptance/subscribers-test.js, tests/acceptance/version-mismatch-test.js, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js
refs TryGhost/Ghost#7292
- remove accept mime type validations
- validate on file extension only
- fix tests
=> Remove mime-type validations in favor of extension validation

app/components/modals/upload-theme.js, app/templates/components/modals/upload-theme.hbs, tests/acceptance/settings/general-test.js
refs TryGhost/Ghost#7362, requires TryGhost/Ghost#7367
- display any gscan warnings we get back from a successful upload (very useful for the downgrade of missing `{{asset}}` helpers from an error to a warning)
=> ✨ display warnings after theme upload

app/components/gh-profile-image.js
Gravatar images are horribly pixelated on retina screens due to being pulled by default at 90px size. This PR increases default size to 180px to provide better rendering, at minimal file-size increase.
before:
after:
=> Double default gravatar size

package.json
Reverts TryGhost/Ghost-Admin#252
Using this version of `ember-one-way-controls` results in a bug that prevents the spacebar working when editing post titles.
I'm not sure if it's related to our own code or the addon but reverting to the known-working version for now.
=> Revert "Update ember-one-way-controls to version 1.1.1 🚀"

app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/styles/components/settings-menu.css, app/styles/components/uploader.css, app/templates/components/gh-image-uploader-with-preview.hbs, app/templates/components/modals/upload-image.hbs, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js, tests/integration/components/gh-image-uploader-with-preview-test.js
In reference to [#7310](https://github.com/TryGhost/Ghost/issues/7310)
This is not an Ember issue. Safari ignores classes that begin with `--`. I believe that none of the IEs allow these types of classes as well.
Example:
- https://jsfiddle.net/oy75f0L3/2/
Sources: 
- https://twitter.com/logicoder/status/654897918357434368
- https://www.reddit.com/r/web_design/comments/4ji5p7/safari_completely_ignores_classnames_starting/
Globally searched for modifier classes that start with `--` and removed the first dash. 
closes #7310
- Removes double dashes from modifier classes as safari won’t allow
this.
=> Safari doesn't show dragged-over state for file uploads

app/controllers/setup/two.js, app/services/ajax.js, package.json, tests/integration/services/ajax-test.js
no issue
- update ember-ajax to 2.5.1
- replace custom error checking in setup/two with ember-ajax's `isInvalidError`
- update error normalisation and associated parsing tests to ensure all error types result in the same object structure
=> deps: ember-ajax@2.5.1

app/components/gh-user-invited.js, app/components/modals/invite-new-user.js, app/controllers/setup/three.js, app/controllers/team/index.js, app/mirage/config.js, app/mirage/config/invites.js, app/mirage/factories/invite.js, app/models/invite.js, app/models/user.js, app/routes/team/index.js, app/serializers/invite.js, app/templates/components/modals/invite-new-user.hbs, app/templates/team/index.hbs, tests/acceptance/setup-test.js, tests/acceptance/team-test.js, tests/unit/models/invite-test.js, tests/unit/models/user-test.js
issue https://github.com/TryGhost/Ghost/issues/7420, requires https://github.com/TryGhost/Ghost/pull/7422
- adds a new `Invite` model with associated serializer and test setup
- updates team screen to use invites rather than existing users with the "invited" property
- updates signup process to work with new invite model
- updates setup process to create invites instead of users
- swaps usage of `gh-select-native` for `one-way-select` in the invite modal so that attributes can be set on the `select` element
- updates resend invite process to account for server returning a new model
- rewrites the invite management tests and fixes mirage mocks for invite endpoints
- sorts invites by email address to avoid jumping invites when re-sending
TODO:
=> Separate invites and users

app/adapters/base.js, app/components/modals/new-subscriber.js, app/mirage/config/authentication.js, app/mixins/editor-base-controller.js, app/serializers/user.js, app/services/ajax.js, app/services/notifications.js, tests/acceptance/signup-test.js, tests/acceptance/team-test.js
closes TryGhost/Ghost#7014
- uses the `AjaxServiceSupport` mixin from `ember-ajax` to replace Ember Data's internal `ajax` method with our own ajax service
- normalizes all error handling to use `ember-ajax` style errors
- default to the `application/vnd.api+json` content-type so that we don't have a mix of urlencoded and plain JSON content
TODO:
=> use ember-ajax in place of ember-data's networking

app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/styles/components/settings-menu.css, app/styles/components/uploader.css, app/templates/components/gh-image-uploader-with-preview.hbs, app/templates/components/modals/upload-image.hbs, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js, tests/integration/components/gh-image-uploader-with-preview-test.js
closes TryGhost/Ghost#7310
- Removes double dashes from modifier classes as safari won’t allow this.
=> LTS backport: Safari doesn't show dragged-over state for file uploads (#288)

app/authenticators/oauth2-ghost.js, app/components/modals/re-authenticate.js, app/controllers/setup/two.js, app/controllers/signin.js, app/controllers/team/user.js, app/mirage/config/authentication.js, app/routes/setup.js, app/routes/setup/two.js, app/routes/signup.js, app/services/config.js, app/templates/components/modals/re-authenticate.hbs, app/templates/setup/two.hbs, app/templates/signin.hbs, app/templates/signup.hbs, app/templates/team/user.hbs, app/torii-providers/ghost-oauth2.js, app/validators/new-user.js, app/validators/setup.js, config/environment.js, package.json, tests/acceptance/setup-test.js, tests/acceptance/signin-test.js, tests/acceptance/signup-test.js, tests/acceptance/team-test.js, tests/helpers/oauth.js, tests/index.html, tests/integration/components/gh-theme-table-test.js
issue TryGhost/Ghost#7452, requires TryGhost/Ghost#7451
- use a `ghostOAuth` config flag to switch between the old-style per-install auth and centralized OAuth auth based on config provided by the server
- add OAuth flows for:
- setup
- sign-in
- sign-up
- re-authentication
- add custom `oauth-ghost` authenticator to support our custom data structure
- add test helpers to stub successful/failed oauth authentication
- hide change password form if using OAuth (temporary - a way to change password via oauth provider will be added later)
TODO:
=> ✨ Ghost OAuth

package.json
No need to ignore/ping these on the lts branch as greenkeeper doesn't run on that branch. However, it seems smart to shove this into the package.json so that we don't get bugged by greenkeeper about grunt stuff now we're moving away from it.
closes #290
- We're moving away from grunt, so lets not worry about version bumps for now
=> 🛠 Make greenkeeper ignore grunt dependencies

app/services/ajax.js, package.json
no issue
- pin `ember-ajax` on a version that contains related fixes (https://github.com/ember-cli/ember-ajax/issues/147)
- update our `ajax` service so that it defaults to `application/json` content-type rather than forcing it
=> 🐛 fix file uploads

app/components/gh-fullscreen-modal.js, app/styles/components/modals.css, app/templates/components/gh-fullscreen-modal.hbs, app/transitions.js, package.json
no issue
- remove `liquid-tether` dependency
- add `liquid-wormhole` dependency (previously a dependency of liquid-tether)
- refactor `gh-fullscreen-modal` to simplify and use `liquid-wormhole` directly instead of `liquid-tether` as we don't need the positioning ability that `liquid-tether` provides
- fixes broken View/Component tree in Ember Inspector 🎉
=> Refactor `gh-fullscreen-modal` component

Gruntfile.js, app/components/gh-cm-editor.js, app/helpers/gh-path.js, app/templates/about.hbs, app/templates/error.hbs, app/templates/settings/apps/index.hbs, app/templates/settings/apps/slack.hbs, app/templates/setup/one.hbs, app/templates/setup/three.hbs, app/utils/ghost-paths.js, ember-cli-build.js
See TryGhost/Ghost#7503 for a hopefully clear explanation of why I'm making this change 
I have changed to having both an `admin` and an `asset` path because, although I can't find any usages of `admin`, I didn't want to hijack the term "admin" to mean "asset".
=> 🎨  Change asset path to /ghost/assets

app/mirage/fixtures/settings.js, app/models/tag.js, app/services/feature.js, app/templates/components/gh-tag.hbs, app/templates/posts.hbs, app/templates/settings/labs.hbs
Related to Ghost#7519, which removes all the server-side logic for the internalTags labs flag.
refs Ghost#6165
- it's time to move internal Tags out of labs!
- remove the checkbox & all lab/feature flag code for internalTags
=> ✨ Move internal tags out of labs

app/authenticators/oauth2-ghost.js, app/mirage/config/authentication.js
issue TryGhost/Ghost#7562, requires TryGhost/Ghost#7571
- removes the custom endpoint so that we always use `/authentication/token`
=> remove custom token endpoint when using Ghost OAuth

app/routes/editor/edit.js, app/templates/editor/edit.hbs, package.json
Refs TryGhost/Ghost#7429
Depends on: https://github.com/TryGhost/Ghost/pull/7568
Just a quick update in lieu of a larger overhaul to come through next PR:
- Added mobiledoc card, this uses the mobiledoc editor from within Ghost. In the future we'll pull this out and replace it with a textarea as the preview is too small to fit in the content.
- Made the HTML editor a codemirror editor (pulled in from ghost-admin to save duplicating libraries).
- Ghost-Admin now passes the paths for the ghost-api and the image directory for tools.
- Fixed the scrolling issue.
- Added an obnoxious label on top of each card so you know what they do.
=> Markdown card

app/services/ajax.js, tests/integration/services/ajax-test.js
issue TryGhost/Ghost#5202
We can get into a situation where the app is left open without a network connection and the token subsequently expires, this will result in the next network request returning a 401 and killing the session. This is an attempt to detect that and restore the session using the stored refresh token before continuing with the request
- wrap ajax requests in a session restore request if we detect an expired `access_token`
=> Attempt expired session restore on network requests

app/components/gh-posts-list-item.js, app/components/gh-profile-image.js, app/components/gh-user-active.js, app/controllers/team/user.js
no issue
- #309 introduced a change to our asset path but some images, particularly around the team page and user avatars were missed, this fixes those URLs to use the new `ghostPaths.assetRoot` helper
=> 🐛 fix more asset paths

bower.json
no issue
- Glimmer2 was backed out of the 2.9 branch as it wasn't considered ready yet, 2.9 is therefore safe to upgrade to as changes are very minimal from the previous 2.8.2 version
=> deps: ember@2.9.0

package.json
no issue
- the changes for which we had pinned to a specific commit are now part of a proper release
=> deps: ember-ajax@2.5.2

app/mixins/editor-base-controller.js, app/routes/editor/edit.js, app/styles/layouts/editor.css, app/styles/patterns/global.css, app/templates/editor/edit.hbs, package.json, tests/acceptance/editor-test.js
This bumps the editor to 14 (13 wasn't so lucky).
Requires: https://github.com/TryGhost/Ghost/pull/7619
Refs: https://github.com/TryGhost/Ghost/issues/7429
It includes:
- The title is integrated into the content.
- The toolbar has been revamped, that annoying under paragraph toolbar has been removed in favor of a block level changed (on the left hand side of the content).
- The toolbar also has the ability to create links.
- Additional markdown support within the editor including `# h1 headings`, `## h2 headings`, `### h3 headings`, `1. lists`, `* lists`, `- lists`, `> blockquote`, `_italic_`, `*italic*`, `__bold__`, `**bold**`, `~~strikethrough~~`, `[links](http://www.ghost.org/)`, `![images](https://placekitten.com/200/300)` (warning will replace the entire block).
Footnotes and …
=> New editor layout

app/index.html, app/mirage/config.js, app/mirage/config/configuration.js, app/mirage/fixtures/configurations.js, app/routes/application.js, app/services/config.js, app/torii-providers/ghost-oauth2.js, tests/acceptance/setup-test.js, tests/acceptance/signin-test.js, tests/acceptance/signup-test.js, tests/acceptance/team-test.js, tests/helpers/configuration.js, tests/index.html, tests/integration/services/feature-test.js, tests/unit/services/config-test.js
issue https://github.com/TryGhost/Ghost/issues/7628, requires https://github.com/TryGhost/Ghost/pull/7631
- update `config` service to fetch from public configuration endpoint
- add `beforeModel` to `application` route to fetch config and pause further processing until the request is complete
- remove `<meta name="env-*">` tags from generated `default.hbs` and internal testing `index.html`
- add mirage config to mock configuration endpoint
- update `ghost-oauth2` torii provider to use auth server URL from server-provided config
=> Fetch config from endpoint rather than meta tags

package.json
refs TryGhost/Ghost#7466
- Node v6.9 became LTS on 18th Oct
- Node v0.10 is EOL on 31st Oct
- These values are consistent with Ghost, for the v0.11 LTS stream of Ghost
- On Ghost master, these values match ember-cli
=> 💄 LTS node version in `engines` (+v6.9 -v0.10)

package.json
For some reason greenkeeper isn't upgrading ghost-editor. This upgrades it to the latest version.
=> Updated ghost-editor to 0.1.4

app/templates/components/modals/import-subscribers.hbs
no issue
- recent changes to the way our modals work has resulted in the subscribers import modal appearing blank. The `liquid-if` used for transitioning between upload and result state doesn't run properly and the styles end up hiding the contents
- this PR is a quick-fix that removes the animated transition so that imports are still possible
=> Fix empty subscribers import modal

app/mirage/factories/role.js, app/mirage/factories/setting.js, app/mirage/factories/subscriber.js, app/mirage/factories/tag.js, app/mirage/factories/user.js, app/mirage/fixtures/roles.js, app/mirage/fixtures/settings.js, app/models/role.js, app/models/subscriber.js, app/models/tag.js, app/models/user.js, app/serializers/application.js, app/serializers/tag.js
refs https://github.com/TryGhost/Ghost/issues/7494
- remove `uuid` attrs from all models except Post
- remove uuids from mirage factories and fixtures
- add a workaround for tags where the selectize-based tags input on the PSM relies on a unique identifier for each tag which doesn't get sent back to the server when saving (fixes the broken tags input caused by uuid removal in https://github.com/TryGhost/Ghost/pull/7495)
=> Remove UUID attrs from all models except Post

app/models/post.js, tests/unit/models/post-test.js
closes TryGhost/Ghost#7730
- treat `Post.authorID` as a string not a number as it's now an objectid
- update `isAuthoredByUser` method so that author's posts aren't hidden from them
- update the post compare method so that it doesn't try to parse objectids as integers (may need revisiting now that we don't have auto-increment IDs to fall back on)
=> Fix inability to write posts as an author

app/torii-providers/ghost-oauth2.js
no issue
- use the configured `blogUrl` value rather than using `window.location.href` with a poor regex that was incorrectly matching on domains containing multiple `/ghost` parts such as `http://ghost.local:2368/ghost`
=> 🐛 fix oAuth login for blog urls which contain `/ghost`

app/routes/setup.js
no issue
- fixes an issue where landing on setup/three with a temporary token would appear to work until you clicked the invite or skip buttons at which point you landed back on the signin screen
- ESA requires data to be persisted to the store (LocalStorage/cookie) before a session can be "restored"
=> 🐛 fix session restoration on setup/three with temp token

app/routes/setup.js
no issue
- the `/authentication/setup/three/` endpoint is now returning seconds in order to be consistent with all other oauth2 responses, this PR updates our response handling to convert seconds to ms and store the coorect `expires_at` value
- adds `token_type: 'Bearer'` to the session config to fully match a normally acquired session
=> 💄 expires_in is always in seconds

package.json
no issue
- ember-watson does not need to be included in our dependency list, it has limited one-time usage and is better used as a global install for developers who want to run any of it's codemods
=> remove ember-watson dependency

app/controllers/settings/general.js, app/templates/settings/general.hbs
closes #7746
- Added gh-form-group around PostsPerPage
- Changed focusOut action to validate
- Removed now redundant `checkPostsPerPage()` call
=> Show error message for invalid data in PostsPerPage LTS

tests/helpers/destroy-app.js
no issue
- ensure our mirage server is shutdown during app teardown in acceptance tests
- a [recent update](https://github.com/pretenderjs/pretender/pull/178) to Pretender contained a breaking change that throws an error when multiple pretender instances exist
- using mirage in acceptance tests was [triggering the error](https://github.com/samselikoff/ember-cli-mirage/issues/915)
=> add manual pretender shutdown to fix acceptance tests

tests/helpers/destroy-app.js
no issue
- `liquid-tether` which we use for modals leaves container elements behind when it's used within acceptance tests which then interfere with the integration tests because integration tests expect the first element in the testing container to be the rendered component
=> fix tests on LTS

tests/helpers/destroy-app.js
no issue
- a [recent update](https://github.com/pretenderjs/pretender/pull/178) to Pretender contained a change that throws warnings when multiple pretender instances exist
- using mirage in acceptance tests was [triggering the warning](https://github.com/samselikoff/ember-cli-mirage/issues/915)
=> add manual pretender shutdown to remove warnings in test logs

.travis.yml, app/mirage/config.js, package.json
- add code coverage via ember-cli-code-coverage and coveralls
- improve test running by filtering out eslint tests during main test run
=> Add code coverage

app/styles/layouts/settings.css
In reference to [#7373](https://github.com/TryGhost/Ghost/issues/7373)
When adding long theme names the theme layout is broken. Ew!
- Removed `white-space: nowrap;' to the theme name container to allow breaking.
- Added `flex: 1;` to sibling elements (`.theme-list-item-body` and `.theme-list-item-aside`)
- Aligned links inside `.theme-list-item-aside` to the right. 
Desktop 
Mobile
=> Long theme names break themes table layout

app/helpers/gh-count-characters.js, app/helpers/gh-count-down-characters.js, tests/unit/helpers/gh-count-characters-test.js, tests/unit/helpers/gh-count-down-characters-test.js
closes https://github.com/TryGhost/Ghost/issues/7739
- use es6's `Array.from` to convert the string to an array to get a symbol count rather than a byte count
=> 🐛 correctly count multibyte chars in character counters

app/components/gh-loading-spinner.js, app/routes/settings/apps.js, app/styles/components/loading-indicator.css, app/templates/components/gh-loading-spinner.hbs, app/templates/components/gh-subscribers-table.hbs, app/templates/editor/edit-loading.hbs, app/templates/posts-loading.hbs, app/templates/settings/apps-loading.hbs, app/templates/settings/code-injection-loading.hbs, app/templates/settings/general-loading.hbs, app/templates/settings/labs-loading.hbs, app/templates/settings/navigation-loading.hbs, app/templates/settings/tags-loading.hbs, app/templates/settings/tags.hbs, app/templates/team/index-loading.hbs, app/templates/team/user-loading.hbs, tests/acceptance/version-mismatch-test.js
no issue
- add loading substates for all routes that previously blocked transitions until their model had finished loading
- enables immediate response on navigation click
- loading templates include the title bar to provide immediate indication of which page is loading
- loading templates include a new `{{gh-loading-spinner}}` component that will only show the spinner after 200ms to avoid flashing a spinner for users on fast connections
=> 🏃 improve navigation responsiveness with loading substates

package.json, tests/helpers/start-app.js, yarn.lock
Greenkeeper has been turned off so we're back to periodic dependency update roll-ups, fortunately `yarn` makes this *much* quicker and more convenient than `npm` ever did 😁 
- ember-cli@2.10.1
- ember-cli-chai@0.3.2
- ember-cli-code-coverage@0.3.10
- ember-power-select@1.2.0
- ember-route-action-helper@2.0.2
- password-generator@2.1.0
=> Dependency updates

.travis.yml
Workaround for yarnpkg/yarn#1981
Found in this commit: https://github.com/tjgrathwell/ng-picross/commit/22d55c04b236f0b7647e8c8a7813047ac183009a
=> Add workaround for yarn node-sass bug

package.json, yarn.lock
no issue
- note: this does not include the switch from using bower for ember + ember-cli-shims as we are currently on an older ember version.
=> deps: ember-cli@2.11.0

app/components/gh-image-uploader.js, app/controllers/settings/general.js, app/models/setting.js, app/templates/components/gh-image-uploader.hbs, app/templates/components/modals/upload-image.hbs, app/templates/settings/general.hbs, app/templates/team/user.hbs, mirage/fixtures/settings.js, tests/acceptance/settings/general-test.js
refs TryGhost/Ghost#7688
needs TryGhost/Ghost#7893
Adds new upload functionality for a blog icon in general settings.
Icons will be uploaded to a new endpoint `uploads/icons` to trigger different validations.
Todo:
=> ✨  Blog icon upload

app/services/config.js, tests/integration/services/config-test.js
no issue
- update `config` service normalise blogUrl to non-trailing slash to match previous API behaviour
- fixes double slashes appearing in places around the app
- fixes "Redirect URI Mismatch" errors when using Ghost OAuth due to the double slashes
=> 🐛 fix double slashes in URLs

.travis.yml
no issue
- adds yarn cache to travis
- uses latest version of yarn via npm install
=> Use latest version of Yarn in travis

app/controllers/settings/general.js
no issue
-  `settings/general` controller contained a number of `xImageSource` CPs that are no longer being used
=> 🔥 remove unused cps

app/templates/team/index.hbs
closes TryGhost/Ghost#7890
- moved the modal outside of the `<header>` tag to avoid triggering unexpected flexbox justification
=> 🐛 fix jumping "Invite User" button when modal is opened

app/torii-providers/ghost-oauth2.js
refs https://github.com/TryGhost/Ghost/issues/7907
- rather than forwarding the redirect URI as configured in Ghost we should use the URL that the admin client is currently loaded on when setting the Ghost OAuth `redirectUri` attribute
- fixes issue with the admin app loading inside of the OAuth popup window and not logging in when using https with a registered http redirect uri
=> use current URI instead of configured blog URI for OAuth redirectURI

app/routes/reset.js, app/routes/signup.js
no issue
- aligns those routes more with the ember-simple-auth method of doing things
=> Refactor signin/signup/setup/reset routes to use correct route mixin

app/components/gh-nav-menu.js, app/templates/components/gh-nav-menu.hbs
no issue
- the content filter will be remembered if you navigate away from and then back to the content screen
- this PR changes the behaviour slightly so that clicking the sidebar "Content" link whilst viewing the content screen will act as a shortcut to reset the filter
=> Content link resets filter if already viewing content screen

app/routes/application.js, tests/acceptance/authentication-test.js
refs https://github.com/TryGhost/Ghost/issues/5202
- refresh the access token after a successful authenticated application boot so that the session lifetime is continually extended
=> refresh access token on app boot

app/components/gh-trim-focus-input.js, package.json
closes https://github.com/TryGhost/Ghost/issues/7886
- deps: ember-one-way-controls@2.0.0
- adjust `gh-trim-focus-input` for the removal of `sanitizeInput` method and to trim value only on focus-out to avoid trailing spaces being removed whilst using backspace
Backport of https://github.com/TryGhost/Ghost-Admin/pull/475 for LTS
=> Update ember-one-way-controls to version 2.0.0

app/templates/components/gh-search-input.hbs
closes TryGhost/Ghost#8013
- ember-power-select yields the select public api object instead of just
the searchterm
Probably during the 1.0 update, the yield of `power-select` changed from `searchText` to the entire select object. Because we were converting that object to a regex, it was matching based on `/[object Object]/` which is why the highlighting styles were off.
=> Fix gh-search-input highlighting

app/components/gh-cm-editor.js
closes TryGhost/Ghost#7855
- check if codemirror has been initialized before trying to destroy it
note - the codemirror initialization happens inside a `scheduleOnce`, so I'm fairly certain that if the component is destroyed before the codemirror script finishes loading, then the scheduleOnce won't be called and we won't have to worry about extraneous objects.
=> Don't destroy codemirror editor if it doesn't exist

package.json
Upgrades Ghost-Editor to 0.1.9
- Adds drag and drop image support within the markdown card.
- Adds drag and drop image support within the editor.
- The slash menu now renders in the next run-loop which means it should always be located at the correct place.
- The editor scrolls to follow the caret if it's off screen.
=> Editor 0.1.9

.travis.yml
no issue
- persisting the broccoli cache should dramatically speed up the client builds on Travis as it will only need to rebuild changed files and those that depend on them
- re-enable yarn on Travis
=> 🏃 persist broccoli cache + re-enable yarn on Travis

app/templates/posts/index.hbs
no issue
- changes to layout meant that every page was automatically requested upon loading the content screen, this changes the infinite scroll trigger to match the new scrollable element
=> 🐛 fix posts screen infinite scroll

app/components/gh-user-invited.js, app/templates/team/index.hbs, mirage/config/invites.js, mirage/factories/invite.js, tests/acceptance/setup-test.js, tests/acceptance/team-test.js
closes https://github.com/TryGhost/Ghost/issues/8055
- use `expired` if the date is in the past, otherwise `expires`
- fix mirage factories to use `moment.valueOf` instead of `moment.unix` for invite `expires` attributes
=> 🐛 display correct expired/expires text for invites

app/controllers/posts-loading.js, app/controllers/posts.js, app/routes/posts.js, app/templates/components/gh-nav-menu.hbs, app/templates/posts-loading.hbs, app/templates/posts.hbs, mirage/models/post.js, mirage/models/user.js, tests/.eslintrc.js, tests/acceptance/content-test.js, tests/acceptance/editor-test.js, tests/acceptance/version-mismatch-test.js, tests/helpers/start-app.js
refs https://github.com/TryGhost/Ghost/issues/7860
- removes post type filter links
- adds dropdown filters for post type, author, and tag
- replaces custom refresh on query params change with Ember's standard `refreshModel` config
TODO:
=> ✨ dropdown filters for post type, author, and tag

app/controllers/team/user.js, app/styles/patterns/boxes.css, app/templates/team/user.hbs
no issue
- removes user email field when using Ghost OAuth because email addresses are synced from the central identity management system
- adds a link to my.ghost.org account management when using Ghost OAuth and viewing your own user
Link to my.ghost.org currently looks like this, we probably want to make this more prominent as part of https://github.com/TryGhost/Ghost/issues/8021
=> remove email field when using OAuth, direct users to my.ghost.org

app/components/gh-image-uploader-with-preview.js, app/components/gh-image-uploader.js, app/components/gh-profile-image.js, app/styles/components/uploader.css, app/templates/components/gh-ed-preview.hbs, app/templates/components/gh-image-uploader-with-preview.hbs, app/templates/components/gh-image-uploader.hbs, app/templates/components/gh-profile-image.hbs, app/templates/components/modals/upload-image.hbs, app/templates/settings/general.hbs, app/templates/setup/two.hbs, app/templates/signup.hbs, app/templates/team/user.hbs, lib/gh-koenig/addon/components/cards/image-card.js, lib/gh-koenig/addon/templates/components/image-card.hbs, tests/acceptance/settings/general-test.js, tests/integration/components/gh-image-uploader-test.js, tests/integration/components/gh-profile-image-test.js
refs https://github.com/TryGhost/Ghost/issues/8032
- `fileStorage: false` config is going away, it predates storage engines and will simplify future image optimisation work
- simplifies UI, it can be brought back in the future in a more robust fashion if required
=> 🔥 remove URL input option from image upload components

app/components/gh-task-button.js, app/components/modals/new-subscriber.js, app/styles/patterns/buttons.css, app/templates/components/gh-modal-dialog.hbs, app/templates/components/gh-task-button.hbs, app/templates/components/modals/delete-all.hbs, app/templates/components/modals/delete-post.hbs, app/templates/components/modals/delete-subscriber.hbs, app/templates/components/modals/delete-tag.hbs, app/templates/components/modals/delete-theme.hbs, app/templates/components/modals/delete-user.hbs, app/templates/components/modals/invite-new-user.hbs, app/templates/components/modals/new-subscriber.hbs, app/templates/components/modals/re-authenticate.hbs, app/templates/components/modals/transfer-owner.hbs, app/templates/components/modals/upload-image.hbs, app/templates/reset.hbs, app/templates/team/user.hbs, tests/acceptance/settings/general-test.js, tests/integration/components/gh-task-button-test.js
refs https://github.com/TryGhost/Ghost/issues/7515
- changes to `gh-task-button`:
- can take `buttonText` (default: "Save"), `runningText` ("Saving"), `successText` ("Saved"), and `failureText` ("Retry") params
- positional param for `buttonText`
- default button display can be overridden by passing in a block, in that scenario the component will yield a hash containing all states to be used in this fashion:
```
{{#gh-task-button task=myTask as |task|}}
{{if task.isIdle "Save me"}}
{{if task.isRunning "Saving"}}
{{if task.isSuccess "Thank you!"}}
{{if task.isFailure "Nooooooo!"}}
{{/gh-task-button}}
```
- update existing uses of `gh-task-button` to match new component signature
This PR only introduces the basics so that initial testing can be done and further `ember-concurrency` refactors …
=> ✨ success/failure state spinner buttons

app/adapters/theme.js, app/components/gh-theme-table.js, app/components/modals/upload-theme.js, app/controllers/settings/design.js, app/models/setting.js, app/models/theme.js, app/routes/settings/design.js, app/templates/components/gh-theme-table.hbs, app/templates/settings/design.hbs, app/templates/settings/design/uploadtheme.hbs, mirage/config/themes.js, mirage/fixtures/settings.js, mirage/fixtures/themes.js, tests/acceptance/settings/design-test.js, tests/integration/components/gh-theme-table-test.js
requires https://github.com/TryGhost/Ghost/pull/8093
- adds `theme.activate()` method and associated adapter method for activating themes rather than relying on `settings.activeTheme`
- minor refactors to the `modals/upload-theme` component to use a full theme model
=> 🎨 move theme activation to /themes endpoint

app/components/gh-task-button.js, app/controllers/signin.js, app/routes/signin.js, app/templates/signin.hbs, tests/integration/components/gh-task-button-test.js
refs https://github.com/TryGhost/Ghost/issues/7865
- convert all signin related actions to ember-concurrency tasks and consolidate in the signin controller rather than spread across controller+route
- add `successClass` and `failureClass` params to `gh-task-button` that can be used to override the default success/failure button classes
- prevent clicks on `gh-task-button` from triggering form actions (this behaviour should never be necessary, task buttons should either be separate to the form as in the "forgot?" button or the form action performs the same task and can be triggered by a standard form submit)
=> 🎨 refactor signin screen to use ember-concurrency & gh-task-button

app/authenticators/oauth2-ghost.js, app/components/modals/suspend-user.js, app/components/modals/unsuspend-user.js, app/controllers/team/index.js, app/controllers/team/user.js, app/models/user.js, app/routes/application.js, app/routes/team/index.js, app/templates/components/gh-nav-menu.hbs, app/templates/components/modals/suspend-user.hbs, app/templates/components/modals/unsuspend-user.hbs, app/templates/team/index.hbs, app/templates/team/user.hbs, mirage/config/users.js, tests/acceptance/team-test.js, tests/integration/components/gh-task-button-test.js, tests/unit/models/user-test.js
requires https://github.com/TryGhost/Ghost/pull/8114
- adds "(Un-)Suspend User" options on user profile page with a modal confirmation screen
- separates team index into "active" and "suspended" users
- adds "suspended" badge to user profile when suspended
- updates `oauth2-ghost` authenticate method to handle an ember-ajax error object instead of an xhr (fixes "There was a problem on the server" message instead of "Your account has been suspended" when trying to log in)
- bumps `gh-task-button` test timeouts to avoid random test failures
TODO:
=> ✨ suspend user feature

app/controllers/settings/tags/tag.js
no issue
- fixes error thrown when you focus in/focus out of a field in the tags
editor without entering anything
=> fix(tag): ensure tag property exists before trying to trim it

app/components/gh-post-settings-menu.js, app/templates/components/gh-post-settings-menu.hbs, mirage/config/posts.js, tests/acceptance/editor-test.js, tests/unit/components/gh-post-settings-menu-test.js
closes https://github.com/TryGhost/Ghost/issues/8122
- because the PSM is now a component, some of the component lifecycle
hooks can be employed to load things
=> fix(psm): fix author dropdown in post-settings-menu

app/adapters/theme.js, app/components/gh-theme-error-li.js, app/components/modals/theme-warnings.js, app/controllers/settings/design.js, app/models/theme.js, app/templates/components/gh-theme-error-li.hbs, app/templates/components/modals/theme-warnings.hbs, app/templates/components/modals/upload-theme.hbs, app/templates/settings/design.hbs, mirage/config/themes.js, tests/acceptance/settings/design-test.js
closes https://github.com/TryGhost/Ghost/issues/8127
- update theme activation to manually set other themes to `active: false` in the store now that we only get the active theme back from `/themes/:name/activate` endpoint
- move theme warning list item rendering into `{{gh-theme-error-li error=x}}`
- add `theme-warnings` modal that accepts a warnings list, title, and optional message
- after activating a theme, check if the theme has any warnings or errors and display an appropriate modal informing the user
=> ✨ show theme warnings/errors when activating a theme

app/index.html, app/initializers/trailing-hash.js, app/mixins/unauthenticated-route-mixin.js, app/routes/reset.js, app/routes/signin.js, app/routes/signup.js, config/environment.js, ember-cli-build.js, lib/asset-delivery/index.js, package.json, tests/acceptance/authentication-test.js, yarn.lock
requires https://github.com/TryGhost/Ghost/pull/8142
- switch to hash-location rather than history-location
- remove usage of Ghost's `{{asset}}` helper in index.html
- add `content-for` helpers to `asset-delivery` addon that switch asset urls in index.html to `.min` files in production
- update the `asset-delivery` addon to copy the production `index.min.html` to `default-prod.hbs` so Ghost can serve production assets when in production mode
- enable asset fingerprinting
- add `ember-cli-inject-live-reload` dependency
- remove `ember-cli-sri` dependency - we weren't using it but now that ember is handling assets it was used automatically and could potentially create issues if users have proxy servers that attempt to compress or otherwise modify asset files
This cuts the final tie that …
=> 🎨 remove usage of ghost's {{asset}} helper in index.html

app/models/setting.js, app/validators/setting.js, mirage/fixtures/settings.js, tests/integration/services/feature-test.js
requires https://github.com/TryGhost/Ghost/pull/8149
- "posts per page" is now a theme-level concern
- UI has already been removed, this finishes the cleanup by removing `settings.postsPerPage` and related validation/test support
=> 🔥 remove settings.postsPerPage

lib/gh-koenig/addon/components/koenig-slash-menu.js, lib/gh-koenig/addon/options/default-tools.js
Refs: https://github.com/TryGhost/Ghost/issues/8157
Currently mobiledoc-kit doesn't allow the inserting or replacing of a list item with a card.
There is a solution that works toggling the section to a `p` then replacing the section, however there are issues with the mobiledoc range object becoming out of sync and the workarounds for that are too hacky.
We need to update mobiledoc to deal with this use case (although the way that ranges are handled during undo might also be an option worth exploring), but for now we'll simply insert a card at the bottom of the list which is unfortunately different behaviour from any other block.
=> 🐝  Add cards in lists.

lib/gh-koenig/addon/components/koenig-toolbar.js
closes: https://github.com/TryGhost/Ghost/issues/8163
Previously when you created a link the toolbar component would re-render and dissapear.
This update ensures that the logic that must happen on first render does not happen on subsequent renders.
=> 🐜 🐝  Create link from toolbar.

lib/gh-koenig/addon/components/koenig-plus-menu.js
When a user clicks on the plus button it opens the card menu, when they click on it twice the card menu input field loses focus and the card menu closes, because the Range object of the document is no longer within the editor the '+' button also disappears. This has the effect of making the '+' button disapear when double clicking.
Now when the input field to search cards loses focus the card menu disapears but the '+' button remains, we rely on the cursorDidChange event to also hide the button.
Refs: https://github.com/TryGhost/Ghost/issues/8106
=> 🐝 🐜 '+' button double click bug.

lib/asset-delivery/index.js
This requires TryGhost/Ghost#8184
refs TryGhost/Ghost#8140
- now that the admin index page is just html, we don't need handlebars anymore
- this changes the template be called .html to reflect this
=> 🔥 Remove handlebars from serving admin

lib/gh-koenig/addon/components/gh-koenig.js
Previously when selecting text in the editor the screen will jump as it tries to scroll so that the cursor is always on it.
This update means it will no longer happen when selecting the text with either the mouse or in a mobile browser. Unfortunately when selecting text with the keyboard the editor will no longer scroll with the cursor.
Closes: https://github.com/TryGhost/Ghost/issues/8153
=> 🐜  Bulk selecting

app/styles/addons/gh-koenig/gh-koenig.css, app/styles/layouts/editor.css, app/styles/layouts/main.css
Make the editor 100% height in Safari and position toolbars correctly.
Closes: https://github.com/TryGhost/Ghost/issues/8023
=> 🐝 Safari fixes:

lib/gh-koenig/addon/components/koenig-plus-menu.js, lib/gh-koenig/addon/components/koenig-slash-menu.js, lib/gh-koenig/addon/templates/components/koenig-plus-menu.hbs
Closes: https://github.com/TryGhost/Ghost/issues/8106
- Fixes the keyboard selection problems of the '+' menu.
- Makes the active state of the keyboard selection blank until a key is pressed.
- Fixes it so that the '+' menu executes the tool on Enter.
=> 🐝  Card menu fixes

lib/gh-koenig/addon/components/koenig-toolbar.js, lib/gh-koenig/addon/options/default-tools.js
When the toolbar is toggled into link mode the link input field should always focus, however this only happens on the first time which leads to issues with mobiledoc having focus but not the range.
This fix means that the toolbar always focuses.
Closes: https://github.com/TryGhost/Ghost/issues/8195
=> 🐝 Fix editor toolbar link focus issues.

lib/gh-koenig/addon/components/koenig-plus-menu.js, lib/gh-koenig/addon/components/koenig-slash-menu.js
The default state of both the '/' and '+' card menus is a selection of -1, this ensure that the active tool prompt isn't shown until the user presses an arrow key for keyboard selection. However -1 isn't a valid tool id so when pressing enter without selecting a tool the user will cause an error.
This update ensures that the selected tool is the first tool available even if the selection is in fact -1.
Closes: https://github.com/TryGhost/Ghost/issues/8196
=> 🐜  Card Menu Default State Enter Action

Gruntfile.js, package.json, yarn.lock
refs https://github.com/TryGhost/Ghost/issues/8161, requires https://github.com/TryGhost/Ghost/pull/8176
- updates the `ember:watch` grunt task to use `ember serve`, passing in the required `--live-reload-base-url` parameter
- forces live reload port to `4201` for now as there's a [bug on touchbar macs](https://github.com/ember-cli/ember-cli/issues/6513)
- removes the unused `ember-cli-content-security-policy` dependency to remove console log noise from x-domain warnings
With this and the required Ghost PR, when using `grunt dev` the admin screen will refresh any time a file is changed. It will also allow tests to be run simultaneously by visiting http://localhost:4200/tests
=> ✨ `grunt dev` admin livereload

app/components/gh-cm-editor.js, app/components/gh-editor-title.js, app/styles/addons/gh-koenig/gh-koenig.css, lib/gh-koenig/addon/cards/card-hr_dom.js, lib/gh-koenig/addon/cards/card-html_dom.js, lib/gh-koenig/addon/cards/card-image_dom.js, lib/gh-koenig/addon/cards/card-markdown_dom.js, lib/gh-koenig/addon/components/cards/card-html.js, lib/gh-koenig/addon/components/cards/card-markdown.js, lib/gh-koenig/addon/components/gh-koenig.js, lib/gh-koenig/addon/components/koenig-card.js, lib/gh-koenig/addon/lib/card-factory.js, lib/gh-koenig/addon/options/default-tools.js, lib/gh-koenig/addon/templates/components/card-html.hbs, lib/gh-koenig/addon/templates/components/card-markdown.hbs, lib/gh-koenig/addon/templates/components/gh-koenig.hbs, lib/gh-koenig/addon/templates/components/koenig-card.hbs, testem.js
This is a WIP and needs cleanup, tests, integration tests, and also bug/usability updates. But can be merged.
Refs: https://github.com/TryGhost/Ghost/issues/8191
Refs: https://github.com/TryGhost/Ghost/issues/8194
If you navigate to a card with a keyboard or click on the new editor toolbar it "hard selects".
If you click into the body of a card to edit it it "soft selects".
When a card is "hard selected" you can navigate out of the card and to the previous or following blocks within the mobiledoc with the keyboard, you can delete the current card with the backspace or delete button, and you can create a new block following the card with the enter key.
When a card is soft selected it is simply displayed as selected and allows the user to edit content within the card.
Allows a user to …
=> ✨  Selected card

ember-cli-build.js, mirage/fixtures/configurations.js, package.json, yarn.lock
no issue
- `blogUrl` in the mocked config was hardcoded, switching to using the current origin fixed the navigation tests
- we were only pulling jquery drag simulator library in on test builds but we also need it added to `test-support.js` in development builds
- lazy loading is disabled in the test env which previously worked fine as all of the codemirror assets are bundled into the test build, now that we also run tests using the development build we needed to update the config to import codemirror assets into the `test-support.js` file - this ensures that we have normal lazy-loading behaviour when developing locally and that accessing via http://localhost:4200/tests doesn't die horribly due to missing dependencies
=> Fix tests when run via http://localhost:4200/tests

Gruntfile.js
requires https://github.com/TryGhost/Ghost/pull/8261
- use `yarn install` instead of `npm install` in our `grunt init` task (used in Ghost's `grunt init` via subgrunt)
=> 🛠 switch to using yarn in our Grunt tasks

lib/gh-koenig/addon/lib/format-markdown.js
Removes the upload image button in the markdown preview.
Refs: https://github.com/TryGhost/Ghost/issues/8248
=> 🐝  Ghost Image Preview in Markdown.

ember-cli-build.js
closes https://github.com/TryGhost/Ghost/issues/8213
- quick-fix by not adding the `.min` to the production `ghost-dark.css` file, the asset rename breaks the asset rewriting resulting in the lazy loader attempting to load a non-fingerprinted file
=> 🐛 fix night-mode in production build

app/templates/application.hbs
no issue
- pass in the action string so that the mobile menu trigger works
=> 🐛 fix "More" link in mobile nav

app/helpers/gh-path.js, app/templates/-contributors.hbs, app/templates/about.hbs, app/templates/error.hbs, app/templates/settings/apps/amp.hbs, app/templates/settings/apps/index.hbs, app/templates/settings/apps/slack.hbs, app/templates/setup/one.hbs, app/templates/setup/three.hbs, ember-cli-build.js
closes https://github.com/TryGhost/Ghost/issues/8270
- add `.jpeg` to the list of asset extensions that get fingerprinted
- remove the use of the `{{gh-path "asset" ...}}` helper - since switching to hash-location URLs all assets can now be referenced relatively and removing usage of the helper prevents it getting in the way of ember-cli's asset fingerprinting/rewriting mechanism
=> 🐛 fix broken assets

app/components/gh-basic-dropdown.js, app/components/gh-nav-menu.js, app/controllers/application.js, app/mixins/body-event-listener.js, app/services/dropdown.js, app/styles/components/dropdowns.css, app/styles/layouts/main.css, app/templates/components/gh-nav-menu.hbs, package.json, tests/integration/components/gh-basic-dropdown-test.js, yarn.lock
closes https://github.com/TryGhost/Ghost/issues/8269
- swaps the usage of our custom `gh-dropdown` component in the user menu dropdown for the `ember-wormhole` based `ember-basic-dropdown` that is used elsewhere in the app and will fully replace `gh-dropdown` in the future
- adds `gh-basic-dropdown` component that extends from `ember-basic-dropdown` and hooks into our `dropdown` service so that we can programatically close dropdowns from disparate areas of the app
- modifies the `body-event-listener` mixin to pass the click event through to it's consumers
- modifies the `bodyClick` handler in the `dropdown` service to check if the click actually originated from an ember-basic-dropdown element - this body click handler will go away once we've fully switched to `gh-basic-dropdown`
- adds …
=> 🐛 fix sticky dropdown links

app/app.js
no issue
- our custom validation engine makes extensive use of `DS.Errors` which fills the console and especially the test logs with a ton of warnings, this change adds a handler to skip the warnings that we don't care about at the moment
- should be removed when we merge the validations refactor
=> 🚫 hide ds.errors related warnings that fill the test logs

app/components/gh-nav-menu.js
refs TryGhost/Ghost#7688
Instead of using a hardcoded `favicon.ico` URL to request the blog/publication icon, we read the settings which get updated as soon as a icon is uploaded.
=> 🐝  Refresh publication icon after upload

app/styles/layouts/main.css
refs TryGhost/Ghost#7688
Instead of having a dark background (which was ok, when we were **only** using the default Ghost icon), we're changing it to be transparent, so custom icons look like this:
instead of
=> 🎨  Make blog icon backround transparent

app/components/gh-editor-title.js, tests/acceptance/editor-test.js
When a title is empty it has no textnode to get a length of so we automatically put the horizontal offset of the cursor to 0.
Closes: https://github.com/TryGhost/Ghost/issues/8293
=> 🐜  Key up to empty title.

app/templates/settings/general.hbs
no issue
Wraps the existing `{{one-way-checkbox}}` in general-setting in a `<label>` tag to make the checkbox styles work properly.
=> 🎨  Checkbox styles in settings

app/components/gh-editor-title.js, app/styles/addons/gh-koenig/koenig-toolbar.css, app/styles/addons/ghost-editor/cardmenu.css, app/templates/editor/edit.hbs, lib/gh-koenig/addon/components/gh-koenig.js, lib/gh-koenig/addon/components/koenig-plus-menu.js, lib/gh-koenig/addon/components/koenig-slash-menu.js, lib/gh-koenig/addon/components/koenig-toolbar.js, lib/gh-koenig/addon/options/default-commands.js, lib/gh-koenig/addon/templates/components/gh-koenig.hbs
Refs: https://github.com/TryGhost/Ghost/issues/8194
Previously if the title was selected and the first element was a card then the first element would be skipped on key down.
Previously if the first element was a card and the card was selected it wouldn't navigate into the title upon pressing the up key.
This update:
- Allows you to navigate to the title and body if the first element in the document is a card.
- Adds paragraphs underneath inline markdown cards if they are the last item in the document.
- Better optimises UI for mobile devices.
=> 🐜  Navigating from the title to a card.

app/styles/patterns/buttons.css
closes https://github.com/TryGhost/Ghost/issues/8029
- quick fix - works for the setup button but won't work for buttons that include spinners because the `display: flex` breaks the `text-overflow: ellipsis` style, this should be fine as I'm not aware of any other buttons where the text is user-defined
=> 🐛 fix long text overflowing signin button on setup screen

app/components/gh-nav-menu.js
refs TryGhost/Ghost#7688
Fixes a bug in subdirectory setup where the blog icon URL would be concatenated with a double subdirectory in the URL.
Uses `RegExp` to strip it from `settings.icon` and concat it without trailing slash.
=> 🐛  Use correct blog icon URL with subdirectory

tests/acceptance/editor-test.js
no issue
- fixes tests where timezone difference we were using to enter dates was so large it wrapped days so the hours input looked like it was in the past rather than the future
=> ✅ fix timezone errors in editor tests

lib/gh-koenig/addon/components/gh-koenig.js, lib/gh-koenig/addon/templates/components/gh-koenig.hbs
Closes: https://github.com/TryGhost/Ghost/issues/8315
Previously you couldn't upload images in markdown cards in firefox. Moving the drop action off of the component and onto the root editor as well as having an dragover handler which does nothing fixed the issue 🤷
=> 🐜  🎊  Fix firefox drag and drop support in markdown cards.

app/styles/addons/gh-koenig/gh-koenig.css, lib/gh-koenig/addon/templates/components/koenig-card.hbs
closes TryGhost/Ghost#8340
Use `{{inline-svg}}` helper instead of icon font
=> 🗑  Get the trash icon back in card

app/controllers/signup.js, app/routes/signup.js, app/templates/signup.hbs
refs https://github.com/TryGhost/Ghost/issues/7865
- moves authentication actions from `signup` route to controller
- refactors authentication and signup logic into EC tasks
- replaces use of `gh-spin-button` with `gh-task-button` in signup template
=> 💄 refactor signup to use ember-concurrency

app/mixins/editor-base-controller.js, tests/acceptance/editor-test.js
refs https://github.com/TryGhost/Ghost/issues/8331, https://github.com/TryGhost/Ghost/pull/8328
- prevents auto-save save if nothing has changed, this avoides unnecessary collision errors when reading a post that another user is editing
=> don't auto-save posts if there are no changes

app/components/gh-post-settings-menu.js, app/controllers/editor/edit.js, app/mixins/editor-base-controller.js, app/templates/components/gh-post-settings-menu.hbs, app/templates/editor/edit.hbs
closes https://github.com/TryGhost/Ghost/issues/8332
- moves `toggleDeletePostModal` action from the `edit` controller to the `editor-base-controller` mixin
- adds delete button to the bottom of the PSM unless it's a new post
- adds `deletePost` attribute to `gh-post-settings-menu` to allow a delete post action to be passed in
_Note:_ this PR adds the necessary functionality but the styling for settings menu delete buttons is currently broken (https://github.com/TryGhost/Ghost/issues/8345) and will be fixed in a separate PR
=> add "delete post" button to the PSM

app/styles/components/settings-menu.css, app/templates/components/gh-post-settings-menu.hbs, app/templates/components/gh-tag-settings-form.hbs, tests/acceptance/settings/tags-test.js, tests/integration/components/gh-tag-settings-form-test.js
closes TryGhost/Ghost#8345
- renames `.tag-delete-button` to `.settings-menu-delete-button` to match it's more generic purpose
- match styles as close to 0.11.x as possible, it was necessary to add both stroke and fill to the trashcan SVG for it not to be washed out
0.11.x style for reference:
=> 🎨 fix settings menu delete button styles 

app/components/gh-editor.js, app/mixins/editor-base-controller.js, app/styles/layouts/editor.css, app/templates/components/gh-editor.hbs, app/templates/editor/edit.hbs
closes https://github.com/TryGhost/Ghost/issues/8271
- adds `gh-editor` wrapper component that checks the editor position and will apply a `.gh-editor-header-small` class if the editor content will overlap the view actions
- adds `.gh-editor-header-small` class that minifies the header and applies a solid background so that there's no conflict between editor content and header elements
- modifies `.gh-editor-header` z-index so that there's no hidden non-selectable area at the top of the screen
=> 🎨 responsive editor header

tests/acceptance/editor-test.js
no issue
- `async/await` cuts down on some boilerplate `andThen(() => { ... })` code and makes it more explicit which methods are async and will wait for run-loop/promise behaviour to finish before continuing
Starting with the single acceptance test file to demonstrate the concept and get some buy-in for a decision to make this the default going forwards.
=> 💄 convert editor acceptance tests to async/await

app/components/gh-task-button.js, app/models/user.js, app/templates/team/user.hbs
closes https://github.com/TryGhost/Ghost/issues/8358
- the change password task was not returning a truthy value on success so you always saw the "X Retry" state
- adds option to pass `idleClass` and `runningClass` to `gh-task-button` - this is so that colour classes can be set in the "base" state without overriding the success/failure colors (some colours would have preference based on the order the colours are defined in the CSS file, eg. setting `gh-btn-red` as a base CSS class would override the `gh-btn-green` that is added after a successful save)
=> 🐛 fix password change button not showing success state

app/components/gh-nav-menu.js, app/controllers/application.js, app/controllers/settings/labs.js, app/services/settings.js, app/templates/application.hbs, app/templates/components/gh-nav-menu.hbs
closes https://github.com/TryGhost/Ghost/issues/8307
- unloading the store and refreshing the `session.user` attribute after an import was triggering a rendering edge case where the style was re-computed and a re-render was attempted after the sidebar has been destroyed
- rather than binding a style attribute directly to a CP in `gh-nav-menu` we pass the menu icon in (using `settings.settledIcon` - see below) and manually set the style attribute via the `didReceiveAttrs` hook so that outside changes don't trigger re-computations when we don't expect them and so we can still react to icons being uploaded or removed
- our usage of `settings.icon` is a bit of an odd situation because it's a link to an external resource that will only resolve correctly after a successful save - if we change …
=> 🐛 fix broken sidebar after successful import

app/styles/patterns/forms.css
closes TryGhost/Ghost#8335
Use `display: none` instead of positioning it out of the viewport.
=> 🎨  Don't scroll to top after toggle checkbox

app/styles/layouts/editor.css, app/templates/components/gh-editor-title.hbs
Closes: https://github.com/TryGhost/Ghost/issues/8322
Previously in firefox the `no-content` psuedo element was placed below the actual on first load (but not subsequent reloads), this update positions it in the correct place in both scenarios.
=> Places no-content placeholder in the correct position in firefox.

app/styles/layouts/editor.css
closes https://github.com/TryGhost/Ghost/issues/8366
- ensure that header actions are layered above the editor so that they are still clickable
- editor content is still selectable in the header area
=> 🐛 fix non-clickable editor header actions with wide screens

app/components/gh-post-settings-menu.js, app/templates/components/gh-post-settings-menu.hbs, tests/acceptance/editor-test.js
closes TryGhost/Ghost#8359
- if the date/time picker is in an error state when the PSM is closed, reset it to the currently saved time
- resolves the problem with the flash of an error as the publish menu is closed as it's no longer possible to be in a hidden error state
=> 🐛 clear date error when closing the PSM 

app/styles/patterns/global.css
closes TryGhost/Ghost#8136
The "Fira Sans" system font looks - even on a retina display - not very readable for users.
=> 🖌  Remove "Fira Sans" system font

app/components/gh-editor-title.js, tests/acceptance/editor-test.js, tests/helpers/editor-helpers.js
Closes: https://github.com/TryGhost/Ghost/issues/8353
Currently when you paste HTML into the title (or modify the title in some other way that inserts HTML) the title keeps the styling which is not saved.
This update detects if HTML is included into the title and strips it if it exists.
=> 🐝 Strip HTML from title.

tests/acceptance/authentication-test.js, tests/acceptance/content-test.js, tests/acceptance/editor-test.js, tests/acceptance/ghost-desktop-test.js, tests/acceptance/password-reset-test.js, tests/acceptance/settings/apps-test.js, tests/acceptance/settings/code-injection-test.js, tests/acceptance/settings/design-test.js, tests/acceptance/settings/general-test.js, tests/acceptance/settings/labs-test.js, tests/acceptance/settings/slack-test.js, tests/acceptance/settings/tags-test.js, tests/acceptance/setup-test.js, tests/acceptance/signin-test.js, tests/acceptance/signup-test.js, tests/acceptance/subscribers-test.js, tests/acceptance/team-test.js, tests/acceptance/version-mismatch-test.js
no issue
- replaces `andThen(() => {}` blocks with `async/await` in acceptance tests
https://www.youtube.com/watch?v=oqwzuiSy9y0
=> 💄 refactor acceptance tests to use async/await

lib/gh-koenig/addon/components/cards/card-markdown.js, lib/gh-koenig/addon/components/gh-koenig.js, lib/gh-koenig/addon/components/koenig-card.js, lib/gh-koenig/addon/components/koenig-plus-menu.js
Closes: https://github.com/TryGhost/Ghost/issues/8312
1. Currently when adding cards via the `+` menu the card is not selected or placed in edit mode. This update means that cards created with the `+` menu behave the way as with the `/` menu.
2. If a card is deleted and the deletion places the cursor in an empty section of the document the editor places the `+` menu icon before the card is deleted, this means that the `+` button appears below the actual blank paragraph. Now the card placement occurs after the card has been removed from the editor.
3. Currently when a markdown card is created it does not launch in edit mode, this has now been rectified.
=> Card creation and deletion bugs.

lib/gh-koenig/addon/components/gh-koenig.js, lib/gh-koenig/addon/lib/utils.js
No Issue.
When calculating if the editor should scroll to keep the cursor on screen upon selection change the editor would appear to scroll to random locations.
The issue stemmed from the fact that the `getPositionFromRange` method took into account the scroll offset when figuring out the pixel position of a range. So, if the editor was vertically scrolled the `scrollTop` was added to the cursor position which the editor would assume meant that the cursor was offscreen when it wasn't.
This fix creates a new method `getPositionOnScreenFromRange` which finds the position of an element on screen and ignores the scroll offset.
=> 📜 🐭 Fixes the scroll problem

lib/gh-koenig/addon/components/gh-koenig.js
If a card that is being edited is hard-selected then make sure that it is in fact soft-selected.
closes https://github.com/TryGhost/Ghost/issues/8385
=> Ensure that editing cards are not hard-selected

app/components/gh-editor.js, app/components/gh-markdown-editor.js, app/styles/layouts/editor.css, app/templates/components/gh-editor.hbs, app/templates/components/gh-markdown-editor.hbs, app/templates/editor/edit.hbs, bower.json, ember-cli-build.js, package.json, yarn.lock
no issue
- replace SimpleMDE's split pane handling with our own so that we have more control over the element positioning, can simultaneously toggle our custom fullscreen code, and so that the preview pane can be scrolled separately as per our old editor
=> Fix split screen editor

app/components/gh-markdown-editor.js, app/styles/layouts/editor.css
no issue
- fix visible scroll bars being rendered to the right and bottom of the internal editor area in certain browser/OS configurations
- disable the preview button when in split-screen mode as it's not any use there
- exit SimpleMDE preview mode if it's active when entering split-screen mode
=> 🐛 fix visible scroll bars and disable preview in split-screen

app/components/gh-editor.js, app/components/gh-markdown-editor.js, app/components/gh-simplemde.js, app/templates/components/gh-editor.hbs, app/templates/components/gh-markdown-editor.hbs, app/templates/editor/edit.hbs
no issue
- adds a hidden file input to the `gh-markdown-editor` component
- when the editor image toolbar button is clicked, capture the current selection (it gets during the file upload), trigger the file dialog then when files are selected initiate the same upload+insert process as drag/drop image uploads
=> ✨ upload images via editor toolbar

app/components/gh-uploader.js
no issue
- babel's transpilation of the `for...of` loops was resulting in an error in MS Edge, dropping back to an old `for` loop fixed it
=> 🐛 fix editor image uploads in Edge

app/components/gh-editor.js, app/components/gh-markdown-editor.js, app/styles/layouts/editor.css, app/templates/components/gh-editor.hbs, app/templates/editor/edit.hbs
no issue
- when entering preview mode (not split-screen preview) the toolbar buttons are now disabled. This is usually built in to SimpleMDE but that wasn't working because we've moved the location of the toolbar in the DOM
- hides the markdown editor when entering preview mode to prevent the markdown code appearing at the bottom of the preview when the markdown length is longer than the preview length
=> 🎨 disable buttons in preview, fix preview overlap

app/validators/post.js, app/validators/tag-settings.js, tests/acceptance/editor-test.js, tests/unit/validators/tag-settings-test.js
closes TryGhost/Ghost#8143
- uses new soft limits in validation:
- post title to 255
- meta title (post and tag) to 300
- meta description (post and tag) to 500
- updates test
=> 🗜  Database soft limits

app/controllers/settings/general.js, app/controllers/team/user.js, tests/acceptance/settings/general-test.js, tests/acceptance/team-test.js
closes https://github.com/TryGhost/Ghost/issues/8296
- permit Facebook usernames with less than 5 chars
- brands are allowed to have Page names with less than 5 chars (ex: facebook.com/nike)
- current/former employees are allowed to have usernames with less than 5 chars (ex: facebook.com/zuck)
=> Permit Facebook usernames with less than 5 chars. 

app/templates/team/index.hbs
closes TryGhost/Ghost#8409
- only show current user on team screen when logged in as author
- don't show the suspended users list to authors
=> Fix team screen when logged in as an author

app/controllers/settings/general.js, app/controllers/team/user.js, tests/acceptance/settings/general-test.js, tests/acceptance/team-test.js
closes https://github.com/TryGhost/Ghost/issues/8296
- permit Facebook usernames with less than 5 chars
- brands are allowed to have Page names with less than 5 chars (ex: facebook.com/nike)
- current/former employees are allowed to have usernames with less than 5 chars (ex: facebook.com/zuck)
=> 🐛 permit Facebook usernames with less than 5 chars

app/styles/layouts/editor.css
closes https://github.com/TryGhost/Ghost/issues/8459
- use `vh` instead of `%` for editor height
=> 🐛 fix broken editor layout in Safari

app/components/gh-markdown-editor.js
closes https://github.com/TryGhost/Ghost/issues/8462
- grab image filename and remove extension before inserting it as `alt` text when uploading images
=> ✨ use image name as alt text when inserting images

app/components/gh-input.js, app/components/gh-textarea.js, app/components/gh-trim-focus-input.js, app/mixins/text-input.js, app/templates/editor/edit.hbs, package.json
closes https://github.com/TryGhost/Ghost/issues/8463
- move generic text input handling into `text-input` mixin so it applies to text inputs and textareas
- adds `autoExpand` property to `gh-textarea` that accepts a selector to watch for resize changes, if the property is set then auto-expanding behaviour is triggered any time the textarea value is changed or when the selector element is resized (this prevents change in textarea width after toggling nav/split screen mode causing textarea content to become hidden or the textarea to be taller than it's contents)
- adds `ember-element-resize-detector` addon to allow watching of element resizes rather than window resizes (this was already included as a sub-dependency via `ember-light-table`->`ember-scrollable`->`ember-element-resize-detector`) …
=> ✨ auto-expanding editor title input

app/components/gh-markdown-editor.js, app/styles/layouts/editor.css, yarn.lock
closes https://github.com/TryGhost/Ghost/issues/8461
- adds toggle spellcheck button to the `gh-markdown-editor` toolbar
- adds custom styles to fake a spellcheck icon
- updates `simplemde` fork
- adds `spellcheck` to the list of toolbar buttons that don't have their `active` class removed based on cursor position
- removes bundled `marked` dependency that we no longer use
TODO:
=> ✨ add spellcheck toggle

app/controllers/settings/apps/amp.js, app/controllers/settings/apps/slack.js, app/controllers/settings/code-injection.js, app/controllers/settings/design.js, app/controllers/settings/general.js, app/routes/settings/apps/amp.js, app/routes/settings/apps/slack.js, app/templates/settings/apps/amp.hbs, app/templates/settings/apps/slack.hbs, app/templates/settings/design.hbs, app/templates/team/user.hbs, tests/acceptance/settings/amp-test.js, tests/acceptance/settings/design-test.js, tests/acceptance/settings/general-test.js, tests/acceptance/settings/slack-test.js, tests/acceptance/team-test.js
closes TryGhost/Ghost#8443
Fixes a bug where the keyboard shortcut `cmd+s` would cause a `Maximum call stack size` error and not save.
Wherever there is a `save` button, the keyboard shortcut to save works now.
=> 🐛  Make `cmd+s` work for all save-buttons

app/styles/components/publishmenu.css, app/styles/layouts/editor.css, app/templates/editor/edit.hbs
=> Updated editor styles 🤓

app/controllers/settings/labs.js
closes https://github.com/TryGhost/Ghost/issues/8307
- Ember 2.13 has a behaviour change to `store.unloadAll` where the records aren't removed until later in the runloop resulting in errors if the store is used to find records before it's completed. See https://github.com/emberjs/data/issues/4963
=> 🐛 fix disappearing nav after import

app/components/gh-uploader.js, app/controllers/settings/general.js, app/styles/layouts/settings.css, app/templates/components/gh-uploader.hbs, app/templates/settings/general.hbs, mirage/config.js, mirage/config/uploads.js, tests/acceptance/settings/general-test.js, tests/helpers/file-upload.js, tests/integration/components/gh-uploader-test.js
refs https://github.com/TryGhost/Ghost/issues/8455
- ensure `uploadUrls` and `errors` are cleared in `gh-uploader` when new uploads are started
- yield `isUploading` from `gh-uploader` component
- use `gh-uploader` to implement modal-less image uploads in settings/general
TODO:
=> ✨ streamline image uploads in settings/general

package.json, yarn.lock
refs #706
- bumping to `autoprefixer@7.0.1` in #673 caused `cssnano` to fail on production builds
- upgrading to latest autoprefixer didn't result in any wins
- reverting to `autoprefixer@6.7.7` for now, we may need other dependencies to bump their `postcss` support before it can be upgraded
=> ⬇️ revert to autoprefixer@6.7.7

app/components/gh-publishmenu-scheduled.js, app/components/gh-publishmenu.js, app/templates/components/gh-publishmenu.hbs
closes TryGhost/Ghost#8360
When changing the publish time of an already scheduled post in the publish menu and leaving the menu with clicking outside of the menu, the time wouldn't reset properly and be shown in the PSM. With the usage of an `isClosing` property which is passed to the underlying `gh-publishmenu-scheduling` component, we prevent the changed time from being saved and reset it properly instead.
=> 🐛  Reset publish date in PSM when leaving menu

app/styles/patterns/buttons.css, app/transitions.js
no issue
- removes transition on `all` properties in favour of an explicit list, fixes the buttons flickering after the modal appears and the outline/text being visible when the modal disappears
- simplifies the liquid-fire transition so that elements being removed at slightly different times doesn't cause flickering when the modal is removed
=> 🐛 fix flickering buttons during modal transitions

app/controllers/settings/labs.js
no issue
- the synchronous settings service keeps an internal reference to the settings model, when everything in the store is unloaded during an import that reference breaks and will throw errors when accessing areas of the app that read values from it. This change adds an explicit reload of the settings model during import so that later navigation doesn't break.
=> 🐛 fix errors when navigating after successful import

app/styles/layouts/settings.css
closes https://github.com/TryGhost/Ghost/issues/8487
- removes extraneous padding
- removes double-width border
- matches focused border colour to other inputs
=> 🎨 fix code injection input styles

app/components/gh-posts-list-item.js, app/models/post.js, app/routes/editor/edit.js, app/routes/posts.js, mirage/factories/post.js
refs https://github.com/TryGhost/Ghost/issues/8275
- ask Ghost for `mobiledoc` and `plaintext`
- Ghost returns `html` by default
- use plaintext for {{subText}} for posts overview
This probably needs a change in the tests, will discuss with @kevinansfield before i start.
=> 🎨  use `formats` query param

app/components/gh-post-settings-menu.js, app/utils/format-markdown.js, tests/unit/components/gh-post-settings-menu-test.js
refs #718, https://github.com/TryGhost/Ghost/pull/8305
- meta description preview in the PSM was relying on the `html` field which is no longer queried - see #718 and https://github.com/TryGhost/Ghost/pull/8305
- restores live preview that was in LTS but removed whilst implementing mobiledoc because we had no quick way of rendering mobiledoc->text
- adds a boolean argument to the `formatMarkdown` util that can disable the replacement of `<script>` and `<iframe>` tags so that the inserted text isn't rendered when converting HTML to text
=> 🐛 fix missing meta description preview

app/components/gh-markdown-editor.js
closes https://github.com/TryGhost/Ghost/issues/8480
- removes fullscreen button from toolbar but keeps the "fullscreen" routines so that styling and other behaviour doesn't need to be updated
- side-by-side toggle now toggles fullscreen on/off (previously only toggled fullscreen on)
=> 🎨 remove Fullscreen button from editor toolbar

app/components/gh-cm-editor.js, app/styles/patterns/global.css
closes https://github.com/TryGhost/Ghost/issues/8488
- don't lazy-load the CodeMirror styles in `gh-cm-editor` as they are already loaded and overridden
=> 🐛 fix lazy-loading of CodeMirror interfering with editor

app/styles/layouts/editor.css
closes https://github.com/TryGhost/Ghost/issues/8516
- placeholders are pseudo elements so need to use `::` rather than `:` in their CSS selectors
=> 🎨 fix title placeholder styles

app/mixins/editor-base-controller.js, app/templates/editor/edit.hbs
refs https://github.com/TryGhost/Ghost/issues/8482
- removes "save on first change" behaviour of the post body
- always trigger a background save when title loses focus if the post is a draft
- renames `updateTitle` action to `saveTitle` action to better describe it's purpose and to avoid confusion with the `updateTitle` task
=> 🐛 reduce likelihood of "untitled" slugs

app/components/gh-cm-editor.js, app/styles/layouts/settings.css, ember-cli-build.js, tests/integration/components/gh-cm-editor-test.js
closes https://github.com/TryGhost/Ghost/issues/8504
- allow `.settings-code-editor` to inherit from `.gh-input` - fixes border colours
- change `gh-cm-editor`'s "focused" class from `.focused` to `.focus` so it can inherit `.gh-input` styles
- add lazy loading of CM styles back in `gh-cm-editor` but prevent `lib/codemirror.css` from being compiled into the codemirror styles so that we get the theme colours without causing conflicts with the main editor
=> 🎨 fully fix Code Injection styles

app/controllers/settings/general.js, app/styles/components/modals.css, app/styles/components/notifications.css, app/styles/components/power-select.css, app/styles/components/publishmenu.css, app/styles/components/settings-menu.css, app/styles/components/uploader.css, app/styles/layouts/auth.css, app/styles/layouts/editor.css, app/styles/layouts/main.css, app/styles/layouts/settings.css, app/styles/layouts/subscribers.css, app/styles/layouts/user.css, app/styles/patterns/forms.css, app/styles/patterns/navlist.css
closes https://github.com/TryGhost/Ghost/issues/8384
- fixes image uploads on settings/general by reverting to jQuery for triggering the file dialog because IE11 doesn't support `MouseEvent` events or have the `.closest` method on native DOM elements
- gives all SVG elements an explicit `width` and `height` - if one property is set to `auto` or not specified IE11 will treat it as 100% of the container
- fixes horizontal scroll + scrollbar on the main app viewport
=> 🐛 fix IE11 bugs and styles

app/templates/team/user.hbs
closes TryGhost/Ghost#8521
The image uploader modals in `user.hbs` used the old image properties instead of `coverImage` and `profileImage`.
=> 🐛  Use new user image properties for image upload

app/components/gh-post-settings-menu.js, app/components/gh-tour-item.js, app/models/user.js, app/routes/application.js, app/services/session.js, app/services/tour.js, app/styles/app-dark.css, app/styles/app.css, app/styles/components/popovers.css, app/styles/components/tour.css, app/styles/patterns/throbber.css, app/templates/components/gh-nav-menu.hbs, app/templates/components/gh-post-settings-menu.hbs, app/templates/components/gh-tour-item.hbs, app/templates/editor/edit.hbs, app/templates/settings/design.hbs, app/transitions.js, package.json, tests/unit/models/invite-test.js, tests/unit/serializers/user-test.js, yarn.lock
refs TryGhost/Ghost#5168
- adds a `tour` service that handles syncing and management of tour throbbers & content
- adds a `gh-tour-item` component that handles the display of a throbber and it's associated popover when clicked
- populates viewed tour items on app boot/signin
TODO:
- for the current tour items an array of IDs is sufficient, if we need deeper customisation for recording tour item state later on then the client should be able to modify the `user.tour` JSON itself
- partially fixed, using semi-hardcoded values for now, we can look at using variable replacement later on if required
=> ✨ welcome tour

app/controllers/team/user.js
closes https://github.com/TryGhost/Ghost/issues/8547
- `window.history.state` is no longer a thing (not sure if it's a recent browser change or because we switched to hash-urls) so the URL change logic after a successful user save needs to use `window.location.hash` instead
=> 🐛 fix saving users when slug has been changed

app/styles/layouts/users.css, app/templates/team/user.hbs
closes #8546
Creates new `suspended` class as a copy of `administrator` for better naming and add `15px` of `margin-left` to it.
=> 💄  Give suspended user badge a little room

app/styles/patterns/buttons.css, app/templates/signin.hbs
closes TryGhost/Ghost#8550
Use no success- and failure-classes for forgot link `gh-task-button`.
Fixes loading spinner fill and positioning.
=> 🐛  Fix styles for password forgot link

app/controllers/setup/three.js, app/templates/components/gh-nav-menu.hbs, app/templates/components/modals/markdown-help.hbs, app/templates/settings/labs.hbs, tests/unit/components/gh-upgrade-notification-test.js
no issue
- support.ghost.org has gone away, we now have self-host/dev documentation on https://docs.ghost.org and user documentation at https://help.ghost.org
=> 📖 update all support.ghost.org links to docs/help.ghost.org

app/controllers/post-settings-menu.js, app/mixins/editor-base-controller.js, app/routes/editor/edit.js, app/routes/editor/new.js
refs https://github.com/TryGhost/Ghost/issues/8551
- renames editor-base-controller.generateSlug to generateSlugFromTitle
- moves `updateSlug` logic from PSM to editor base controller
- moves editor base controller save logic into a `save` task
- adds `updateSlug` and `save` into a `saveTasks` task group so that calls are queued rather than running concurrently
- sets the editor controller on the PSM when accessing the new/edit routes - we use a base controller mixin so the slug/save logic is duplicated on new/edit controllers meaning we need to add a reference manually rather than relying on dependency injection
- remove titleObserver checks for non-existent titleObserver
=> 🐛 fix Cmd-S save with cursor in slug field

app/controllers/setup/three.js
no issue
- URL on docs.ghost.org has been shortened for more readable display in errors
=> 📖 shorten mail config docs links

app/components/gh-publishmenu.js, app/templates/components/gh-publishmenu.hbs, tests/acceptance/editor-test.js
The save button text now represents the state of change for a post and includes a more suitable success message.
closes https://github.com/TryGhost/Ghost/issues/8536, closes https://github.com/TryGhost/Ghost/issues/8500
- Post save button will now display publish/un-publish/schedule/un-schedule/re-schedule/update
- On successful save button will display published/un-published/scheduled/un-scheduled/re-scheduled/updated
=> Update post save button texts

app/mixins/editor-base-controller.js, app/routes/editor/edit.js, app/routes/editor/new.js, app/templates/editor/edit.hbs
closes https://github.com/TryGhost/Ghost/issues/8525
- always give focus to the editor content area by default when loading the editor
- change the editor placeholder text
=> always give editor text area focus by default

app/components/gh-markdown-editor.js
closes https://github.com/TryGhost/Ghost/issues/8566
- sets codemirror into "markdown" mode during initialisation
=> set spellchecker to "off" by default

app/templates/settings/general.hbs
closes TryGhost/Ghost#8544
When clicking on an already uploaded icon, logo or cover in Settings -> General we trigger now the file upload to be able to replace it.
Todo:
=> ⬆️  Trigger image upload when clicking on image

app/styles/patterns/forms.css
closes TryGhost/Ghost#8552
Reduce the `font-size` per `0.5rem` so it'll fit within the `700px` `max-width` of the parent container even with three numbers in word count.
---
Before:
---
After:
=> 💅🏼 Reduce meta description word count font-size

app/controllers/settings/labs.js
closes https://github.com/TryGhost/Ghost/issues/8508
- manually set `config.blogTitle` when reloading settings after a successful import
=> 🐛 fix title not updating after import

app/components/gh-markdown-editor.js
No Issue
- disables simpleMDE image shortcut when using Cmd+alt+i
=> Disable simpleMDE image shortcut

app/components/modals/theme-warnings.js, app/controllers/settings/design.js, app/templates/components/modals/theme-warnings.hbs, app/templates/components/modals/upload-theme.hbs, app/templates/settings/design.hbs, tests/acceptance/settings/design-test.js
refs TryGhost/Ghost#8530
This PR takes care that the modals for theme activation gets the same treatment as theme upload modal:
- differentiate between normal and fatal errors
- List headings for each error type (fatal, normal or warning)
- update test
=> 💅🏼  Improve theme activation error messages

app/models/post.js
refs TryGhost/Ghost#8603
refs https://github.com/TryGhost/Ghost-Admin/pull/753
With https://github.com/TryGhost/Ghost-Admin/commit/68ffa29e31124c327372c74f091c6cff1feb3a15 we introduced a bug, that caused the Ghost Admin to crash when scheduling a blog post. Adding a check in the conditional prevents it from crashing and fixes the functionality.
=> 🐛  Add conditional to fix post scheduling

app/styles/components/power-select.css
closes TryGhost/Ghost#8630
Add `width: 100%` to `.ember-power-select-search input` class so the input field is full width.
=> 💅🏼  Set width of search input to almost 100%

app/templates/about.hbs
closes TryGhost/Ghost#8623
Uses the same classes as the other pages for more consistency and sexiness. Also updated the links to slack and contributers to be correct.
=> 💄  Consistent layout for about page

app/components/gh-markdown-editor.js
closes https://github.com/TryGhost/Ghost/issues/8637
- add a default object to `_openImageFileDialog` args so that destructuring with default params works when not passed a value
=> Fix for broken image upload button

ember-cli-build.js
closes TryGhost/Ghost#8610
There's an issue in CSSnano, which we're using in production mode to minify our CSS that caused animation frames to not work properly anymore.
See: https://github.com/ben-eb/gulp-cssnano/issues/33#issuecomment-210518957
=> 🐛  Add CSSNano fix to minify keyframes properly

app/components/modals/re-authenticate.js, app/styles/components/modals.css
closes https://github.com/TryGhost/Ghost/issues/8656
- prevents button stretching from flexbox and adds margin between input and button
- use the `context` attribute returned from the server instead of the `message` so the error is now `Your password is incorrect.` instead of `You are not authorised to make this request.`
- return truthy/falsy values from the auth tasks so that the save-state button shows the correct state
=> 🐛 fix display/message bugs in re-auth modal

app/styles/app-dark.css, app/styles/layouts/editor.css
no issue
- background color of the editor header at smaller screen sizes had been removed resulting in the editor content showing through when scrolling, this adds the explicit bg color back for both normal and dark mode
=> 🎨 fix editor header not covering scrolled content

app/components/gh-tag.js, app/components/power-select-vertical-collection-options.js, app/controllers/posts.js, app/controllers/settings/tags.js, app/routes/posts.js, app/routes/settings/tags.js, app/routes/settings/tags/tag.js, app/styles/layouts/content.css, app/templates/components/gh-tag.hbs, app/templates/components/power-select-vertical-collection-options.hbs, app/templates/posts.hbs, app/templates/settings/tags.hbs, package.json, tests/acceptance/settings/tags-test.js, yarn.lock
closes https://github.com/TryGhost/Ghost/issues/8540
- use `{{vertical-collection}}` in the tags dropdown filter list, opening the dropdown is now virtually instant as it's not attempting to immediately render components for every tag in the list
- remove pagination/infinite scroll from tags screen
- load all tags when accessing the tags screen
- will pause to show spinner if no tags have previously been loaded
- if tags exist in the ember data store, show the list immediately and load/update list in the background
- use `{{vertical-collection}}` to render enough tags to fill the scrollable area with a small buffer and use occlusion and element re-use to swap tags in whilst scrolling (suuuuper fast no matter number of tags loaded)
- scroll tags into view when they are selected (keyboard …
=> 🚀 supercharge tags performance

app/controllers/posts.js, app/routes/posts.js, app/templates/posts.hbs
closes https://github.com/TryGhost/Ghost/issues/8662
- removes `k`, `j`, `up`, `down` shortcuts for changing the active post (these were already mostly unusable in 1.0) and the associated `enter` and `ctrl/cmd+backspace` commands for opening and triggering the delete modal respectively
- removes the `c` shortcut for opening the new post screen
=> 🔥 remove content screen keyboard shortcuts

app/routes/application.js, mirage/config/authentication.js, tests/acceptance/authentication-test.js, tests/acceptance/settings/tags-test.js, tests/acceptance/signin-test.js
refs https://github.com/TryGhost/Ghost/issues/8616
- only refresh tokens on boot if we last refreshed more than 24hrs ago - this should prevent rapidly changing access/refresh tokens when opening new admin tabs or refreshing whilst other tabs are open
- fix token refresh test which was testing it's own behaviour instead of the applications 🙈
This may not be the full solution to the session issues but it closes one potential culprit and should at least reduce token churn which can only help track down the real cause.
=> 🐛 prevent session sync issues with multiple tabs/refreshes

app/mixins/editor-base-controller.js, mirage/config/posts.js, tests/acceptance/editor-test.js
refs TryGhost/Ghost#8525
- fix `saveTitle` action
- don't abort title save when we have an empty title
- force a "dirty" state so that the save actually happens
- add acceptance test for title blur behaviour
- extract multiple instances `"(Untitled)"` into a const
=> 🐛 fix autosave+transition on title blur with empty title

app/styles/components/power-select.css, app/styles/patterns/forms.css
closes https://github.com/TryGhost/Ghost/issues/8665
- updates width/height for non-square icons to match the desired dimensions (width+height have to be specified for IE11)
Changes introduced in #724 failed to take into account a few of our icons are not square (notably the `arrow-*-small.svg` icons) resulting in some icons appearing too small.
=> 🎨 fix non-square icon sizes

app/mixins/text-input.js
closes https://github.com/TryGhost/Ghost/issues/8588, closes https://github.com/TryGhost/Ghost/issues/8639
- check that we have an action assigned to keyEvent codes before attempting to prevent the default behaviour
- no tests because browsers don't trigger form submissions in response to JS key events as a security measure
=> 🐛 fix enter key not working in text inputs/areas

app/components/gh-post-settings-menu.js, app/components/gh-tour-item.js, app/services/tour.js, app/templates/components/gh-post-settings-menu.hbs
closes https://github.com/TryGhost/Ghost/issues/8611
- fix positioning of "static page" throbber
- fix PSM throbbers re-appearing after PSM close/open (need to use `pushObject` instead of `push` so that it's KVO compliant and the `_activeThrobbers` CP is updated)
- fix order of `willDestroyElement` so that we don't attempt to use `get` after the component is destroyed
- fix issue in Chrome that was preventing the Meta Data link from sliding the PSM panels
TODO:
=> 🐛 fix PSM throbber bugs

app/components/gh-post-settings-menu.js, app/components/gh-textarea.js, app/controllers/editor/new.js, app/mixins/editor-base-controller.js, app/mixins/editor-base-route.js, app/routes/editor/edit.js, app/routes/editor/new.js, app/templates/editor/edit.hbs
closes TryGhost/Ghost#8525
- always give focus to the editor content area by default when loading the editor
- allow content autosave to work for new posts (it was previously turned off for new posts)
- move transition-on-save behaviour from editor/new controller into the controller mixin's save routine
- cancel background autosave when "are you sure you want to leave?" modal is shown as it can cause the "leave" option to fail because it attempts to delete the post record that can be in flight (plus if we're saving anyway it doesn't make much sense to ask the user  🙈) - this is quite an edge-case as it will only happen if the user makes a content change to a draft post then tries to leave the screen within 3 seconds
- change the editor placeholder text
=> Focus editor content area by default (attempt 2 😁) 

app/components/gh-editor-post-status.js, app/templates/components/gh-editor-post-status.hbs, app/templates/editor/edit.hbs
closes TryGhost/Ghost#8501
- don't show publish menu for new posts - the publishmenu options don't make much sense for a post that hasn't been saved yet
- show post status as "new" when a post is unsaved rather than "draft"
=> 🐛 empty posts shouldn't be publishable

app/components/gh-posts-list-item.js, app/controllers/posts.js, app/templates/posts.hbs, tests/acceptance/content-test.js
closes https://github.com/TryGhost/Ghost/issues/8675
- move `gh-posts-list-item` to closure actions
- add missing `openEditor` action in posts controller
=> 🐛 fix double-click on post to open editor

app/mixins/editor-base-controller.js
closes https://github.com/TryGhost/Ghost/issues/8636
- `save` action on editor base controller was not returning so the `_super` call in `editor.new` controller's `save` action returned `undefined` which broke the `.then` call
- force a dirty state in the `autoSaveNew` action so that the save still happens when the body gains focus whilst the title is blank
=> 🐛 fix autosave when title loses focus

app/components/gh-theme-error-li.js, app/styles/layouts/settings.css, app/templates/components/gh-theme-error-li.hbs, app/templates/components/modals/theme-warnings.hbs, app/templates/components/modals/upload-theme.hbs, tests/acceptance/settings/design-test.js
no issue
needs GScan 1.1.4
With GScan sending error details now, the modal was a bit overloaded.
This PR adds a toggle for each error rule which - when clicked - shows the details and the affected files.
TODOs:
=> 💄  Theme upload modal style improvements

app/components/gh-publishmenu-draft.js, app/components/gh-publishmenu.js, app/templates/components/gh-publishmenu.hbs, app/templates/components/gh-task-button.hbs, tests/acceptance/editor-test.js, tests/integration/components/gh-task-button-test.js
closes TryGhost/Ghost#8696
- Change wording to not include dashes
- Changes the `gh-save-button` component to allow a custom `runningText` which would be rendered in the button when the current task is running.
- Adds a `runningText` CP to `gh-publishmenu` component, which will render (depending of post status and desired save type) 'Unpublishing', 'Publishing', 'Scheduling', 'Updating', 'Unpublishing', 'Rescheduling', and 'Unscheduling'.
=> 🐷  Publish menu wording and saving states improvements

app/components/gh-markdown-editor.js
closes https://github.com/TryGhost/Ghost/issues/8695
- non-spellchecker mode should be "gfm" not "markdown" so that fenced
code blocks are displayed correctly and other markdown behaviour better
matches the preview/rendering
=> 🐛 fix editor fenced code block handling

app/styles/layouts/main.css
closes https://github.com/TryGhost/Ghost/issues/8625
- add CSS rules for the non-authed pages to remove the mobile nav bar
=> 🐛 don't show mobile nav bar when not logged in

app/controllers/reset.js
closes https://github.com/TryGhost/Ghost/issues/8688
- `reset` task wasn't returning a truthy value on success so `gh-task-button` flashed the "retry" state before the transition happened
=> 🐛 fix "failed" button flash on password reset

app/templates/editor/edit.hbs
closes https://github.com/TryGhost/Ghost/issues/8718
- only give focus to editor body when starting a new post
- update the title and body placeholders
=> 🎨 only focus editor body for new posts

app/services/tour.js
closes https://github.com/TryGhost/Ghost/issues/8730
- "and 'about' or 'contact' page" -> "an 'about' or 'contact' page"
=> 🎨 fix typo in welcome tour

app/templates/components/modals/markdown-help.hbs
no issue
- match shortcuts to the new editor shortcuts
- add shortcut for ordered lists
=> 🎨 update markdown help modal shortcuts

app/controllers/posts.js, app/styles/components/power-select.css, app/styles/layouts/content.css, app/templates/components/power-select-vertical-collection-options.hbs
closes https://github.com/TryGhost/Ghost/issues/8729, closes https://github.com/TryGhost/Ghost/issues/8728
- remove the duplicated `max-height` rules for different parts of the power select dropdowns - they were interacting with each other and causing a large part of the lists to be unreachable
- filter the temporary tags that are created when using the PSM tags input so duplicates aren't visible in the tags dropdown filter
=> 🐛 fix filter dropdown issues

app/mixins/editor-base-controller.js, app/routes/editor/edit.js, app/routes/editor/new.js, app/templates/components/gh-post-settings-menu.hbs, app/templates/editor/edit.hbs
refs TryGhost/Ghost#8723
- #795 contained a regression where the body focus was lost during the new->edit transition because at that point `model.isNew` is false
- returns `shouldFocusEditor` code that was removed in #768 (it was assumed the body should _always_ have focus in that PR)
- instant-save if body is edited and the post is new - fixes issue where you could keep typing without any save when body had autofocus
- don't show preview link for new posts - fixes issue where it links directly to the admin endpoint so it would force a refresh
=> [HOLD] 🐛 fix loss of editor focus on new post autosave

app/mixins/editor-base-controller.js, app/mixins/editor-base-route.js, app/templates/editor/edit.hbs, tests/unit/mixins/editor-base-controller-test.js
no issue
- fixes bug where multiple posts were created starting with one char and growing until the new->edit transition completed, e.g. posts with content such as `a`, `ab`, `abcd` were created in quick succession
- moves old `_savePromise` body into the `save` task
- call the `save` task instead of the old `_savePromise` so that concurrency is handled properly
- fixes odd behaviour with the "Are you sure you want to leave?" modal appearing too often - it's now aware of on-going or scheduled saves and will wait for those to complete before transitioning
- move all transition abort/save/retry handling into `toggleLeaveEditorModal` method
- check for a running save, wait for it to finish then retry the transition
- check for a scheduled autosave, cancel it if present and perform an …
=> 🐛 fix duplicate posts bug, more intelligent autosave when transitioning

app/components/gh-download-count.js
no issue
- default component tag of `<div>` forced the download count to appear on it's own line, setting `tagName: ''` returns the desired inline behaviour
Before:
After:
=> 🎨 fix download count position on setup/one

app/components/gh-markdown-editor.js, app/styles/components/notifications.css, yarn.lock
no issue
- adds Hemingway Mode toggle to the editor toolbar that disables backspace
- shortcut is <kbd>Ctrl+Alt+H</kbd>
=> ⚡️ hemingway editor mode (disable backspace)

app/components/modals/upload-image.js, app/templates/components/modals/upload-image.hbs
closes TryGhost/Ghost#8724
Adds a `isUploading` action that disables the `save` button for `upload-image` component until the upload process is finished.
=> 🙅  Disable image upload save btn when uploading

app/templates/setup/two.hbs, tests/acceptance/setup-test.js
People were having trouble with automatically entering password verification in blog title field. This re-orders the form to a more "normal" flow where password field is the last item on the page, so no risk of double-typing it.
Closes https://github.com/TryGhost/Ghost/issues/8622 by inadvertent knock-on effect.
=> Reorder account signup form

app/components/modals/theme-warnings.js, app/templates/components/modals/theme-warnings.hbs, app/templates/components/modals/upload-theme.hbs, app/templates/settings/design.hbs, tests/acceptance/settings/design-test.js
closes TryGhost/Ghost#8530
- Changed the wording for activation and uploading a theme to separate between error and warnings in the title and the body text for the modal
- Changed the wording of "Activated successful with warnings/errors" to "Activation successful with (warnings || errors)"
=> 🦄  Improved theme validation messages

app/styles/layouts/editor.css
closes https://github.com/TryGhost/Ghost/issues/8866
- add `overflow: hidden` to disable scrollbars on editor title input
=> 💄 Fix scrollbar on editor title input in Chrome on Windows

app/components/gh-uploader.js, tests/integration/components/gh-uploader-test.js
no issue
- push upload results into an array at the same index as the passed in files array
=> 🐛 Fix order of multiple upload results

app/styles/app-dark.css
closes https://github.com/TryGhost/Ghost/issues/8905
- import unsplash css file in `app-dark.css`
- add background and logo styles to match night shift styles
=> 🐛 Fix Unsplash when using Night Shift

app/components/gh-image-uploader.js
no issue
- the `config` injection in `gh-image-uploader` was missing so the Unsplash button was only being displayed for the length of the session after visiting the Unsplash app screen (creates in-memory settings record based on config) or more permanently by saving the Unsplash settings (in which case the image uploader component reads the settings from the DB rather than config)
=> 🐛 Fix missing Unsplash icons in uploaders when using config override

app/styles/app-dark.css
Closes TryGhost/Ghost#8875
Not sure if midgrey or lightgrey should be used. IMHO lightgrey is too bright
Here's midgrey (which I used)
=> Lighten upload theme description

app/controllers/subscribers.js, app/styles/patterns/tables.css
Closes TryGhost/Ghost#8876
Changed arrow styles to enable correct positioning. The sort arrow displayed below the `th` label; this CSS change fixes it.
Capitalization change: opinionated, but changing capitalization of “Address” to match “Subscription Date”.
Before:
After:
=> Addresses TryGhost/Ghost #8876

app/styles/layouts/apps.css, app/styles/layouts/users.css
responsive styles for .apps-configured and .apps-card adjusted, so that elements fit smaller device screens.
=> adjust mobile styles for apps-module (#8744)

app/templates/team/user.hbs
Fixes TryGhost/Ghost#8835
After changing the type to button, (from the default submit), it no longer causes the image to appear on enter in the fields.
=> Fixed upload page trigger

app/controllers/team/user.js
no issue
- the `updateSlug` task never returned a value if there was no change needed, this meant that giving the slug field focus then blurring it again caused the "Save" button to become red with "Retry" text
- always return true from `updateSlug` - this stops the button from showing "Retry" and will instead show "Saved" which is a little less confusing
=> 🐛 Fix save button showing "Retry" when user slug field loses focus

app/controllers/settings/design.js
Fixes TryGhost/Ghost#8764
After adding the item it sets the focus to the bottom gh-blognav-line element, the addNavItem gh-navitem component. 
I tried at first to see if I could edit the gh-navitem component. However, there are two gh-navitem components in the settings/design.hbs file. One is in the #each loop, which is surrounded by sortable-group component, the other is outside the each loop and is used to add items (addNavItem). Every time a new navItem is added the addNavItem gh-navitem component is pushed down to the bottom of the list. So that's why I decided to use jQuery outside the components to set the focus to that input box.
=> Fix field focus when adding navigation items

app/styles/layouts/editor.css
Assigns overrides to `og-preview-*` classes. Previously, the classes inherited their color from `body`. Now the preview appears correctly in both default and Night Shift modes.
Colors verified against Facebook's Sharing Debugger using the URL in @JohnONolan's bug report (TryGhost/Ghost#8864): https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fblog.ghost.org%2Fcustom-social-data%2F
I also threw in a couple blank line removals for organization. Opinionated but I did it for the sake of consistency.
=> Closes #8864

app/transforms/json-string.js, tests/unit/transforms/json-string-test.js
no issue
We've seen an issue where after an import a user record had `tour: ""` which meant they were unable to log in due to JSON parsing of the empty string failing.
- add a guard so that an empty string is transformed to `null` before parsing
- changed `serialised` to `serialized` to match spelling in all other serializers
=> Guard against blank strings in `json-string` fields

app/models/tag.js
refs TryGhost/Ghost#8943
- Tag model has an observer watching the `isNew` and `name` properties so that it can set the `visibility: "internal"` property for new tags based on their name starting with a `#`
- PSM creates tags using `store.createRecord('tag', {name: tagName})` which means that the tag is instantiated with the `isNew` and `name` properties already set (unlike the tags screen where an empty tag is first created before the name is set via UI) - because the properties are there at instantiation the observer never fires because it's only watching for changes
- adds the `.on('init')` modifier to the `setVisibilityOnNew` observer so that it's run for the watched properties during instantiation as well as on change
=> 🐛 Fix #tags added via PSM having "public" visibility

app/styles/layouts/settings.css
Override default `overflow: scroll` value that was causing the double scrollbar to appear.
Override an unnecessary (_at least for the __.settings-code-editor__ element scope_) `margin-right: -30px` on __.CodeMirror-scroll__ container that was causing the text inside to overflow.
Result:
This will fix the issue TryGhost/Ghost#8896
=> 🐛 Fix double-scrollbar in code injection editor

app/controllers/settings/apps/index.js, app/templates/settings/apps/index.hbs, tests/acceptance/settings/apps-test.js
no issue
On the apps index screen there were conditionals for each app so that active apps show "Active" instead of "Configure" when they are activated - the conditionals weren't working because the properties they check for weren't available in the template's context.
- add a new `settings/apps/index` controller that imports the `settings` service
- updates template conditionals to check for properties on the `settings` service
=> 🐛 Fix "active" state of apps on apps index screen

.travis.yml, package.json, testem.js, yarn.lock
no issue
- align Travis config more closely to default ember-cli setup
- run Chrome in headless mode in CI (Travis + `ember test`, `ember test --server` is "dev" mode)
- install yarn via install script rather than npm
- remove broccoli cache from Travis cache (not sure it ever worked?)
- remove forced node-sass install (no longer needed)
- add `testem` as a top-level dep to force the latest version (ember-data is pinned at 1.15)
=> Run Chrome in headless mode on Travis

app/styles/components/settings-menu.css
Fixes double scrollbar problem in code injection editor of PSM
refs #838, TryGhost/Ghost#8896
Before:
After:
=> Fix double scrollbar in code injection editor of PSM

app/html/apps.html, app/html/themes.html, app/templates/components/gh-nav-menu.hbs, app/templates/publishbutton.html
No issue
The uservoice wishlist has been pretty inactive and neglected for quite a long time now. Removing links to it from Ghost is the first step toward retiring it. We're still listening to user feedback in order to determine the Ghost roadmap, but simplifying the process around it.
Matches https://github.com/TryGhost/Ghost/pull/8981
=> Remove wishlist links

app/utils/format-markdown.js, package.json, yarn.lock
closes https://github.com/TryGhost/Ghost/issues/8958
- `markdown-it-named-headers` pulled in [`string.js`](http://stringjs.com) despite it not being used which added a lot of String.prototype extensions and caused Ember deprecation notices
- moves the short `markdown-it-named-headers` functionality directly into our app code without using `String.js`
=> Remove unwanted String.prototype extensions

app/templates/team/index.hbs
closes TryGhost/Ghost#8996
Fixes a bug, where properties in a nested component where not available and resulted in not rendering the users' profile images and 'last seen' dates on the team page.
=> 🐛  Fix team page regression bug

ember-cli-build.js
refs TryGhost/Ghost#8815, TryGhost/Ghost#8840, TryGhost/Ghost#8842, TryGhost/Ghost#8849
- `ember-cli` 2.14 introduced some [new defaults for uglify-js](https://github.com/ember-cli/ember-cli/pull/7077) that resulted in CloudFlare's Auto Minify feature mangling the JS files and causing syntax errors
- revert the `semicolons: false` option to restore compatibility
**Note:** This does _not_ mean it's recommended to use CloudFlare's Auto Minify feature. It's still recommended that all CloudFlare's performance settings are [disabled for /ghost* URLs](https://docs.ghost.org/docs/troubleshooting#section-ghost-admin-not-loading)
=> Improve built JS compatibility with CloudFlare's Auto Minify feature

app/templates/components/gh-date-time-picker.hbs
closes https://github.com/TryGhost/Ghost/issues/8891
- set the `center` option as well as the `selected` option for `{{power-datepicker}}` inside `{{gh-date-time-picker}}` to force the month view to jump to the correct date when the selection changes
=> 🐛 Fixed "scheduled at" datepicker not showing correct month when opening

app/templates/components/gh-tag.hbs
no issue
- adds a link to the existing stories count in the tags list that when clicked will transition to the stories screen showing all stories with that tag
=> 🎨 Link tags story count to filtered stories list

app/models/setting.js, app/transforms/unsplash-settings.js, tests/acceptance/editor-test.js, tests/unit/transforms/unsplash-settings-test.js
closes https://github.com/TryGhost/Ghost/issues/9031
- add a default value `unsplash` value to the `setting` model so that Unsplash is activated when the server doesn't return an `unsplash` setting
- update the `unsplash-settings` transform to always deserialize or serialize to `{isActive: true}` when the value is blank or not parsable
- add acceptance regression test covering API not returning an `unplash` setting
- add unit tests for the `unsplash-settings` transform
=> Fixed missing Unsplash icons when API doesn't return an unsplash setting

app/styles/app-dark.css
closes https://github.com/TryGhost/Ghost/issues/9030
- don't change the search input's background color when the input has focus in Night Shift
Before:
After:
=> 🐛 Fixed unreadable Unsplash search text in Night Shift mode

app/components/gh-uploader.js, app/controllers/settings/general.js, app/controllers/settings/labs.js, app/templates/settings/general.hbs, app/templates/settings/labs.hbs, tests/acceptance/settings/labs-test.js, tests/integration/components/gh-uploader-test.js
refs TryGhost/Ghost#9028
- add upload/download UI to labs screen
- displays success/failure state in the button for 5 secs after uploading
- minor refactor to remove redundant `{{#if}}` conditionals in general settings screen
- minor naming refactor of `onUploadFail` -> `onUploadFailure` for `{{gh-uploader}}`'s closure action
=> Upload/Download redirects UI

app/components/gh-file-upload.js, app/controllers/settings/labs.js, app/templates/settings/labs.hbs
closes https://github.com/TryGhost/Ghost/issues/8660
- detect a `413` when uploading an import and show the appropriate message
- refactor `{{gh-file-upload}}` to use closure actions
- add test selectors to import errors HTML
- note: doesn't include tests because `{{gh-file-upload}}` doesn't rely on the file input's `change` event (as used by our other uploader components to facilitate testing) and browsers don't allow us to artificially set and submit files
=> 🐛 Fixed missing "file too large" text for import uploads

yarn.lock
closes https://github.com/TryGhost/Ghost/issues/8775
- upgrades our SimpleMDE fork
- [bumps CodeMirror version to 5.30.0](https://github.com/kevinansfield/simplemde-markdown-editor/commit/b3e9f8b579fd3175064e62794d1c2d9f12811360)
- [fixes Home/End key behaviour on Windows](https://github.com/kevinansfield/simplemde-markdown-editor/commit/f2e981845cbcbb5b50d0df3c12b4d56f8412412a)
=> 🐛 Fixed incorrect Home/End key behaviour on Windows

app/components/gh-nav-menu.js
this fixes iconStyle when 'icon' is a full url, when custom storage adapter is used. 
Refs: 
https://github.com/TryGhost/Ghost/issues/8885
=> fix iconStyle when icon is a full url

app/styles/components/publishmenu.css
Closes https://github.com/TryGhost/Ghost/issues/8514
These changes should stop the affected elements from breaking outside their container in IE11, and should keep the fields the same sizes they were across other browsers.
=> Fixed IE11 incorrect publish menu date/time input sizes

mirage/config.js, mirage/config/authentication.js, mirage/config/invites.js, mirage/config/posts.js, mirage/config/subscribers.js, mirage/config/tags.js, tests/acceptance/editor-test.js, tests/acceptance/setup-test.js
no issue
We weren't being consistent in our use of Mirage's `normalizedRequestAttrs()` method which meant that in certain cases Mirage's internal database had duplicated attrs, the original set being `camelCase` and the new/updated set being `underscore_case` which was not only confusing but can lead to errors or unexpected behaviour in tests.
- updated Mirage config to always normalize where necessary
- updated tests to always use `camelCase` attrs
- added `HEAD` route handler for gravatar to avoid unknown route noise in tests
=> Fix normalization of attrs in Mirage config and tests

app/styles/app-dark.css
closes https://github.com/TryGhost/Ghost/issues/9056
- decrease transparency of background color applied to spellcheck errors in night shift
Before:
After:
=> 🐛 Fixed visibility of spellcheck errors in Night Shift mode

app/services/unsplash.js
closes https://github.com/TryGhost/Ghost/issues/9041
- add missing public `retryLastRequest()` method to Unsplash service
=> 🐛 Fixed broken "retry" link when an Unsplash API request failed

app/styles/layouts/editor.css
There's only one instance of smartquotes, removed in the edited editor.css file
ref: TryGhost/Ghost#8867
I haven't been able to reproduce the issue in my version of Edge, but that doesn't really mean anything, since my version of Edge can't seem to run the Ghost admin interface without crashing. I'm going to attribute that to user error (because I've made a lot of core changes to Windows) but I will post updates when I get access to another Windows computer
Whether or not this is causing an issue in Edge, it's probably a good idea to not use smartquotes since it's only used in _one_ place (for consistency and whatnot) 😆
=> Remove smartquotes

app/components/gh-search-input.js, app/helpers/highlighted-text.js
closes TryGhost/Ghost#8959
- Treated the search input as a literal string rather than `RegExp` to allow characters that need escaping in `RegExp` and disable `RegExp` characters like `|`.
- Replaced any non-word characters in `highlighted-text` fn with escaped characters, so they're working with `RegExp`.
=> 🐛 Fixed search behaviour to not use RegExp

app/mixins/editor-base-controller.js, app/mixins/editor-base-route.js
closes https://github.com/TryGhost/Ghost/issues/9072
- the checks when leaving the editor were detecting that the autosave tasks were running and so forcing an immediate autosave even though the autosave tasks wouldn't do anything
- exit early from autosave tasks if autosave isn't allowed
=> 🐛 Fixed incorrect autosave of published posts when leaving editor

app/styles/app-dark.css
closes https://github.com/TryGhost/Ghost/issues/9080
- increase lightness of the default CodeMirror html property colour
Before:
After:
=> 🐛 Fixed unreadable HTML property colours in Night Shift mode

app/components/gh-search-input.js, app/models/setting.js, app/routes/settings/tags.js, app/serializers/tag.js
closes https://github.com/TryGhost/Ghost/issues/9074
- remove unused pagination route attrs that were interfering with routing service - these were a pre-1.0 hangover from when the tags screen had infinite scroll
- fix `adapter returned an array for the primary data of a 'queryRecord' response` deprecation when loading a tag route directly
- change `Posts` to `Stories` in the search dropdown for consistency
=> 🐛 Fixed error when navigating to tag from admin search box

app/components/gh-search-input-trigger.js
closes https://github.com/TryGhost/Ghost/issues/9075
- ensure we re-focus the input element after closing the dropdown so that it's not necessary to click on the search input again after using backspace
- removes unnecessary use of `run.scheduleOnce`
- this was causing the error in TryGhost/Ghost#9075 because search was happening out of sync with the open/close of the dropdown in turn causing `ember-basic-dropdown` to try measuring non-existent elements
- alternative fix would be to wrap each open/close, focus, and search call in separate `run.scheduleOnce('afterRender', ...)` calls
- remove use of `invokeAction`, it's not been necessary in Ember for a while now and we should be calling methods directly where possible for easier debugging
=> 🐛 Fixed search losing focus when removing search term

app/components/gh-markdown-editor.js, yarn.lock
closes TryGhost/Ghost#8863
- Spellcheck shortcut: <kbd>Ctrl-Alt-S</kbd>
- Render preview shortcut: <kbd>Ctrl-Alt-R</kbd>
- Side-by-side preview shortcut: <kbd>Ctrl-Alt-P</kbd>
- fix "Hemmingway" typo
- update SimpleMDE fork to add a bypass of the Ctrl->⌘ transformation in toolbar button tooltips
=> 🎨 Added keyboard shortcuts for editor modes

app/utils/format-markdown.js
refs https://github.com/TryGhost/Ghost/issues/8987
- set `linkify-it` `fuzzyLink` option to false so that it only auto-links URLs starting with `http(s)://` or other valid schemes
=> Disable fuzzy auto-linking of URLs in markdown preview

app/components/modal-leave-settings.js, app/controllers/settings/general.js, app/routes/settings/general.js, app/templates/components/modal-leave-settings.hbs, app/templates/settings/general.hbs, tests/acceptance/settings/general-test.js
closes TryGhost/Ghost#8483
- Added a new modal component that gets rendered when leaving general/settings after changes have been done but not saved
- Added test
TODOs:
=> 🎣  Added modal for unsaved changes in settings

app/styles/patterns/global.css
no issue
- nested lists can become very cramped in post previews, this matches the top margin of the list to what would normally be used in-between list items
Before:
After:
=> Add top-margin to nested lists

app/components/gh-psm-template-select.js, app/models/post.js, app/models/setting.js, app/models/theme.js, app/styles/patterns/forms.css, app/templates/components/gh-post-settings-menu.hbs, app/templates/components/gh-psm-template-select.hbs, tests/acceptance/custom-post-templates-test.js, tests/integration/components/gh-psm-template-select-test.js
refs https://github.com/TryGhost/Ghost/issues/9060, requires https://github.com/TryGhost/Ghost/pull/9073
- add `{{gh-psm-template-select}}` component
- allows selection of a custom template for a post if the active theme has custom templates
- loads themes on render, only hitting the server if not already in the store
- disables select if post slug matches a `post-*.hbs` or `page-*.hbs` template
- adds `customTemplate` attr to `Post` model
- adds `templates` attr to `Theme` model with CPs to pull out custom vs post/page override templates
- add `.gh-select.disabled` styles to make disabled selects look visually disabled
=> Custom Post Templates UI

app/components/gh-post-settings-menu.js, app/controllers/error.js, app/models/post.js, app/serializers/post.js, app/templates/components/gh-post-settings-menu.hbs, mirage/config/users.js, tests/acceptance/authentication-test.js
no issue
- `controller.content` will no longer be an alias to `controller.model`
- re-org relationships and attrs in Post model, add missing transforms
- fix "unknown `error` field in payload" warning when `/users/me` returns 404 during tests
- fix unsafe style binding warnings caused by PSM twitter/facebook preview image styles
=> Fix Ember deprecations and warnings

app/templates/components/gh-psm-template-select.hbs
no issue
- adding missing conditional so we only display `Post URL matches post-slug-name.hbs` when a match is found
=> 🐛 Fixed "Post URL matches" text displaying when no slug match is found

app/validators/new-user.js, app/validators/reset.js, app/validators/user.js, tests/acceptance/setup-test.js, tests/acceptance/signup-test.js, tests/acceptance/team-test.js
refs TryGhost/Ghost#9150
needs TryGhost/Ghost#9152
- Increase the password length in validators for signups, pw resets, and password changes for users to 10 instead of 8
- Update tests
Todos:
=> ✨Increase password length for changes and signups

app/controllers/reset.js, app/models/user.js, app/routes/signup.js, app/validators/new-user.js, app/validators/password.js, app/validators/reset.js, app/validators/user.js, tests/acceptance/setup-test.js, tests/acceptance/signin-test.js, tests/acceptance/signup-test.js, tests/acceptance/team-test.js, tests/unit/models/user-test.js, tests/unit/serializers/user-test.js
refs TryGhost/Ghost#9150
- added a new validator for password validations that will take care of the rules client side
- Passwort rules added:
- Disallow obviously bad passwords: 1234567890, qwertyuiop, asdfghjkl; and asdfghjklm
- Disallow passwords that contain the words "password" or "ghost"
- Disallow passwords that match the user's email address
- Disallow passwords that match the blog domain or blog title
- Disallow passwords that include 50% or more of the same characters: 'aaaaaaaaaa', '1111111111' and 'ababababab' for example.
- When changing the own password, the old password is not affected by the new validations
- Validation are running on
- setup
- signup
- password change in Team - User (only new passwords are validated)
- passwort reset
=> ✨ Improved password validations rules

app/components/gh-navitem.js, app/controllers/settings/apps/amp.js, app/controllers/settings/apps/slack.js, app/controllers/settings/apps/unsplash.js, app/controllers/settings/code-injection.js, app/controllers/settings/design.js, app/controllers/team/user.js, app/routes/settings/apps/amp.js, app/routes/settings/apps/slack.js, app/routes/settings/apps/unsplash.js, app/routes/settings/code-injection.js, app/routes/settings/design.js, app/routes/team/user.js, app/templates/components/gh-navitem.hbs, app/templates/settings/apps/amp.hbs, app/templates/settings/apps/slack.hbs, app/templates/settings/apps/unsplash.hbs, app/templates/settings/code-injection.hbs, app/templates/settings/design.hbs, app/templates/team/user.hbs, app/utils/route.js, tests/acceptance/settings/amp-test.js, tests/acceptance/settings/design-test.js, tests/acceptance/settings/slack-test.js, tests/acceptance/settings/unsplash-test.js, tests/acceptance/team-test.js, tests/integration/components/gh-navitem-test.js
refs TryGhost/Ghost#9119
- Apps - AMP
- Added `leave-settings-modal` component to Settings - Apps - AMP
- Apps - Slack
- Added `leave-settings-modal` component to Settings - Apps - Slack
- Added a `triggerDirtyState` action that will uses a new Array with the input data to trigger the dirty state on the parent settings model
- Apps - Unsplash
- Added `leave-settings-modal` component to Settings - Apps - Unsplash
- Used manual tracking of changes with using a custom `dirtyAttributes` property and a `rollbackValue` to manually rollback the `isActive` attribute on the model
- Code injection
- Added `leave-settings-modal` component to Settings - Code injection
- Design
- Added `leave-settings-modal` component to Settings - Design (only for navigation model)
- Used manual tracking of changes …
=> 🎨  Added confirmation dialog for unsaved changes in settings

app/components/gh-post-settings-menu.js, app/mixins/editor-base-controller.js, app/templates/components/gh-post-settings-menu.hbs, app/templates/editor/edit.hbs
closes https://github.com/TryGhost/Ghost/issues/8969
Collision detection errors were appearing incorrectly because the save routines in the post settings menu bypass the sequential saves in the main editor controller and so are prone to having stale data if a previous save is still in progress.
- added a new `savePost` task that is part of the `saveTasks` group so that all post saves are sequential
- pass the `savePost` task to the `{{gh-post-settings-menu}}` component
- use `savePost` task in `gh-post-settings-menu` instead of calling `save()` directly on the model instance
**Note:** See https://github.com/TryGhost/Ghost/issues/8969 for local reproduction steps.
=> 🐛 Fixed "Someone else is editing" errors showing when no-one else is editing

app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/components/gh-uploader.js, app/components/modal-new-subscriber.js, app/components/modal-re-authenticate.js, app/components/modal-upload-theme.js, app/controllers/settings/design.js, app/controllers/setup/three.js, app/controllers/setup/two.js, app/controllers/signin.js, app/controllers/signup.js, app/mixins/editor-base-controller.js, app/routes/application.js, app/services/ajax.js, app/services/notifications.js, lib/gh-koenig/addon/components/cards/card-image.js, lib/gh-koenig/addon/components/cards/card-markdown.js, package.json, tests/acceptance/error-handling-test.js, tests/integration/services/ajax-test.js, tests/unit/services/notifications-test.js, yarn.lock
no issue
- upgrade `ember-ajax` to 3.0.0
- `ember-ajax` [now passes the payload through directly](https://github.com/ember-cli/ember-ajax/releases/tag/v3.0.0) rather than trying to normalize it so all our error handling needed to be updated
=> Bump ember-ajax dependency

app/routes/team/user.js
closes [TryGhost/Ghost#9174](https://github.com/TryGhost/Ghost/issues/9174)
- Added ```willTransition``` action which clears the password input fields when transitioning to a new route
=> clear password fields when leaving team/user page

app/templates/components/gh-tag-settings-form.hbs, app/validators/tag-settings.js, tests/integration/components/gh-tag-settings-form-test.js, tests/unit/validators/tag-settings-test.js
no issue
- Increased the possible length of the tag description field from 200 to 500
=> ✨  Increased tag description length to 500

app/styles/layouts/apps.css, app/styles/layouts/editor.css, app/styles/layouts/main.css, app/styles/layouts/settings.css, app/styles/layouts/users.css
Trying to close https://github.com/TryGhost/Ghost/issues/8744, I went through several parts of the admin interface improving the mobile styles (focusing on iPhone 6 and up).
I've tried to follow the CSS style as close as possible but please review the changes 👍
Here are the screens (could have missed one).
=> Improve admin styles on mobile

app/validators/tag-settings.js, app/validators/user.js, tests/acceptance/team-test.js, tests/unit/validators/tag-settings-test.js
refs TryGhost/Ghost#8143
Increases existing input validation lenght (soft limits) of the following fields:
- `tags.name`: 191 chars
- `tags.slug`: 191 chars
- `users.name`: 191 chars
=> 🗜  Increase soft limits

app/controllers/settings/general.js, app/controllers/team/user.js, app/templates/team/user.hbs, tests/acceptance/settings/general-test.js, tests/acceptance/team-test.js
closes https://github.com/TryGhost/Ghost/issues/9160
- simplified FB validation to allow any valid FB url (autocomplete of raw usernames and facebook-like URLs is still in place)
- fixed a bug with sticky Twitter validation message, if you entered an invalid URL then changed it to an invalid username you still saw the invalid URL message (surfaced through new test helpers for validating facebook/twitter fields)
=> 🐛 Fixed failing Facebook URL validation for group urls

app/components/gh-posts-list-item.js, app/controllers/posts.js, app/routes/posts.js, app/templates/components/gh-posts-list-item.hbs
closes https://github.com/TryGhost/Ghost/issues/9234
- add `featured` badge to stories/pages that have the featured flag
- add "Featured posts" to the post type filter dropdown
- simplified badge logic in `{{gh-posts-list-item}}`
=> 🎨 Added "Featured posts" filter and featured badge to stories list

app/validators/setup.js, app/validators/subscriber.js, app/validators/user.js
refs TryGhost/Ghost#8143
Added more client side validations for input fields:
- Blog title in setup flow (150 chars)
- User email (191 chars)
- Subscribers email (191 chars)
=> ✅ Added missing client validations

app/components/gh-editor.js, app/components/gh-file-input.js, app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/components/gh-markdown-editor.js, app/components/gh-profile-image.js, app/components/gh-uploader.js, app/controllers/settings/general.js, app/controllers/settings/labs.js, app/templates/components/gh-uploader.hbs, app/templates/settings/general.hbs, app/templates/settings/labs.hbs
closes https://github.com/TryGhost/Ghost/issues/9266
- `emberx-file-input` passes a `resetInput` function through to it's action handler but we weren't doing that in our override component. Added the missing functionality and updated all of our handlers to use that instead of doing manual resets
- added a `setFiles` action to `{{gh-uploader}}` and yield it for use in block invocations
=> 🐛 Fixed inability to re-upload the same redirects file

app/components/gh-alerts.js, app/components/gh-markdown-editor.js, app/components/gh-nav-menu.js, app/controllers/application.js, app/routes/application.js, app/templates/application.hbs, app/templates/components/gh-markdown-editor.hbs, app/templates/editor/edit.hbs
no issue
- in a very old iteration of the admin design we needed a data attribute containing the number of notifications in order to add extra spacing in the styles. This hasn't been necessary for a long time and there are easier ways to do it now than using observers.
=> Remove unused top notification count functionality

app/templates/application.hbs
closes TryGhost/Ghost#9293
Added https://github.com/TryGhost/Ghost-Admin/commit/14aa87ed39b93826d33ac23ac955aafcd4d5d69b#diff-f63965ba48df687541db46e0e1b2c2ecL10 back, which broke the rendering of the blog icon in the nav menu.
=> 🐛 Fixed blog icon not shown in nav

app/components/gh-editor.js
closes https://github.com/TryGhost/Ghost/issues/9300
- as of https://github.com/TryGhost/Ghost-Admin/commit/74428efd8bf5a3d896dd1c5c549553893bc5aa05 we reset the file input earlier in the actions chain, this was clearing the file references before the editor was triggering the upload. By converting the `FileList` to an `Array` before resetting the input we keep hold of the file references and the upload works again.
=> 🐛 Fixed editor image uploads

yarn.lock
closes https://github.com/TryGhost/Ghost/issues/9302
- reverts the `simplemde` bump introduced in https://github.com/TryGhost/Ghost-Admin/pull/911/, the updated version of CodeMirror appears to contain a bug or incompatibility with SimpleMDE
=> 🐛 Fixed "NaNUndefined" when inserting unordered list items

app/components/gh-token-input/trigger.js
closes https://github.com/TryGhost/Ghost/issues/9298
- override the default Ember Power Select behaviour of stopping keydown event propagation for any alpha-numeric key events which was preventing our keyboard shortcuts from being triggerable
=> 🐛 Fixed Ctrl/Cmd+S save shortcut not working when tags input has focus

app/components/gh-editor.js, app/components/gh-file-input.js, app/components/gh-file-uploader.js, app/components/gh-image-uploader.js, app/components/gh-profile-image.js, lib/gh-koenig/addon/components/cards/card-image.js
closes https://github.com/TryGhost/Ghost/issues/9321
- don't use `dataTransfer.effectAllowed` in IE11
- only fire the action in `{{gh-file-input}}` if there are files selected to prevent a double call to the action due to resetting the input
=> 🐛 Fixed editor and drag/drop image uploads in IE11

package.json, yarn.lock
This PR updates `ember-simple-auth` to v1.4.2 to take advantage of the bug fix in https://github.com/simplabs/ember-simple-auth/pull/1477
This will enable/unblock https://github.com/TryGhost/Ghost-Admin/pull/922
=> Update `ember-simple-auth` to v1.4.2

app/components/gh-download-count.js, app/components/gh-editor-post-status.js, app/components/gh-simplemde.js, app/controllers/settings/labs.js, app/mixins/editor-base-controller.js, app/services/clock.js, app/services/lazy-loader.js
no issue
- `Ember.testing` is or will soon be a getter/setter in Ember with the value set during a test, however destructuring will read the value when the module is evaluated
- moves all uses of `Ember.testing` inline
=> Don't destructure Ember.testing

app/mixins/editor-base-route.js
Addresses: https://github.com/TryGhost/Ghost/issues/9296
Also confirmed in ubuntu.
Shortcut changed to CTRL+SHIFT+P as CTRL+ALT+P is an already assigned shortcut in all platforms at:
https://github.com/TryGhost/Ghost-Admin/blob/312bd68f4c30b8b919ea4c0911c98faaca55ff8f/app/components/gh-markdown-editor.js#L113
A better fix would probably be a centralised or user controllable
shortcut config.
But for now, this or only setting the shift alternative for platforms
other than mac should fix this.
=> Addresses issue #9296 (unexpected publishing of post)

app/styles/layouts/apps.css, app/styles/layouts/users.css
Another go at https://github.com/TryGhost/Ghost/issues/8744.
Without changing the markup it's going to be difficult to wrap the badges when we have more than one. It's a bit of a compromise, as it looks fine with a slightly larger screen (iPhone 6 plus) and I want to avoid changing the design.
I've tried to get more space where possible reducing a bit the internal padding.
=> Improve users table mobile style

app/templates/settings/general.hbs
Fixes hover state inconsistency between 'Expand' and 'Upload new image' buttons in Settings > General.
=> Fix for icon upload button hover state in Settings > General

app/components/gh-cm-editor.js, app/styles/components/settings-menu.css, app/styles/layouts/settings.css, app/templates/components/gh-cm-editor.hbs, app/templates/components/gh-post-settings-menu.hbs
closes https://github.com/TryGhost/Ghost/issues/9249
- in `{{gh-cm-editor}}` display a standard textarea in place of the CodeMirror editor whilst CodeMirror assets are loading in the background, textarea will be upgraded to a CodeMirror editor when loading finishes
- update styles so that the switch from plain textarea to CodeMirror is not too jarring
=> 🎨 Improved code injection loading behaviour on slow connections

app/controllers/settings/labs.js
no issue
- show an error message when a non-Ghost error is received, eg. when a proxy server times out due to a large import
=> 🐛 Fixed non-existent error message for unexpected errors during import

tests/acceptance/settings/tags-test.js, tests/integration/components/gh-psm-tags-input-test.js
refs https://github.com/TryGhost/Ghost/issues/8805
- `{{vertical-collection}}` causes async issues and random failures in our tests
- we can't upgrade to the latest version which includes a test wait helper because it's buggy in Firefox
- skip the tests for now
=> Skip tests that touch vertical-collection to fix random Travis failures

app/styles/layouts/editor.css
closes TryGhost/Ghost#9289
- add css to fix hidden textarea position
Japanese IME popup position.
hidden textarea size and position.
Japanese IME popup position.
hidden textarea size and position.
=> Fixed Japanese IME popup position

app/components/gh-navitem-url-input.js, tests/acceptance/settings/design-test.js, tests/integration/components/gh-navitem-url-input-test.js
closes https://github.com/TryGhost/Ghost/issues/9373
- using an `<a>` element to parse a URL does not behave as expected when the URL has special characters because the `host` attribute will show the Puny URL version. Eg. `exämple.com` will become `xn--exmple-cua.com`
- `{{gh-navitem-url-input}}` was failing to manipulate the URL value because of the difference between the Puny URL encoded URL and the raw configured URL with unicode chars
- uses the `URI` module that's bundled with the imported version of `google-caja` to parse the URL via regexes rather than relying on native browser parsing
=> 🐛 Fixed navigation url inputs when configured URL has special characters

app/controllers/settings/apps/slack.js, app/validators/slack-integration.js
Towards https://github.com/TryGhost/Ghost/issues/9263
- trimming the URL value in the validator
Having a space in the URL would cause Ghost to complain - 
> The URL must be in a format like https://hooks.slack.com/services/<your personal key>
Now trimming the URL before validating.
Signed-off-by: Abijeet <abijeetpatro@gmail.com>
=> Trims the URL before saving or sending test notification

app/templates/settings/general.hbs
pull request #703
- added Language option to General Settings, just a text field for
flexibility, to allow any language
- click on the "Save settings" button, and restart Ghost to activate the
new language
- default: English (en); currently available: Spanish (es); translation
files can be added for any language
- the corresponding translation files should be at
_core/server/translations/en.json_, _es.json_... and
_content/themes/mytheme/assets/translations/mytheme_en.json_,
_mytheme_en.css_...
- `currentLocale`, dynamically based on overall settings (key =
"`default_lang`") in the `settings` db table
- during Ghost's initialization, settings available inside `i18n`
functions; see files _core/server/i18n.js_ and _index.js_
- there is a complementary commit for Ghost's PR …
=> [i18n] Added "Language and locale" to Settings

app/styles/components/modals.css, app/templates/components/modal-delete-user.hbs, tests/acceptance/team-test.js
closes TryGhost/Ghost#9405
Gives the user a clearer message before deleting a user.
User that is also author of posts:
User that hasn't written any posts:
---------
Todos:
=> ⭐️  Improved delete user confirm dialog

app/templates/settings/general.hbs
Two spelling and grammar fixes, and one technical.
- eg. → e.g.
- /yyyy/mm/slug/ → /yyyy/mm/dd/slug/
- , → .
=> Correct errors in /settings/general descriptions

tests/integration/components/gh-task-button-test.js
Newer versions of `mocha` will complain that `done()` was called with a `non-error` argument if used this way. This PR is needed to unblock #922.
/cc @kevinansfield
=> tests/gh-task-button: Return Promises instead of using `done()`

package.json, yarn.lock
This PR updates `ember-cli-mocha` to test the changes in https://github.com/emberjs/ember-mocha/pull/173 and https://github.com/ember-cli/ember-cli-mocha/pull/229
=> Update `ember-cli-mocha` to v0.15.0

app/templates/reset.hbs, app/templates/setup/two.hbs, app/templates/signin.hbs, app/templates/signup.hbs, tests/acceptance/setup-test.js
no issue
- if we would like to re-add html in our error messages, we have to differentiate between static messages which can contain html and messages which are dynamic and can contain dynamic input, which should not allow html
- e.g. it is always possible that Ghost receives a message from a third party module, which concats static text with input text
- if we want to show html content from an error, we need to come up with a concept
- for now: no support for html in error messages
I just went through the code base, where `<p class="main-error">` is used. Maybe there are more.
@kevinansfield feel free to push if something is missing.
=> Escape html for error messages

app/styles/components/uploader.css
Closes #9476
- added midgrey color to text on upload fail while night mode is on
=> Color change in theme upload error dialog box.

app/services/feature.js
Fixed -If night-shift is enabled, checkbox has to be clicked three times to disable
Closes #9471
- added check for undefined value
- fixed the condition in feature.js _setAdminTheme
=> Fixed -If night-shift is enabled, checkbox has to be clicked three times

bower.json, config/environment.js, mirage/config/settings.js, mirage/factories/invite.js, mirage/factories/post.js, mirage/factories/user.js, mirage/fixtures/roles.js, mirage/models/invite.js, mirage/models/post.js, mirage/models/tag.js, mirage/serializers/post.js, package.json, tests/acceptance/content-test.js, tests/acceptance/editor-test.js, tests/acceptance/subscribers-test.js, tests/acceptance/team-test.js, tests/integration/components/gh-psm-tags-input-test.js, yarn.lock
closes TryGhost/Ghost#9433
- remove unnecessary bower deps
- update mirage usage
- fix tests
Took a bit longer than expected, but got this working as far as I can tell, minus some flaky tests. This will likely need a fairly significant update too once the multi-author stuff is merged in.
=> Bump ember-cli-mirage to 0.4.2

app/styles/components/modals.css, app/styles/patterns/forms.css
Super small issue but I noticed when I was using the Ghost Admin in Firefox, when I opened the "Invite Team" modal, a scrollbar would briefly appear and the form would be scrollable by 1px. This PR fixes it so it no longer scrolls.
=> Prevent Firefox Fieldset Scrolling

app/mixins/shortcuts.js, tests/helpers/destroy-app.js
no issue
Keymaster.js bindings could be kept around between tests with references to objects that should have been deleted. This was manifesting itself with a Tags acceptance test failing because one of the key binding tests triggered two actions, one on the route under test and another on a route that was kept around from a previous Error Handling acceptance test (previous test intentionally had an aborted transition so the action in the current test was complaining about the first transition not being complete).
- add guard to ensure that shortcuts can't be registered multiple times on an object
- remove all `default` scope keymaster bindings when destroying a test app instance
=> Prevent keymaster bindings from causing failed tests

package.json, yarn.lock
closes TryGhost/Ghost#9434
Just bumping the dependency didn't seem to cause any issues 🤔- I tested it manually as well as ran tests locally. @kevinansfield were there specific things you noticed that were broken?
=> Bump ember-light-table dependency

app/components/gh-cm-editor.js, app/components/gh-file-uploader.js, app/components/gh-fullscreen-modal.js, app/components/gh-image-uploader.js, app/components/gh-navitem-url-input.js, app/components/gh-tag-settings-form.js, app/components/gh-task-button.js, app/components/gh-timezone-select.js, app/components/modal-base.js, app/components/modal-delete-subscriber.js, app/components/modal-delete-tag.js, app/components/modal-delete-theme.js, app/components/modal-delete-user.js, app/components/modal-import-subscribers.js, app/components/modal-leave-editor.js, app/components/modal-leave-settings.js, app/components/modal-suspend-user.js, app/components/modal-transfer-owner.js, app/components/modal-unsuspend-user.js, app/components/modal-upload-theme.js, app/utils/link-component.js, package.json, yarn.lock
closes TryGhost/Ghost#9477
- remove ember-invoke-action in favor of straight function calls
Need to do some manual testing of this, but this _should_ be good.
=> Remove ember-invoke-action

app/routes/posts.js, tests/acceptance/content-test.js
no issue
- we need `?filter=authors:foo` to match all posts where `foo` is an author, the previous `?filter=author:foo` will only match posts where `foo` is the primary author
=> Fixed authors filter for posts with multiple authors

app/templates/team/index.hbs
When you suspend a user, it moves out of the "Active Users" list, to the "Suspended Users" list. Each user in this list currently looks like this:
It does not pull through the user image or the last seen time and it looks a bit odd. This PR fixes this so both an image and last seen time now show and it looks like this:
=> fixed suspended users list so it now shows image and last seen time

app/mixins/shortcuts.js, package.json, yarn.lock
closes https://github.com/TryGhost/Ghost/issues/9543
- https://github.com/TryGhost/Ghost-Admin/pull/972 moved `keymaster` from Bower to NPM but version 1.6.3 is not published to NPM and it contains fixes for unbinding multiple keys (eg, `'down, j': 'moveDown'`). Switched to fetching directly from github to ensure we have the latest version
- removed the "has registered shortcuts" guard added in https://github.com/TryGhost/Ghost-Admin/pull/976 - it was working around the buggy keymaster version but was also buggy itself because it meant shortcuts could only be registered the first time a route was loaded even though we unregister all of the shortcuts when leaving the route
=> 🐛 Fixed `j` and `k` keys not working in editor after visiting Tags screen

app/models/post.js, mirage/fixtures/configurations.js
refs TryGhost/Ghost#9561
- use the hardcoded routeKeyword for `preview`
- removed `routeKeywords` from mirage configurations API fixtures
=> Replaced config routeKeyword with hardcoded one

tests/acceptance/subscribers-test.js
no issue
- `ember-in-viewport` was forced to a newer version in https://github.com/TryGhost/Ghost-Admin/commit/cb46718a264daa283c92a015414bd37037a9b0c0 which has resulted in the subscriber table's infinite scroll triggering immediately in FF when testing
=> Fix subscriber table tests in FF

app/components/gh-editor.js, app/templates/components/gh-editor.hbs, app/templates/components/gh-koenig-editor.hbs, app/templates/editor.hbs, lib/koenig-editor/addon/components/koenig-card-html.js, lib/koenig-editor/addon/components/koenig-card-markdown.js, lib/koenig-editor/addon/components/koenig-card.js, lib/koenig-editor/addon/components/koenig-editor.js, lib/koenig-editor/addon/templates/components/koenig-card-html.hbs, lib/koenig-editor/addon/templates/components/koenig-card-markdown.hbs, lib/koenig-editor/addon/templates/components/koenig-card.hbs, lib/koenig-editor/addon/templates/components/koenig-editor.hbs, package.json, yarn.lock
refs https://github.com/TryGhost/Ghost/issues/9505
- use `ember-sticky-element` to stick card icons in top left when scrolling
- pass an `headerOffset` down from the `{{gh-editor}}` component through Koenig and the card components so that it can be used for adjustments where necessary
- calculate `headerHeight` in `{{gh-editor}}` any time we change the header class
TODO:
=> Koenig - Sticky card icons

ember-cli-build.js
Doing so causes a double pass through asset-rewrite and forces both to take much longer. This cuts 3s off of rebuilds, bringing them to ~500-700ms on my mac.  Using asset-rewrite as is done in dev mode is also suspicious, likely a better setup could be devised that doesn't require rewrite to interop with the local ghost server. I'd estimate 250ms of savings on rebuilds by doing so.
The end result of the RFC for pre-built addons will likely reduce initial build times by 50%, and rebuilds by 250ms based on my observations using https://github.com/rwjblue/heimdalljs-visualizer
Reducing dependence on packages using ember-browserify would also help, rollup is often a better solution here, but that work overlaps with the RFC work.
=> [BUGFIX perf] don't fingerprint assets in development

app/templates/components/gh-koenig-editor.hbs, app/templates/editor.hbs, lib/koenig-editor/addon/components/koenig-editor.js, lib/koenig-editor/addon/options/key-commands.js
refs https://github.com/TryGhost/Ghost/issues/9505
- when cursor changes through the normal `cursorDidChange` or through certain programmatic changes we trigger a check to see if the cursor is out of the viewport and scroll it into view if necessary
- disable our scroll-into-view routine if the mouse button or shift key is down so that we don't interfere with default browser behaviour which works well in that situation
- for scroll-into-view at the bottom there are two slightly different methods
- if the cursor is near the bottom of the document we scroll so that the bottom padding of the editor is visible
- if the cursor is mid-document then we scroll just enough to bring the cursor into the viewport
TODO:
- doesn't appear to be too much of a problem. Timing the main `__scrollIntoView` …
=> ✨ Koenig - Keep cursor on screen whilst typing or moving via keyboard

app/routes/editor/edit.js
closes https://github.com/TryGhost/Ghost/issues/9582
fix editor's loading bug by deleting the loading template
=> fix editor's loading state

app/templates/components/modal-invite-new-user.hbs
Issue https://github.com/TryGhost/Ghost/issues/7132
- Removed tabindex from role selection on invite user field.
- Removing the tabindex defaults the tabindex to "-1".
👋 Hey y'all, this solves this issue with not being able to tab over to the role dropdown after putting in an email address. It does not, however, solve the issue of autofocusing the email field when the modal is created.
When digging into the autofocus I found that it seems to be an issue with the ember component lifecycle hooks and the modal itself. From what I can tell, the `didInsertElement` method in the `text-input` mixin gets called before the element is visible on the screen. By the time the element is visible on the screen, it has lost its focus.
I was able to make it work by placing a `setTimeout` around the …
=> Remove tabindex from role selection field

app/components/gh-search-input.js, app/routes/editor/edit.js, app/routes/posts.js, mirage/config/posts.js, tests/acceptance/content-test.js
no issue
- `staticPages` API param is deprecated in favour of using the `filter` param
- switched `status` query to param to the `filter` param as well for consistency
=> Use `filter` instead of `status` and `staticPages` params for post queries

lib/koenig-editor/addon/components/koenig-card-image.js, lib/koenig-editor/addon/templates/components/koenig-card-image.hbs
requires https://github.com/TryGhost/Ghost/pull/9741
- using `payload.cardWidth` so that it's more generic than having separate width attributes for every card
=> Koenig - Rename image card payload.imageStyle to payload.cardWidth

app/controllers/application.js, app/routes/editor.js, app/styles/layouts/editor.css, app/templates/editor.hbs
refs https://github.com/TryGhost/Ghost/issues/9724
- when Koenig is active, toggle `ui.isFullscreen` when entering/leaving the editor route
- add `ui.isFullscreen` to the `showNavMenu` CP in the application controller
- when in fullscreen mode, display a "< Stories" link in the editor header
- refine editor header style
=> 🎨 Koenig - Hide sidebar when editing

app/controllers/settings/design.js
closes https://github.com/TryGhost/Ghost/issues/10011
- theme download URLs were missing the `/download/` portion
=> 🐛 Fixed theme download links

app/controllers/editor.js, app/models/post.js, app/templates/components/gh-post-settings-menu.hbs
no issue
- Admin API v2 outputs absolute URLs so we no longer need to construct full URLs ourselves
=> Adjust post URL handling for API v2's absolute URLs

app/components/modal-delete-webhook.js, app/components/modal-webhook-form.js, app/controllers/settings/integration.js, app/controllers/settings/integration/webhooks/edit.js, app/helpers/event-name.js, app/router.js, app/routes/settings/integration/webhooks/edit.js, app/templates/components/modal-delete-webhook.hbs, app/templates/components/modal-webhook-form.hbs, app/templates/settings/integration.hbs, app/templates/settings/integration/webhooks/edit.hbs
requires https://github.com/TryGhost/Ghost/pull/10033
- added `settings.integration.webhooks.edit` route
- `/integrations/:integration_id/webhooks/:webhook_id`
- added error handling to the webhook form modal that copes with the actual errors we get back from the server
- added `event-name` helper to display humanised event names in the webhooks list
- added delete button to the webhooks list and associated confirmation modal
TODO:
=> Added edit webhook modal

app/components/aspect-ratio-box.js, app/controllers/settings/integration.js, app/templates/components/aspect-ratio-box.hbs, app/templates/settings/integration.hbs
no issue
- add `{{aspect-ratio-box}}` to make it easier to adjust box sizes at a fixed ratio based on container height which isn't possible with CSS directly
- used `{{gh-uploader}}` to add upload facility to the icon shown on the integration screen
=> Added ability to upload integration icons

app/controllers/setup/three.js
no issue
- Escaped email ids string sent to notification message during blog setup
Credits: Antony Garand
=> Fixed sanitization of user invited emails for notification message

app/components/modal-webhook-form.js, app/controllers/settings/integration.js, app/controllers/settings/integrations.js, app/routes/settings/integration.js, app/templates/components/modal-webhook-form.hbs, app/templates/settings/integration.hbs, app/templates/settings/integrations.hbs
closes TryGhost/Ghost#9942
- move custom integrations UI out from behind the developer experiments flag
- put Admin API key and web hook secret fields behind the developer experiments flag
- do not show "unsaved changes" modal when adding/editing a webhook
- fixed all webhooks showing for each custom integration
=>  ✨ Added custom integrations - Content API Keys and "Site rebuild" webhooks

lib/koenig-editor/addon/components/koenig-card-image.js, lib/koenig-editor/addon/components/koenig-card.js, lib/koenig-editor/addon/templates/components/koenig-card-code.hbs, lib/koenig-editor/addon/templates/components/koenig-card-html.hbs, lib/koenig-editor/addon/templates/components/koenig-card-markdown.hbs
refs https://github.com/TryGhost/Ghost/issues/10049
- update `{{koenig-card}}` component to compare payload values and create a snapshot when exiting edit mode for container cards (markdown, html, code)
- update image card to trigger snapshots on image upload/selection and width change
=> 🐛 Fixed editor undo states for card contents

app/components/gh-psm-tags-input.js, app/controllers/posts.js, app/controllers/settings/tags.js, app/templates/components/gh-tag.hbs, tests/acceptance/content-test.js, tests/acceptance/settings/tags-test.js, tests/integration/components/gh-psm-tags-input-test.js
no issue
- switch tags sorting from ID based to alphabetical
- pre-requisite to nested tags sorting
=> 🎨 Changed tags screen, filter dropdown, and select input to sort alphabetically

app/styles/layouts/apps.css
No issue
Resolves error with integration background icon images being tiled
Before:
After:
=> Fix display bug on app icons

lib/koenig-editor/addon/components/koenig-card-gallery.js, lib/koenig-editor/addon/templates/components/koenig-card-gallery.hbs
closes https://github.com/TryGhost/Ghost/issues/9840
- added error on trying to upload an invalid image format to gallery card
- updated error message logic to use both overall error method(`onFailed`) to set error message as well as individual upload failures(`onUploadFailure`)
=> Added image validation error message to gallery card

app/templates/components/modal-markdown-help.hbs
Fixes https://github.com/TryGhost/Ghost/issues/10227
Corrected the link for the Markdown documentation. @kevinansfield Please review.
=> Fix the link for Markdown guide documentation.

lib/koenig-editor/addon/components/koenig-card-gallery.js
no issue
- use `URL.createObjectURL(file)` to get a blob url rather than using `FileReader.readAsDataURL` which generates a very large data attribute
- speeds up the display of previews and associated browser hangs when an upload finishes, especially noticeable with large images and fast connections where multiple uploads finish around the same time
=> Optimised gallery image upload previews

lib/koenig-editor/addon/components/koenig-card-gallery.js, lib/koenig-editor/addon/lib/dnd/constants.js, lib/koenig-editor/addon/lib/dnd/container.js, lib/koenig-editor/addon/lib/dnd/utils.js, lib/koenig-editor/addon/services/koenig-drag-drop-handler.js, lib/koenig-editor/addon/templates/components/koenig-card-gallery.hbs, lib/koenig-editor/app/services/koenig-drag-drop-handler.js
no issue
- first pass at implementation of drag-and-drop re-ordering of images within a gallery
- adds a `koenig-drag-drop-handler` service that allows consumers (editor, cards, etc) to hook into drag and drop behaviour without interfering with each other and allows for future possibilities such as dragging images between galleries or into/out of galleries
=> ✨ Added drag-n-drop re-ordering of images within gallery cards

lib/koenig-editor/addon/components/koenig-card-gallery.js, lib/koenig-editor/addon/templates/components/koenig-card-gallery.hbs
no issue
- when dragging an image, if you dragged out of the gallery then back in directly over the space between images then no indicator was shown
- switch to using padding around images rather than margin so that the mouse can be detected over the gap. Added classes to the image overlays to account for the change in sizing
=> Fixed drop indicator not showing if placed directly between images

lib/koenig-editor/addon/components/koenig-card-gallery.js, lib/koenig-editor/addon/services/koenig-drag-drop-handler.js
no issue
- clear the cached `insertIndex` when hiding the drop position indicator
- update the gallery card's `_isDropAllowed` function to return `false` if the `droppabeIndex` (`insertIndex`) doesn't exist
=> 🐛 Fixed gallery image changing order randomly when dropped on itself

lib/koenig-editor/addon/lib/dnd/constants.js, lib/koenig-editor/addon/lib/dnd/scroll-handler.js, lib/koenig-editor/addon/lib/dnd/utils.js, lib/koenig-editor/addon/services/koenig-drag-drop-handler.js
no issue
Adds auto-scroll if the mouse is placed near the top or bottom of the window whilst dragging an image to re-order it within a gallery. Useful when the position you want to drag to is not currently on screen.
- append drop indicator element to `.koenig-editor` element to account for scrolling (also fixes indicator positioning bug with current implementation if you use mouse-wheel or keyboard to scroll the page whilst dragging)
- generalise `getParent` util to accept a 
- switch to using selectors rather than dataset for finding parent draggable/droppable/container
- add a `ScrollHandler` class that is used by the `koenigDragDropHandler` service to trigger scrolling whilst dragging
=> ✨ Added auto-scroll when dragging gallery images

mirage/config/authentication.js, package.json, tests/unit/helpers/gh-format-post-time-test.js, yarn.lock
refs https://github.com/TryGhost/Ghost/issues/10310
- bump liquid-fire (cleans up multiple deprecations)
- bump ember-sinon
- bump ember-optional-features
- bump ember-assign-helper
- bump ember-cli-dependency-checker
- bump ember-cli-mirage
- bump ember-cli-pretender
- bump ember-cli-es6-transform
Partial dependency bump. Keeping groups smaller so that any issues are easier to pin down if needed.
=> Bump dependencies

README.md, app/controllers/setup/three.js, app/services/tour.js, app/templates/about.hbs, app/templates/components/gh-nav-menu.hbs, app/templates/editor.hbs, app/templates/settings/general.hbs, app/templates/settings/labs.hbs, tests/acceptance/settings/design-test.js
This updates the all the old-style documentation links sprinkled through Ghost-Admin. Most of them were already redirecting, but it seems like a good idea to clean this up.
I've done my best to match up the context of the URL with best piece of documentation available.
@JohnONolan One thing that you might want to review more closely is the README.md file.
Matching PR for Ghost to follow.
=> Updated docs links to best equivalents

app/controllers/editor.js, app/controllers/settings/general.js, app/routes/editor.js, app/utils/document-title.js, tests/unit/controllers/editor-test.js
refs TryGhost/Ghost#10088
The change moved the title information into a function that returns the
correct title or if no title is set for now "Editor" for the editor route. That should help
with multiple Editor tabs open since it now displays the correct title.
Before:
After:
=> Update title of page in editor to current title of post.

app/services/unsplash.js, mirage/config.js
Fixes: https://github.com/TryGhost/Ghost/issues/10455
=> Load the most recent unsplash images.

app/components/gh-image-uploader.js, app/components/gh-uploader.js, app/controllers/setup/two.js, app/controllers/signup.js, app/templates/settings/general.hbs, app/templates/staff/user.hbs, mirage/config/uploads.js, tests/acceptance/settings/general-test.js, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js, tests/integration/components/gh-uploader-test.js
refs https://github.com/TryGhost/Ghost/issues/10438
@kevinansfield changed `/uploads` endpoints to `/images` and updated response handling for those endpoints to use new structure (`{url: 'image_url'}`). Would love to receive feedback on possible other places that might be affected by the response structure change
=> Drop uploads in admin api

app/templates/components/gh-post-settings-menu.hbs, app/templates/components/modal-delete-post.hbs
Closes tryghost/ghost#10577
- Update templates to use `post.displayName` rather than hard-coded `Post`
Fixed three separate things:
- Code injection
- Delete ... action button
- Delete ... modal
=> 🐛 Post -> Page in Page PSM and delete modal

.travis.yml, config/coverage.js, package.json, testem.js, tests/test-helper.js, yarn.lock
no issue
- improves test run times by splitting the tests into multiple groups and running each in their own browser instance
- settled on 2 browser instances as that seems to best fit within Travis' memory and CPU constraints
- updated ember-cli-code-coverage config to work with parallel builds
=> Used ember-exam to split tests and run in parallel on Travis

renovate.json
no issue
- ignore `ember-exam` until it's compatible with latest stable of `ember-mocha`
- see https://github.com/ember-cli/ember-exam/issues/238
- moved `ember-exam`, `ember-mocha`, and `testem` into their own group so changes to test env don't cause addon upgrade PRs to fail
=> Updated Renovate configuration

app/styles/layouts/settings.css, app/templates/components/gh-theme-error-li.hbs, app/templates/components/modal-theme-warnings.hbs, app/templates/components/modal-upload-theme.hbs, mirage/config/themes.js
refs. https://github.com/TryGhost/Team/issues/206
Improvements for theme upload and activation dialogs:
- updated copy for buttons and static descriptions
- updated style for better readability of gscan errors
- fixed modal scrolling when gscan output is too long to fit on screen
=> Gscan styles

app/templates/components/gh-post-settings-menu.hbs, app/templates/components/gh-publishmenu-draft.hbs, app/templates/components/gh-publishmenu-published.hbs, app/templates/components/gh-publishmenu.hbs
Closes TryGhost/Ghost#10658
- Update publish menu states to use `{{post.displayName}}` instead of hard coded `post`
- Update settings menu image uploader to generate CTA using `post.displayName`
=> Fixed post/page labels in feature image and save components

renovate.json
no issue
- latest `ember-exam` is now compatible with latest stable `ember-mocha` release
=> Removed "ember-exam" from list of ignored packages in Renovate configuration

renovate.json
no issue
- the `config:base` preset sets a maximum of 2 PRs per hour
- we have specific timings for Renovate in this repo so the max limit is more hindrance than help
=> Remove 2-per-hour PR limit for Renovate

app/styles/layouts/content.css
closes [#9494 issue](https://github.com/TryGhost/Ghost/issues/9494) 
-Modified the content_list css class
It's my first PR here. You can find the use-case in posts list (admin panel), where the problem was reported in the issue.
=> 🐛 Fixed the scroll problem using safari on low resolutions smartphones

.travis.yml
Fundamental problem: cos renovate pushes branches to the main repo, when it opens a PR there are 2 checks, one for push and one for the pr.
Currently to fix that we exclude renovate branches, and only build renovate PRs
That means we can't use automerge branch, as we wouldn't run any checks!
This swaps to running only renovate pushes, which means the branch always gets checked
PR builds check the merge commit, but as renovate always rebases from latest master, this is effectively the same commit as the push.
=> Updated .travis.yml swap renovate build to push

renovate.json
no issue
- `ember-in-viewport` has introduced a change in 3.5.0 that is incompatible with `ember-light-table` so adding it to the ignore list temporarily
=> Re-configured Renovate to ignore ember-in-viewport

app/services/lazy-loader.js
Over in:
* https://github.com/whatwg/html/issues/3840
* https://bugzilla.mozilla.org/show_bug.cgi?id=1281135
I'm trying to come up with a model for `<link rel="stylesheet" disabled>` in
which Blink / WebKit and Firefox can agree on.
See that HTML spec issue for all the inconsistencies of WebKit / Blink, and the
following post for more context:
* https://groups.google.com/d/msg/mozilla.dev.platform/BdgNaChHnpY/mhXzCBwSCgAJ
---
Unfortunately, my change to Firefox breaks the Ghost Admin panel night-mode
switch (you can see it in Firefox Nightly).
This is because with my change, removing the `disabled` attribute from an
stylesheet behaves the same regardless of whether the `disabled` attribute is
added dynamically or not.
That means that adding the `disabled` attribute dynamically "unloads" …
=> Fix theme-switching in Firefox Nightly.

app/components/gh-cm-editor.js, app/styles/spirit/_font-weight.css, app/styles/spirit/_koenig.css, app/templates/components/gh-cm-editor.hbs, lib/koenig-editor/addon/components/koenig-card-code.js, lib/koenig-editor/addon/components/koenig-card.js, lib/koenig-editor/addon/components/koenig-editor.js, lib/koenig-editor/addon/options/text-expansions.js, lib/koenig-editor/addon/templates/components/koenig-card-code.hbs
no issue
- Added a language indicator when in rendered mode and a language input when in edit mode
- Allow code card language to be set with <code>```lang</code>+<kbd>Space/Enter</kbd> expansion 
- previously <code>\`\`\`</code> would immediately create a code card, the <kbd>Space/Enter</kbd> is now necessary for the insertion to occur
- lang is optional <code>\`\`\`</code>+<kbd>Space/Enter</kbd> will insert a code card with no language selected
- requires <kbd>Enter</kbd> to be pressed to finalise the expansion and insert the card
- Set the code card editor's language mode based on selected language
- set the CodeMirror mode based on the code card payload language
- add a basic map of language short codes to their respective CodeMirror modes
- observe `mode` property in …
```
=> ✨ Added language selection to code cards

lib/koenig-editor/addon/components/kg-action-bar.js, lib/koenig-editor/addon/components/koenig-caption-input.js, lib/koenig-editor/addon/components/koenig-card-code.js, lib/koenig-editor/addon/components/koenig-card.js, lib/koenig-editor/addon/options/parser-plugins.js, lib/koenig-editor/addon/services/koenig-drag-drop-handler.js, lib/koenig-editor/addon/services/koenig-ui.js, lib/koenig-editor/addon/templates/components/kg-action-bar.hbs, lib/koenig-editor/addon/templates/components/koenig-card-code.hbs, lib/koenig-editor/addon/templates/components/koenig-card.hbs, lib/koenig-editor/addon/templates/components/koenig-toolbar.hbs, lib/koenig-editor/app/components/kg-action-bar.js, lib/koenig-editor/app/services/koenig-ui.js
requires https://github.com/TryGhost/Ghost/pull/10719
- added caption component to the code card
- updated the click-to-edit behaviour for cards with edit mode to allow clicks through to the caption element so that caption clicks, selects, etc don't trigger edit mode
- added allow-clickthrough data attribute to the toolbar element so clicks on the caption's formatting toolbar don't trigger edit mode
- added parser plugin to transform `<figure><pre /><code /><figcaption /></figure>` into a code card with a caption
- improved code card parser plugins so that they can set the code card's language if a `lang-x` or `language-x` CSS class is detected
- added `koenig-ui` service for tracking when a caption has focus so that we can disable card toolbars when a caption has focus
- aliased the …
=> ✨ Added caption support to code cards

.travis.yml, README.md, mirage/config.js, package.json, yarn.lock
no issue
- coverage reports were not really being used and were frequently ignored when merging PRs because we knew there were reductions in test coverage
- coveralls also causes some problems with Renovate because there can be random micro changes in reported coverage that meant a PR "failed" when really it was fine
=> Removed coveralls code-coverage reporting

app/templates/settings/design.hbs
no issue
- Marketplace moved to https://ghost.org/marketplace
=> 🔗 Update link to Marketplace

package.json
no issue
- Node v6 has come to EOL as of 2019-04-30 (ref. https://github.com/nodejs/Release#end-of-life-releases)
=> 🔥 Dropped Node v6 support

app/services/feature.js
We currently set admin theme by dynamically loading `ghost-dark.css` and based on the value of `nightShift` feature. In extreme cases, when `ghost-dark.css` is unavailable, it causes the ember route to crash as we reject the promise from `lazyLoader` service which is currently not being handled in `setAdminTheme` method.
As a quick fix, `setAdminTheme` method is updated to catch the error from `lazyLoader` and enable light theme as graceful exit.
Known issue: Admin will crash in case user attempts to toggle theme again from UI :(
=> Fixed missing ghost-dark.css causing crash

app/templates/components/gh-date-time-picker.hbs, tests/acceptance/editor-test.js
refs TryGhost/Ghost#10767
The use of the date format 'MM/DD/YYYY' is confusing to those not in American English locations. In the absence of being able to dynamically determine full locale data, using 'YYYY-MM-DD' seems to the least ambiguous date format which would be intuitive to most users.
=> 🎨 Changed post/page date picker format to 'YYYY-MM-DD'

app/templates/components/gh-nav-menu.hbs
no-issue
Preview implies something which is not-yet-live, but this feature only shows the live site.
=> Renamed "Preview site" to "View site"

app/templates/components/modal-markdown-help.hbs, app/templates/editor.hbs
refs #10803
Corrected link to editor usage FAQ in both instances of use in admin client.
=> 🐛Fixed links to editor FAQ page

package.json
no issue
- Node v6 has come to EOL as of 2019-04-30 (ref. nodejs/Release#end-of-life-releases)
Note: updating travis to run on Node v10 caused build to fail - https://travis-ci.org/gargol/Ghost-Admin/builds/549962391 . Left it on v8 for now as it wasn't a priority. @kevinansfield did see similar fails when upgrading Travis environment to Node v10 in current master?
=> Dropped Node v6 support for 1.x

lib/koenig-editor/addon/components/koenig-card-gallery.js, lib/koenig-editor/addon/components/koenig-editor.js, lib/koenig-editor/addon/lib/dnd/container.js, lib/koenig-editor/addon/services/koenig-drag-drop-handler.js
no issue
- adjust drag handlers in the editor and gallery card to handle drag/drop of image cards as well as straight images
- adjust drag handlers in the gallery card to handle image inserts as well as re-orders
- add `onDragEnd` event/action to the Koenig drag-n-drop handler so that containers can perform cleanup if one of their draggables was successfully dropped into a different container
- change ghost element when dragging an image card to be an image rather than a card icon
- allow `createGhostElement` function passed in when registering a drag-n-drop container to fall back to the default behaviour by returning a falsy value
- fixed position bugs in the gallery re-ordering when dropping images
TODO:
=> ✨ Added ability to drag images in and out of galleries

package.json
no-issue
This is to keep it in sync with Ghost (https://github.com/TryGhost/Ghost/pull/10914)
=> Bumped minimum node v8.x version to v8.10.0

app/authenticators/cookie.js, app/components/gh-task-button.js, app/controllers/signin.js, app/routes/application.js, app/routes/site.js, app/services/ajax.js, app/services/session.js, app/templates/signin.hbs, mirage/config/config.js, tests/acceptance/error-handling-test.js, tests/unit/authenticators/cookie-test.js
closes https://github.com/TryGhost/Ghost/issues/10995
- when first loading the site preview, if private mode is enabled submit the login form in the background to retrieve the session cookie before loading the iframe
- refactors post-authentication preloading to ensure it occurs before post-authentication route hooks are called
- adds `showSuccess` attribute to `<GhTaskButton>` so that when set to `false` it can stay in the running state after "success" to avoid state change flashes whilst waiting for a transition
=> 🎨 Added auto-login to private site when viewing site preview in admin

app/utils/ghost-paths.js, mirage/config.js, tests/integration/adapters/tag-test.js, tests/integration/adapters/user-test.js, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js, tests/integration/components/gh-uploader-test.js, tests/integration/services/config-test.js, tests/integration/services/feature-test.js, tests/integration/services/slug-generator-test.js, tests/integration/services/store-test.js, tests/unit/authenticators/cookie-test.js, tests/unit/models/invite-test.js, tests/unit/serializers/notification-test.js
no issue
- Ghost-Admin is our primary API client, we should keep it in sync with the canary API branch to dog food our API changes
=> Switched Admin API version from v2 to canary

app/models/setting.js, app/styles/layouts/settings.css, app/styles/spirit/_flexbox.css, app/templates/settings/general.hbs
closes https://github.com/TryGhost/Ghost/issues/10921
- added new fields to settings model
- added "Site SEO" section to general settings
@peterzimon ready for you to work your design magic when you're back 😄 
@JohnONolan a wording review would be good, so far it's only been copied across from a rough sketch so it could do with some tweaking - do we want to mention the fallback behaviour anywhere?
=> ✨ Added global meta data and Twitter/Facebook card settings

app/utils/ghost-paths.js, mirage/config.js, tests/integration/adapters/tag-test.js, tests/integration/adapters/user-test.js, tests/integration/components/gh-file-uploader-test.js, tests/integration/components/gh-image-uploader-test.js, tests/integration/components/gh-uploader-test.js, tests/integration/services/config-test.js, tests/integration/services/feature-test.js, tests/integration/services/slug-generator-test.js, tests/integration/services/store-test.js, tests/unit/authenticators/cookie-test.js, tests/unit/models/invite-test.js, tests/unit/serializers/notification-test.js
Depends on https://github.com/TryGhost/Ghost/pull/11073
- Updates default admin endpoint to v3 from canary
=> Switched Admin API version from canary to v3

app/services/feature.js, app/templates/settings/labs.hbs, mirage/fixtures/configs.js
Changes are related to API v0.1 being completely gone and this flag won't be returned from anywhere anymore. 
I rarely get into Ember codebase (shame on you Naz! :grimacing:) Would appreciate a quick glance if there are any obvious things I missed. Checked the UI and tests but just in case :crossed_fingers:
=> 🔥 Removed publicAPI feature flag related code

app/components/gh-search-input.js, app/routes/editor/edit.js
no issue
- The default post/user filter gets expanded to the same values default values as `status=all` used to: https://github.com/TryGhost/Ghost/blob/e57e19e/core/server/api/canary/utils/serializers/input/posts.js#L97
@kevinansfield didn't find any more references to this filter seems like quite a small change :smiley:
=> 🔥 Removed unnecessary '?status=all' query parameter

lib/koenig-editor/addon/templates/components/koenig-card-image.hbs
This kept bugging me so I made a tweak suggestion
Before:
After:
=> Improved alt text UI legibility

app/components/gh-psm-visibility-input.js, app/controllers/editor.js, app/controllers/settings/labs.js, app/models/setting.js, app/serializers/post.js, app/templates/components/gh-psm-visibility-input.hbs, app/templates/settings/labs.hbs, tests/integration/components/gh-psm-visibility-input-test.js
~is :no_entry_sign: by https://github.com/TryGhost/Ghost/pull/11183~
Changes:
=> Content visibility configuration in labs

app/components/gh-post-settings-menu.js, app/templates/components/gh-post-settings-menu.hbs
no issue
- Limited visiblity to only those users who have the rights to edit post's visibility
=> Hidden post visibility select from PSM for non editors

app/controllers/editor.js
no issue
- if you created a post by setting a title but did not enter anything into the editor body before trying to leave the editor you'd see an "unsaved changes" modal because the "scratch" value for the post mobiledoc is `null` but the post's real mobiledoc value is now a blank document as returned from the API
- adds a conditional reset of the `post.scratch` value after a successful save if the scratch value is blank
=> 🐛 Fixed "unsaved changes" modal when leaving a new post with no content

app/controllers/member.js, app/controllers/members.js, app/templates/members.hbs
no issue
Members calculation was breaking when viewed on admin without refresh after adding/deleting new members and coming back after navigation, updated to more robust calculation logic.
=> 🐛 Fixed members count on list page

app/controllers/member.js
no issue
- a route-level `save` action was set up on the `member` route which calls `controller.send('save')` but the corresponding `save` action was never set up on the controller which meant the action bubbled back up to the route creating an infinite loop
=> Fixed Cmd+S in member details form

app/templates/components/gh-member-settings-form.hbs, app/templates/member.hbs
no issue
- `{{gh-task-button}}` was used inside a form but didn't have a `type="button"` property which meant the browser was treating it as a submit button and triggering the `save` action and related animation before the field's focus-out was called resulting in a save request before the scratch value is transferred to the model
- removed the submit action from the `<form>` element to prevent any other accidental triggers before scratch values have been transferred into real model values
=> Prevented enter key submitting misleading member details save request

app/templates/tags/tag.hbs
no issue
- `{{gh-task-button}}` was used inside a form but didn't have a `type="button"` property which meant the browser was treating it as a submit button and triggering the save action and related animation before the field's focus-out was called resulting in a save request before the scratch value is transferred to the model
- removed the submit action from the `<form>` element to prevent any other accidental triggers before scratch values have been transferred into real model values
=> Fixed enter in tag screen inputs triggering save

app/controllers/members.js
refs https://github.com/TryGhost/Ghost/issues/11298
The members export csv admin API by default paginates the result and only returns upto 15 members. This change passes `limit` param to the API with `limit=all` to fetch all members in result, by using change in PR - https://github.com/TryGhost/Ghost/pull/11299
=> 🐛 Fixed members csv export only exporting upto 15 members

app/components/gh-members-lab-setting.js, app/components/gh-post-settings-menu/email.js, app/components/gh-publishmenu-draft.js, app/controllers/settings/labs.js, app/models/setting.js, app/services/settings.js, app/templates/components/gh-members-lab-setting.hbs, app/templates/settings/labs.hbs, mirage/fixtures/settings.js
This PR -
- Adds new bulk email settings in settings API
- Uses dynamic `isEnabled` and `isCondig` flags from bulk email settings to configure UI and bulk email usage
- Wires mailgun email settings to bulk email settings for read/edit
=> Added new bulk email settings

app/adapters/email.js, app/components/gh-publishmenu.js, app/components/modal-confirm-email-send.js, app/controllers/editor.js, app/models/email.js, app/templates/components/gh-publishmenu.hbs, app/templates/components/modal-confirm-email-send.hbs, tests/acceptance/editor-test.js
no issue
- adds a `.retry()` method to the email model+adapter
- adds a retry email task to the publishmenu that follows the same retry-then-poll behaviour as the regular email confirmation
- show a retry button in the confirm email modal if the original send failed
=> Added ability to retry failed emails from confirm email modal

app/components/gh-member-avatar.js, app/helpers/gravatar.js, app/styles/layouts/members.css, app/templates/components/gh-member-avatar.hbs, app/templates/components/gh-members-list-item.hbs, app/templates/member.hbs, app/templates/member/new.hbs
- When an email has a valid gravatar handle it displays an image instead of initials for the member
TODO:
@rishabhgrg would love a second pair :eyes: on the Ember code. Thaaanks!
=> 🎨  Added gravatars for member avatars

app/components/gh-member-settings-form.js, app/styles/layouts/members.css, app/templates/components/gh-member-settings-form.hbs
refs TryGhost/Members#107
- Adds logic for more descriptive member subscription label when it's due to be canceled. 
- Adds a link to subscription in Stripe
Visuals:
=> Added members cancel subscription fields on members page

renovate.json
no issue
- having so many addons grouped into a single PR is difficult to manage when not reviewing, updating and merging frequently. If a single addon requires deeper work or breaks our node support range than it blocks upgrades on all other addons which then compounds required effort over time
=> Removed ember-addons Renovate group

app/components/gh-date-time-picker.js, app/components/gh-publishmenu.js, app/templates/components/gh-date-time-picker.hbs, app/templates/components/gh-post-settings-menu.hbs, app/templates/components/gh-publishmenu-draft.hbs, app/templates/components/gh-publishmenu-scheduled.hbs, app/templates/components/gh-publishmenu.hbs
closes https://github.com/TryGhost/Ghost/issues/9256
- stores the typed date internally to the component until
- Enter is pressed whilst focused
- Ctrl/Cmd+S is pressed whilst focused
- the input loses focus
- shows an error message if the typed date is not in the correct format or is invalid
- stops Ctrl/Cmd+S propagating if the typed date is not in the correct format or is invalid
- as long as the date is valid it calls the `setDate` action when the input loses focus, Ctrl/Cmd+S or Enter is pressed
TODO / Problems:
=> ✨ Enabled manual typing of post publish dates

renovate.json
no issue
- we want to support all LTS versions and not just the latest
=> Switched to Renovate's LTS support policy

app/controllers/staff/user.js, app/models/base.js, app/models/user.js, app/serializers/application.js, app/templates/components/modal-delete-user.hbs, app/templates/staff/user.hbs
refs https://github.com/TryGhost/Ghost/pull/11466
Adds db export download after popup for user deletion is closed.
TODO:
=> Basic flow for triggering db export on user deletion

app/components/gh-publishmenu-draft.js, app/components/gh-publishmenu-scheduled.js, app/templates/components/gh-publishmenu-draft.hbs, app/templates/components/gh-publishmenu-scheduled.hbs
no issue
So far, only owners or Admins were allowed to control the send email setting while publishing/scheduling a post. This change allows Editors to see the setting as well and toggle as needed.
=> Allowed editors to send email on publish

app/routes/editor.js, app/templates/editor.hbs
Realised when a page is deleted the user is redirected to posts instead of staying in pages. This pull request keeps the user in pages when deleting a page and in posts when deleting a post.
=> 🎨 Fixed page delete redirect

lib/koenig-editor/addon/components/koenig-editor.js, lib/koenig-editor/addon/components/koenig-link-input.js, lib/koenig-editor/addon/components/koenig-link-toolbar.js, lib/koenig-editor/addon/templates/components/koenig-editor.hbs
closes https://github.com/TryGhost/Ghost/issues/9792
- use `getClientRects()` to get separate rectangles for each line of a link and use the mouse position to find the closest one so that the toolbar can be positioned relative to that link section on that line rather than always in the middle of the editor canvas
- pass the rectangle used for positioning the link toolbar through to the link input component so that there is no jumping of position when clicking the edit button
=> 🐛 Fixed unreachable link toolbar when editing wrapped links

app/components/gh-task-button.js, app/controllers/member.js, app/controllers/settings/code-injection.js, app/controllers/settings/design.js, app/controllers/settings/general.js, app/controllers/settings/integration.js, app/controllers/settings/integrations/amp.js, app/controllers/settings/integrations/slack.js, app/controllers/settings/integrations/unsplash.js, app/controllers/tag.js, app/templates/components/modal-custom-view-form.hbs, app/templates/components/modal-members-label-form.hbs, app/templates/member.hbs, app/templates/settings/code-injection.hbs, app/templates/settings/design.hbs, app/templates/settings/general.hbs, app/templates/settings/integration.hbs, app/templates/settings/integrations/amp.hbs, app/templates/settings/integrations/slack.hbs, app/templates/settings/integrations/unsplash.hbs, app/templates/settings/labs.hbs, app/templates/tag.hbs
no issue
Currently the save buttons across Admin don't auto-reset to idle state after success/failure after click which can get confusing once user makes any subsequent changes and sees the old button state. This PR 
- adds auto-reset option to the task button component which allows reset to idle state after a fixed timeout
- updates all relevant save buttons in Admin to use the new option to auto-reset
=> 💄Updated save buttons to reset state

app/components/modal-billing.js, app/controllers/billing.js, app/routes/billing.js, app/services/billing.js, app/templates/billing.hbs, app/templates/components/modal-billing.hbs
The purpose if this change is to allow opening "billing" popup through a URL. It is not meant to render any information. It's purpose is:
1. Trigger open modal action
2.  Parse and pass relevant query parameter - "action"
@kevinansfield wanted to know your opinion on this approach and if the use of billing route is appropriate for this usecase. The naming of the parameters is not final (the "action" part). Naming will be reviewed once the whole flow works :) Let me know if this billing modal could be approached in a more ember-friendly way.
Example use: 
1. Open`http://localhost:2368/ghost/#/billing?action=success
2. This opens a modal with a BMA iframe which has `?action=success` passed in
3. After closing the BMA modal we return to default Ghost-Admin view
The rest of actions opening …
=> Added handling for /billing route with query param passing to BMA

lib/koenig-editor/addon/options/cards.js
no issue
- any content inside the email card will not appear on the site, instead it will only be shown when using the members system to email the post to your members
- email card content can contain `{first_name}` or `{first_name, "fallback"}` to personalise it for each member
=> ✨ Added "Email" card for inserting content that only appears when emailing posts to members

app/templates/components/modal-post-email-preview.hbs
no issue
- added `sandbox` attribute which blocks scripts from running inside the iframe
- results in better representation of how embeds will render in emails where scripts are not allowed
=> 💄 Adjusted email previews to better represent email behaviour for embed cards

app/controllers/settings/labs.js, app/templates/settings/labs.hbs
closes TryGhost/Ghost#11472
Works around a probable Safari bug in which only `yml` files were selectable with the existing `accept` field value. Adds a new `yamlAccept` variable which combines the mime types with the yaml extension array (providing the `yaml` extension explicitly allows it).
=> 🐛 Fixed unselectable routes files in macOS Safari

app/components/gh-members-lab-setting.hbs, app/components/gh-members-lab-setting.js
no-issue
We are going to keep the UI as a fallback in future. Eventually this
`if` will include an `else` block rendering a Stripe Connect button.
[This diff will be much nicer to look at](https://github.com/TryGhost/Ghost-Admin/pull/1576/files?w=1)
=> Hid Stripe apikey form if `stripeDirect: false`

app/controllers/members.js, app/helpers/reset-query-params.js, app/routes/members.js, app/templates/members.hbs
requires https://github.com/TryGhost/Ghost/pull/11854
- ties the search input on the members screen to a `?search` query param, debounced at 250ms to avoid unnecessary API requests and UI churn
- updated the members route's `model` hook to pass through the search param in the API request query parameters
=> Added server-side search to new members screen

app/components/gh-post-settings-menu.hbs, app/components/gh-post-settings-menu.js
refs https://github.com/TryGhost/Ghost/issues/11841
- Allows editors to see email customization option for sending test newsletters
- Editors had the necessary permission fixtures but the UI was previously only available to owners or administrators
=> 🐛 Fixed email preview not visible to Editors

app/components/gh-mobile-nav-bar.hbs, app/components/gh-nav-menu.hbs
These commits fix various small problems in the admin main screen.
- The button to show or hide the custom post types had no label.
- The menu separators weren't accessible.
- The mobile More menu button didn't have a proper Button role.
=> 🐛 Fixed various small accessibility problems in the admin screen

app/components/gh-post-settings-menu.hbs, lib/koenig-editor/addon/components/koenig-card.hbs, lib/koenig-editor/addon/components/koenig-link-input.hbs, lib/koenig-editor/addon/components/koenig-menu-content.hbs, lib/koenig-editor/addon/components/koenig-plus-menu.hbs, lib/koenig-editor/addon/components/koenig-slash-menu.hbs, lib/koenig-editor/addon/components/koenig-toolbar.hbs
This fixes various problems in the post screen and the editor. Missing button labels, roles, etc.
This improves accessibility for people with disabilities.
=> Various A11y post screen fixes

app/components/modal-delete-all.hbs, app/components/modal-delete-integration.hbs, app/components/modal-delete-member.hbs, app/components/modal-delete-post.hbs, app/components/modal-delete-tag.hbs, app/components/modal-delete-theme.hbs, app/components/modal-delete-user.hbs, app/components/modal-delete-webhook.hbs, app/components/modal-impersonate-member.hbs, app/components/modal-import-members.hbs, app/components/modal-invite-new-user.hbs, app/components/modal-leave-editor.hbs, app/components/modal-leave-settings.hbs, app/components/modal-markdown-help.hbs, app/components/modal-members-label-form.hbs, app/components/modal-re-authenticate.hbs, app/components/modal-regenerate-key.hbs, app/components/modal-suspend-user.hbs, app/components/modal-theme-warnings.hbs, app/components/modal-transfer-owner.hbs, app/components/modal-unsuspend-user.hbs, app/components/modal-upload-theme.hbs
no issue.
Some `a` tags with `href` attributes that are empty are used as buttons, but since the href is not linkifying anything, they appear as text nodes to assistive technologies. Give them a `"button"` role so it is guaranteed that assistive technologies will pick them up as actionable controls.
=> 🐛 Fixed various Close buttons throughout the UI.

app/components/gh-task-button.js, app/styles/patterns/buttons.css, tests/acceptance/staff-test.js
Closes https://github.com/TryGhost/Ghost/issues/11789
- By default, action buttons had auto-reset off and reset had to be explicitly set
- Auto reset for action buttons is on by default now, and any button that should not reset should explicitly switch it off
=> Enabled auto reset state for action buttons

app/components/gh-post-settings-menu/email.hbs, app/components/gh-publishmenu.hbs, app/components/modal-custom-view-form.hbs, app/components/modal-impersonate-member.hbs, app/components/modal-members-label-form.hbs, app/templates/member.hbs, app/templates/settings/code-injection.hbs, app/templates/settings/design.hbs, app/templates/settings/general.hbs, app/templates/settings/integration.hbs, app/templates/settings/integrations/slack.hbs, app/templates/settings/integrations/unsplash.hbs, app/templates/settings/labs.hbs, app/templates/tag.hbs
no issue
- Since task buttons by default have reset on now, we don't need to explicitly add it to individual buttons
=> Removed redundant reset value for task buttons

app/styles/patterns/buttons.css, app/templates/staff/user.hbs
refs TryGhost/Ghost#11789
refs https://github.com/TryGhost/Ghost-Admin/commit/aaac4147456fbb2fe4bd1ab2decc0a8ee52b2fab
- Reverted aaac414 as we want to handle the state without relying on CSS specificity, handles properly using task button property
- Updates fix for change password button on staff user edit screen to use task button props instead
Cleanup for all task buttons to handle default button color using `idleClass` property is handled in separate commit.
=> Refactored task buttons class handling

app/components/gh-alert.hbs, app/components/gh-members-lab-setting.hbs, app/components/gh-members-lab-setting.js, app/components/modal-from-address-confirmation.hbs, app/components/modal-from-address-confirmation.js, app/controllers/settings/labs.js, app/routes/settings/labs.js, app/styles/components/notifications.css, app/styles/patterns/buttons.css, app/styles/spirit/_line-height.css, public/assets/icons/close-stroke.svg
refs https://github.com/TryGhost/Ghost/issues/11414
depends on - https://github.com/TryGhost/Ghost/pull/11876
- Restructures member settings in labs, from address gets its own section
- Removes explicit site domain for fromAddress as we allow updating the full address
- Adds new CTA to trigger magic link for updating members from address
- Adds new confirmation modal for email sent to new from address
TODO:
=> ✨ Allowed domain change for members "from" address

app/services/members-utils.js
no-issue
This is now the central place for checking if stripe is configured for
members and we want to make sure that the Stripe Connect correctly
affects this value
=> Updated isStripeEnabled to use stripeConnectIntegration

app/components/gh-members-filter.hbs, app/controllers/members.js, app/helpers/reset-query-params.js, app/routes/members.js, app/templates/members.hbs
requires https://github.com/TryGhost/Ghost/pull/11892
- adds `?paid` query parameter to members route that is tied to the `?paid` query param in the API request
- added all/free/paid members dropdown to members filter component
TODO:
- matched existing design where chart is hidden when a label or search filter is applied
=> ✨ Added all/free/paid filter to members admin screen

app/components/gh-nav-menu.hbs, app/components/gh-nav-menu.js
closes https://github.com/TryGhost/Ghost/issues/11882
- Editors have all the same permissions and access to tags as Owner/Admin roles, but had the sidebar navigation for tags missing
- Adds "Tags" to sidebar for Editor roles as well
=> Added tags sidebar navigation for editors

app/components/gh-task-button.js
closes https://github.com/TryGhost/Ghost/issues/11866
Updating a slug on user profile triggers [`updateSlug`](https://github.com/TryGhost/Ghost-Admin/blob/28aa16f9a96b13bdcac116777e2be9b41b8ca437/app/controllers/staff/user.js#L369) task, which is in the [same task group](https://github.com/TryGhost/Ghost-Admin/blob/28aa16f9a96b13bdcac116777e2be9b41b8ca437/app/controllers/staff/user.js#L452) as `save` task which is tied to the Save button on page. Every-time `updateSlug` is called after editing a slug, it triggers the task button states causing the button to incorrectly show "Saving" -> "Saved" status change though no save action is called.
- Adds extra check to task button states if the last task ran was same as the current associated task
- In case of task groups, triggering one task in …
=> 🐛 Fixed staff profile editing incorrectly showing saved state

app/components/gh-navitem.hbs, app/components/gh-navitem.js, tests/integration/components/gh-navitem-test.js
no issue
- Fixes nav item values not saving on keyboard save shortcut
- Nav items value was only being updated in settings on focus out from text field.
- In case of keyboard save, focus out didn't happen so old value got saved and re-populated
- Change fixes to update setting value while typing
=> 🐛 Fixed nav item not saving updated value on keyboard save

app/controllers/settings/integrations/amp.js, app/models/setting.js, app/templates/settings/integrations/amp.hbs
refs https://github.com/TryGhost/Ghost/issues/11980
This adds a new UI to set the `amp_gtag_id` setting.
When AMP is disabled:
When AMP is enabled:
=> Added AMP Gtag UI

app/components/gh-post-settings-menu/email.hbs, app/components/gh-post-settings-menu/email.js, app/services/ajax.js
refs https://github.com/TryGhost/Ghost/issues/11971
- Newsletter preview email request has been using hardcoded fixed error message
- Reads custom error message from server's API response to show when available
=> Added custom error message handling for newsletter email failures

app/styles/spirit/_koenig.css
Code tag within a heading in the editor ignores font-size fixed #11814.
https://github.com/TryGhost/Ghost/issues/11814
=> Fixed  #11814

app/controllers/settings/general.js, app/templates/settings/general.hbs
no issue
- Accent color setting was behind dev flag on General settings screen
- Its now moved inside Portal settings where its primarily being used
- This change removes it from general settings screen so its only on Portal settings
=> Removed accent color from general settings

app/adapters/base.js, app/adapters/member.js, app/components/modal-delete-member.hbs, app/components/modal-delete-member.js, app/controllers/member.js
no-issue
This adds a new adapter for the member model so we can (optionally) add a `cancel` query parameter to the DELETE URL for members
Also updates the delete member modal to include a conditionally (based on active subscriptions) displayed toggle to enable/disable the `cancel` query parameter.
=> Updated delete member UI to add toggle to cancel subscriptions

app/controllers/editor.js
closes #12102
There was a typo which showed the month instead of day. This should fix the issue.
=> 🐛 Fixed incorrect scheduled date in toast

app/templates/member.hbs
closes https://github.com/TryGhost/Ghost/issues/12126
- Previously, only Owner user was shown option to impersonate a member
- Grants Administrator user ability to impersonate a member as well
=> Allowed Admin users to impersonate members

app/styles/app-dark.css
no issue
Adds a new css class selector to app-dark.css to mimic the same effect as created in the gh-markdown-editor. The class keonig-card-html--editor is applied conditionally when the card is in edit mode, as per its template file. This now makes the cursor the same color as the text and easier to read.
=> 🐛 Changed caret color to white in code editor on Night Shift

app/components/gh-members-lab-setting.hbs
no issue
depends on https://github.com/TryGhost/Ghost/pull/12211
- Other than dev flag, the Portal is now also enabled behind a dedicated `portal` flag
- Shows/hides Portal settings based on dev or Portal flag
=> Moved Portal settings behind dedicated flag

app/components/modal-impersonate-member.hbs
no-issue
Since https://github.com/TryGhost/Ghost/pull/12218 magic links now have
an expiry of 4 hours.
=> Updated magic link expiry to 4 hours

app/components/gh-token-input.js, tests/acceptance/editor-test.js
closes TryGhost/Ghost#11786
It was because ember-power-select was stopping the propagation of the events when ctrl/cmd or meta key is down.
----
`GhTokenInput` uses `PowerSelect` component of `ember-power-select` internally in `app/components/gh-token-input/select-multiple`. 
When you open that component, [you can find](https://github.com/cibernox/ember-power-select/blob/d36f38f39eba6a0afad6fd23821d20c06a9a42ef/addon/components/power-select.ts#L262-L278) that it calls `stopImmediatePropagation` when ctrl/cmd or meta key is down.
```js
handleTriggerKeydown(e: KeyboardEvent) {
if (this.args.onKeydown && this.args.onKeydown(this.storedAPI, e) === false) {
e.stopImmediatePropagation();
return;
}
if (e.ctrlKey || e.metaKey) {
e.stopImmediatePropagation();
return;
}
if ((e.keyCode >= 48 && …
```
=> Fix GhTokenInput not handling keyboard shortcut bug.

app/index.html, app/styles/layouts/main.css
No issue.
On newer iOS devices with no home button, we have this bar at the bottom of the screen instead. When installed as a PWA, the mobile nav sits under that bar. I'm unsure how much Ghost is used this way, but this is a small QOL improvement for those who do.
This PR uses the native `env` CSS custom properties Safari has to add a propriety amount of `padding-bottom` to the mobile nav bar, and also the global container to prevent anything in the iframe from being hidden by the taller nav bar. If the device does not support these `env` vars, is has no adverse affect. In order for this to work, the `<meta name="viewport" />` tag needs `viewport-fit=cover` added to it.
MDN docs for reference: https://developer.mozilla.org/en-US/docs/Web/CSS/env
The screenshots here show a before and …
=> Add margin to bottom of Admin when installed as PWA on newer iOS devices

app/components/gh-members-chart.js
closes #[12014](https://github.com/TryGhost/Ghost/issues/12014)
-startDateLabel variable populated in order to show start date for the members chart.
=> startDateLabel populated

app/controllers/settings/general.js
no issue
- Social account(twitter/facebook) values in general settings were only updated to settings upstream on focus out
- Keyboard shortcut save (Cmd/Ctr + S) doesn't trigger focus out event so values were not getting updated
- Updates save task to use new twitter/facebook values if changed on all save
=> 🐛 Fixed social settings not saved on keyboard shortcut

app/controllers/members.js, app/styles/components/dropdowns.css, app/templates/members.hbs
:warning: Relies on this https://github.com/TryGhost/Ghost/pull/12228
The button has the `disabled` attribute, so will not allow to export - can be styled based on this attribute too
=> Added support for filtering the exported Members CSV

app/components/gh-tag-settings-form.hbs, app/controllers/tag.js
closes https://github.com/TryGhost/Ghost/issues/12190
The "scratch" concept was being used incorrectly for codeinjection
fields and was not initialised with all the required fields.
=> Fixed tag metadata fields not being populated

app/components/gh-member-settings-form.hbs, app/components/gh-member-settings-form.js, app/components/modal-delete-member.js
refs https://github.com/TryGhost/Ghost/issues/12256 , https://github.com/TryGhost/Ghost/issues/12255
Currently when listing subscriptions for Members, we only show the subscriptions which have a status of trialing or active.
Based on discussion, the `unpaid` and `past_due` states on Stripe also represent owner's intention of considering a subscription as active instead of `cancelled`, so we allow any subscriptions under these 2 states to be also listed for a member and consider them as `paid`.
- Subscriptions will go into a past_due state if the payment is missed, this should be considered a grace period where the member still has access.
- After this the subscriptions will either go to the unpaid or the cancelled state - this can be configured on an account by account basis in the Stripe …
=> Added `past_due` and `unpaid` subscriptions for members

app/components/gh-members-lab-setting.hbs
no refs
Removes Portal access from only behind a dedicated flag and allows all sites to access Portal settings in Admin
=> Enabled Portal settings for all sites

app/components/modal-email-design-settings.hbs, app/components/modal-email-design-settings.js, app/styles/layouts/members.css, lib/koenig-editor/addon/components/koenig-toolbar.js
no-issue
This allows users to use basic HTML to customise their newsletter
footer, meaning they can use links, and bold/italic text.
=> ✨ Added support for basic HTML newsletter footer

app/components/gh-portal-links.hbs, app/components/gh-portal-links.js
refs https://github.com/TryGhost/Ghost/issues/12365
Portal now allows direct checkout links for monthly/yearly plans via Portal links or data attributes, allowing members to directly signup to a paid plan. This PR adds -
- A new portal signup link for monthly plan - `/signup/monthly`
- A new portal signup link for yearly plan - `/signup/yearly`
=> ✨ Added new portal links for plan checkout

app/components/gh-portal-links.hbs, app/components/gh-portal-links.js
refs TryGhost/Ghost#12365
Portal allows direct free signup link or data attributes, allowing members to directly share or link to only free plan in Portal popup if available
- A new portal signup link for free plan - `/signup/free`
=> Added new portal link for free plan

app/components/gh-publishmenu.js
no refs
With last release, by default a post has newsletter sending option enabled by default based on default visibility. Since authors don't have permission to see or toggle the email newsletter options, if the newsletter was enabled for them the post publish failed as they lacked permissions to send newsletter. This patches the option by switching off newsletter option when publishing post as an author.
=> 🐛 Fixed authors failing to publish post with newsletters

app/components/gh-members-lab-setting.hbs, app/components/gh-members-lab-setting.js, app/models/setting.js
closes https://github.com/TryGhost/Ghost/issues/12390
requires https://github.com/TryGhost/Ghost/pull/12404
- Added toggle for open-tracking in settings (Labs > Members > Email section)
=> Added toggle in settings to enable open-tracking configuration

app/components/gh-posts-list-item.hbs, app/components/gh-posts-list-item.js, app/models/email.js, app/models/post.js, app/styles/layouts/content.css, app/templates/pages.hbs, app/templates/posts.hbs
No issue
- Added stats-related fields to the `Email` and `EmailRecipients` models
- Moved update time to entry-meta
- Got rid of email icons
- Added columns for recipients and opens
- Added tooltip on hovering scheduled state
- Changed column order on mobile
=> Changed post list layout to display email stats

app/controllers/signin.js
closes TryGhost/Ghost#12189
This bug happened because authenticate function always returned success(true) even when it is failed.
I intentionally didn't add tests because it can be flaky.
----
=> Remove spinner when login attempt failed

lib/koenig-editor/addon/components/koenig-basic-html-input.js
no issue
- Email design settings doesn't open in some cases when footer html is set as null, specifically on import
- Patches html cleanup to use empty string in case of null footer value
=> 🐛 Fixed email design settings not opening 

app/components/gh-members-filter.hbs, app/components/gh-members-list-item.hbs, app/controllers/members.js, app/helpers/feature.js, app/helpers/reset-query-params.js, app/models/member.js, app/routes/members.js, app/styles/layouts/members.css, app/templates/members.hbs
No-ref
- Created new column and prefilled it with static data
- Adjusted column width
- added "open rate" for each list item on mobile view
=> Added open-rate column to the members list

app/components/gh-member-activity-feed.hbs, app/components/gh-member-settings-form.hbs, app/styles/layouts/members.css, app/templates/member.hbs, tests/acceptance/members-test.js
No-ref
- Changed order to display feed at the bottom
- Displayed heading and value vertically between 1400px and 1160px
- Displayed "Complementary plan" copy and switch vertically between 1400px and 1160px
- Added margin below "Continue subscription" button
- Prevented date in feed to wrap
=> Fixed issues for member details mobile view

app/services/feature.js
closes TryGhost/Ghost#12396
We use two stylesheets ghost-light.css and ghost-dark.css for light mode and night mode respectively.
The problem occurs when we disable the light stylesheet when we enable dark stylesheet, as there is a moment when there is no style applied
This causes flash of unstyled content (or a big logo when users flip the night mode switch)
Since the ghost-dark style is loaded after the ghost-light stylesheet, we only need to enable or disable the dark stylesheet.
When the dark stylesheet is enabled, the light stylesheet will be overridden automatically by the browser.
I could not find any performance implications on overriding styles. The only performance implication is around loading a new stylesheet
which we already do.
Please include …
=> 🐛 Fixed flash of unstyled content appearing when toggling night mode

app/components/gh-member-settings-form.js, app/models/member.js, app/transforms/member-subscription.js
no issue
- The subscriptions data on member - `stripe.subscriptions` - is flattened to top level `subscriptions` with a new provider value to check for subscription provider
- Updates model to use the new data structure
- Updates serializer to handle new data structure
=> Updated usage of subscriptions data for members

app/components/gh-theme-table.hbs, app/components/modal-install-theme.hbs, app/components/modal-install-theme.js, app/components/modal-upload-theme.hbs, app/controllers/settings/theme/install.js, app/router.js, app/routes/settings/theme/install.js, app/styles/layouts/apps.css, app/styles/layouts/settings.css, app/styles/patterns/buttons.css, app/templates/settings/theme.hbs, app/templates/settings/theme/install.hbs, app/templates/settings/theme/uploadtheme.hbs, tests/acceptance/settings/theme-test.js
refs https://github.com/TryGhost/Ghost/issues/12608
- adds `/settings/themes/install` route with `source` and `ref` query params that match the API. Shows a confirmation modal when accessed asking to confirm installation and activation
- does not allow Casper to be installed
- warns if installing the theme will overwrite an existing one
=> Added ability to install free themes directly from GitHub

app/components/gh-billing-modal.hbs, app/components/gh-billing-modal.js, app/routes/billing.js, app/templates/application.hbs
no issue
The billing iFrame needs to be rendered within the `main` content area rather than as fullscreen.
This needs most probably more tidying up, but is working for now without breaking the functionality.
=> Move billing iFrame to render in main content area

app/components/gh-publishmenu.js, app/components/modal-confirm-email-send.js, app/controllers/members.js
no-issue
As members can now have a status of 'comped' as well as 'free'/'paid',
we need to update queries to the API to function as they were before.
=> Updated paid member filters to handle comped status

app/controllers/settings/labs.js, app/templates/settings/labs.hbs, tests/acceptance/settings/labs-test.js
ref TryGhost/Ghost#11085
ref TryGhost/Ghost#12187
This PR allows users to upload yaml format redirects files to the server.
=> Allow YAML file for redirects.

app/components/modal-base.js, app/components/modal-post-preview/social.hbs, app/components/modal-post-preview/social.js, app/styles/layouts/post-preview.css
refs https://github.com/TryGhost/Team/issues/482
- replace titles and descriptions with text fields when clicked
- save on blur
- blur+save on <kbd>Enter</kbd>
- blur+restore on <kbd>Escape</kbd>
- create newline with <kbd>Shift+Enter</kbd> in description fields
- if there's no available image or fallback show a "+ Add image" header in the previews when hovering
- if there is an image show an upload/change image button when hovering
- show a delete image button when hovering once a custom image has been uploaded
=> Made social/meta text and images in preview modal editable

app/components/gh-launch-wizard/set-pricing.js
refs https://github.com/TryGhost/Admin/commit/638e5027
We moved the definition of currencies to a utils file and this was
missed.
=> Fixed currencies for launch wizard

app/components/gh-billing-modal.hbs, app/components/gh-billing-modal.js, app/routes/billing.js, app/templates/application.hbs
refs https://github.com/TryGhost/Admin/pull/1838
refs https://github.com/TryGhost/Admin/pull/1859
Same changes needed to be done for 3.x
The billing iFrame needs to be rendered within the main content area rather than as fullscreen.
This needs most probably more tidying up, but is working for now without breaking the functionality.
Fixes a bug where the billing iframe would show a blank page when called directly and user is not logged in. This commit ensures to that we have a valid authenticated session and redirects to the signin page if not.
=> Billing iframe 3x

app/components/gh-members-payments-setting.js
no refs
For selected currency, we were only checking in the secondary currency list which does not include the top currencies like USD, so if the current selected currency is one of the top currencies, the `selectedCurrency` returned a value of `undefined`. The fix updates selected currency computation to check both top and other currencies
=> Fixed selected currency in payment settings

app/services/members-stats.js, tests/unit/services/member-stats-test.js
no refs
MRR start date value for charts was being calculated with start value as 0, assuming we have the data for first date in our range to use as start value. Since the events data returned only has data on dates where any MRR event happened, in case the first date in our range didn't have any. data we started from 0 instead of value on previous date. This fix
- adds calculation to pick the start value for chart based on value on last date in our range(30 days)
- adds unit tests for stats
=> 🐛 Fixed MRR start date value in chart

app/components/gh-nav-menu/main.hbs, app/routes/billing.js
no issue
- only owners can generate tokens to identify as the publication so the billing app won't work for non-owners
=> Fixed billing/update links showing for admins

app/components/gh-nav-menu.hbs, app/routes/billing.js, app/templates/application.hbs
no issue
- only users with the Owner role can generate tokens used to identify a publication so the links wouldn't function for Administrators
=> [3.x] Fixed broken billing and update links being shown to admins

app/components/modal-delete-member.js
refs https://github.com/TryGhost/Team/issues/546
Since https://github.com/TryGhost/Ghost/commit/26ee6483 and
https://github.com/TryGhost/Admin/commit/723269bc a members
subscriptions have not been on the `stripe` property.
This meant that all members were considered to not have subscriptions,
and so the modal would not display to option to cancel subscriptions.
=> 🐛 Fixed deleting members to prompt cancellation

app/controllers/application.js, app/templates/application.hbs, app/utils/color.js
refs https://github.com/TryGhost/Team/issues/551
refs https://github.com/TryGhost/Ghost/issues/12767#issuecomment-800177254
- calculate contrast color of accent color against light/dark mode background color
- lighten (dark mode) or darken (light mode) the accent color used in the editor to ensure it has enough contrast to be legible
=> 🐛 Fixed link contrast in editor with very light/dark accent colors

app/components/gh-billing-update-button.js, app/router.js, app/routes/pro.js, app/services/billing.js
no issue
The current `/billing` route needs to be renamed into `/pro`, so we can use sub-routes like `/pro/billing` and `/pro/domain` in the billing app.
Still left to do is to rename the billing service itself, but that can be done with another PR
=> Changed `/billing` route to `/pro`

app/controllers/signin.js
refs https://github.com/TryGhost/Team/issues/536
From 4.0, we ensure and require that accent colour is always set. This change removes hardcoded accent color fallbacks to avoid confusion as well as cause accidental fallback that is undesired causing themes to look different
=> Removed hardcoded accent color fallbacks

app/controllers/dashboard.js, app/services/members-stats.js
closes https://github.com/TryGhost/Team/issues/550
The MRR chart relied on first currency from the list in case of data for multiple currencies, falling back to USD in case of no MRR data for the site. This can be misleading, specially when the active currency set in payment settings is different from one picked to show on MRR chart.
The change updates dashboard to always pick the currency from Payment settings as default for showing chart data.
=> Updated default MRR currency from settings

app/components/gh-members-email-setting.js, app/controllers/settings/members-email.js
closes https://github.com/TryGhost/Team/issues/397
The default newsletter/support email address for a site is currently setup as noreply@DOMAIN , which means for a custom domain setup with www the email address becomes noreply@www.somesite.com which is not the expected behavior.
Note: This fix only removes `www` subdomain from addresses and no other subdomains
=> Removed www subdomain from default newsletter/support address

app/models/invite.js, tests/unit/models/invite-test.js
refs https://github.com/TryGhost/Team/issues/587
- It was not possible to invite a new Contributor to a site that has reached its limit
- This fix divides the resend invite action into two separate steps: 1. Deleting existing invite 2. Creating a new one for the same data
- It was hitting the limit because the permissions were correctly checking for "add" action being executed when the limit of invites/staff users was already used up. By removing existing invite we mimic the behavior the server would do for us anyway (https://github.com/TryGhost/Ghost/blob/2111992dd42cd9d9400eebea52006d023b4b19b3/core/server/services/invites/invites.js#L18-L22)
@rishabhgrg I struggled to figure out why the test for the invites was failing and not picking up the second request. I'm assuming the "run" block …
=>  🐛 Fixed host limit error when resending a pending invite

app/components/gh-members-filter.hbs, app/components/gh-members-list-item.hbs, app/components/modal-delete-members.hbs, app/components/modal-delete-members.js, app/controllers/members.js, app/templates/members.hbs, mirage/config/members.js, mirage/config/posts.js, mirage/factories/label.js, mirage/factories/member.js, mirage/models/label.js, mirage/serializers/label.js, mirage/utils.js, tests/acceptance/members-test.js
refs https://github.com/TryGhost/Team/issues/585
requires https://github.com/TryGhost/Ghost/pull/12082
When a label or status filter is selected on the members screen show a "Delete selected" option in the actions dropdown. Bulk deleted members will _not_ have any subscription data modified in Stripe, if a member should be deleted and have their subscription cancelled it's necessary to do that on a per-member basis.
- updated bulk delete handling to match API
- added link to bulk delete confirmation modal in members actions dropdown (only shown when label, status, or search is used)
- updated testing framework for members
- added label factory for easier test setup
- updated `GET /members` and `DEL /members` endpoints to work with label filters
- updated test selectors for easier …
=> ✨ Added ability to bulk delete members by label or status

app/controllers/settings/members-access.js, app/models/setting.js, app/styles/patterns/forms.css, app/templates/settings/members-access.hbs
refs https://github.com/TryGhost/Team/issues/579
requires https://github.com/TryGhost/Ghost/pull/12886
- renamed `membersAllowFreeSignup` to `membersSignupAccess` and changed type to match new setting
- added `membersAllowFreeSignup` computed property to map to the new setting to avoid having to migrate code elsewhere that will be removed once the new options are out of developer experiments
=> Updated setting model for new `members_signup_access` setting

app/components/gh-role-selection.js, app/components/modal-invite-new-user.hbs, app/components/modal-invite-new-user.js
no issue
- when the role selection was extracted to an external component the limit validation was also extracted but had no way of feeding back to the consumer
- added `onValidationSuccess` and `onValidationFailure` arguments to the role selection component to allow validation feedback to the consumer
- updated staff invite modal with actions to update state based on validation so the modal's buttons can update accordingly
=> Fixed invite staff modal button not reflecting validation state

app/components/modal-upgrade-custom-integrations-host-limit.hbs, app/components/modal-upgrade-custom-integrations-host-limit.js, app/controllers/integrations/new.js, app/routes/integrations/new.js, app/templates/integrations/new.hbs
refs https://github.com/TryGhost/Team/issues/599
- Previously user received genetic limit error after putting in integration name and clicking "create" button. This created a little frustrating experience.
- The updated flow does the check before loading the integration modal, so the user receives communication about needed upgrade before doing any work
@kevinansfield to detect when the limit on integrations is reached I've made integrations.new router return multiple models. Wasn't able to come up with any nicer solution, so was wondering if this is an ok solution or could be done nicer?  Also, would appreciate feedback on the rest of ember code I've added :raised_hands:
=> Added limit check before adding new integration

app/components/gh-member-settings-form-cp.js
refs https://github.com/TryGhost/Team/issues/660
We added a guard to not send price object in a subscription when the data is missing from DB. This can cause the member details page to fail with the missing price object, so this change adds a guard against subscriptions with missing price.
Note: This is only a short-term fix till we add a proper fix to cleanup the DB in the subsequent release.
=> Fixed member details not loading

app/components/gh-members-email-setting.hbs, app/components/gh-members-segment-count.hbs, app/components/gh-members-segment-count.js, app/components/gh-members-segment-select.hbs, app/components/gh-members-segment-select.js, app/components/gh-publishmenu-draft.hbs, app/components/gh-publishmenu-draft.js, app/components/gh-publishmenu-scheduled.hbs, app/components/gh-publishmenu-scheduled.js, app/components/gh-publishmenu.hbs, app/components/gh-publishmenu.js, app/components/gh-token-input/trigger.hbs, app/components/settings/default-email-recipients.hbs, app/components/settings/default-email-recipients.js, app/controllers/settings/members-access.js, app/controllers/settings/members-email.js, app/models/setting.js, app/services/settings.js, app/styles/components/power-select.css, app/templates/editor.hbs, app/templates/settings/members-email.hbs, app/transforms/members-segment-string.js
refs https://github.com/TryGhost/Team/issues/496
reqs https://github.com/TryGhost/Ghost/pull/12925
The publish menu was meant to default to matching post visibility but that wasn't working consistently and didn't make sense for sites which don't email every post to their members.
A "Default newsletter recipients" option has been added to the "Email newsletter" settings screen and the publish menu updated to reflect the option. The free/paid toggles in the publish menu have also been swapped out for a multi-select style component that will cater to more complex member segmentation.
=> ✨ Added default newsletter recipients setting

app/adapters/post.js, app/components/gh-members-segment-count.js, app/components/gh-members-segment-select.hbs, app/components/gh-members-segment-select.js, app/components/gh-publishmenu-draft.hbs, app/components/gh-publishmenu-draft.js, app/components/gh-publishmenu.hbs, app/components/gh-publishmenu.js, app/components/modal-confirm-email-send.hbs, app/components/settings/default-email-recipients.hbs, app/components/settings/default-email-recipients.js, app/models/post.js, app/styles/components/power-select.css, app/templates/editor.hbs
refs https://github.com/TryGhost/Team/issues/581
requires https://github.com/TryGhost/Team/issues/12932
- added segment option and select to default newsletter recipients setting
- updated segment selector to fetch labels/products and show as options
- updated segment selector and count component to call an action when count changes so we can use it in the email confirmation modal
- removed usage and mapping of older `'none'`, `'all'`, `'free'`, and `'paid'` email recipient filter values
=> ✨ Added label and product options for email recipients

app/components/gh-members-recipient-select.hbs, app/components/gh-members-recipient-select.js, app/components/gh-publishmenu-draft.hbs, app/components/gh-publishmenu-scheduled.hbs, app/components/gh-publishmenu.hbs, app/components/gh-publishmenu.js, app/services/members-utils.js, app/styles/components/power-select.css, app/styles/components/publishmenu.css, app/styles/patterns/forms.css, app/utils/flatten-grouped-options.js, package.json, yarn.lock
no issue
Free and Paid are by far the two most common options for email recipients so it makes more sense to have them as very clear options which we felt was not the case with the single token/segment select.
- created a new `<GhMembersRecipientSelect>` component that has individual checkboxes for free/paid/segment and when segment is selected an additional token input for specific labels
- updated draft and scheduled publish menu components to use the `<GhMembersRecipientSelect>`
=> Brought checkboxes back to publish menu recipient selection

app/components/gh-launch-wizard/connect-stripe.js, app/components/gh-members-payments-setting.js, app/components/gh-post-settings-menu/email.js
no refs
We try and create new default prices soon after Stripe Connect is completed, but it might take couple of seconds for backend to have Stripe config ready and in the meanwhile saving a product with new prices will fail with 409 Conflict error as it will be unable to create prices on Stripe. This change allows re-attempting saving a product with new prices soon after connect in case of a STRIPE_NOT_CONFIGURED error so that the default prices can be created properly.
=> Handled product save failure on Stripe connect

app/components/gh-site-iframe.hbs, app/components/gh-site-iframe.js, app/components/modal-portal-settings.hbs, app/templates/settings/membership.hbs
refs https://github.com/TryGhost/Team/issues/701
requires Portal@1.4.2 or later
- changed `<GhSiteIframe @invisibleUntilLoaded>` to accept a string in place of a `true/false` value
- if a string is passed then we'll set up a message event listener than listens for a `postMessage` from the iframe with data that matches the supplied string
- updated `<GhSiteIframe>` usage for portal previews to use `@invisibleUntilLoaded="portal-ready"` so they listen for a message event rather than displaying as soon as we get a load event
=> Fixed portal previews flashing background

app/components/gh-site-iframe.hbs, app/controllers/settings/membership.js, app/styles/layouts/settings.css
no issue
- add CSS transition for height attribute of portal preview container
- before adjusting height of container, apply styles to portal preview nested iframe to prevent scrollbars from showing
=> Added animation to portal preview height

app/components/gh-site-iframe.hbs, app/components/gh-site-iframe.js, app/controllers/settings/membership.js, app/templates/settings/membership.hbs
no issue
- switched to listening to Portal's `message` events that now include a height
- removes need to reach into Portal preview iframe contents which is blocked by browser security when working cross-origin
=> 🐛 Fixed portal preview resize when using split front-end/admin URLs

app/components/gh-member-settings-form-cp.js
refs https://github.com/TryGhost/Ghost/commit/81de2fe223e47255899523a113b63b1423c2de14
refs https://github.com/TryGhost/Team/issues/758
The "Add complimentary" subscription button in members does not show up when members already have an existing zero amount subscription. But this was incorrectly not taking into account active subscriptions and was applying the rule to canceled subscriptions. Since the `comped` behaviour changed in 4.6 which caused member's existing comp subscription to be canceled, this bug did not allow the comped subscription to be added back.
=> 🐛 Fixed missing complimentary subscription add button

app/components/gh-koenig-editor.hbs, app/components/gh-post-settings-menu-labs.hbs, app/components/gh-post-settings-menu.hbs, app/services/feature.js, app/templates/settings/labs.hbs
refs https://github.com/TryGhost/Team/issues/839
The feature image uploader in the post settings menu did not lend itself well to having additional fields so we've moved it into the main editor canvas. This allowed us to use the familiar caption/alt fields from image cards and to let the feature image feel more connected to the post's contents and part of the editing workflow.
---
- removed `featureImageMeta` labs flag
=> ✨ Added post feature image alt and caption support to editor

app/components/gh-members-segment-select.js, app/components/gh-post-settings-menu.hbs, app/components/gh-post-settings-menu.js, app/components/gh-psm-visibility-input.js, app/components/settings/members-default-post-access.hbs, app/components/settings/members-default-post-access.js, app/controllers/settings/membership.js, app/models/post.js, app/serializers/post.js, app/validators/post.js, tests/integration/components/gh-psm-visibility-input-test.js
With multiple products we'll re-enable segmentation by product for posts, which also means we need to add a new option to the default post access setting in Membership settings. This PR handles the new segment for post access behind flag on both post settings and membership settings.
Note: PR is waiting on successful tests for merge
=> Handle new visibility filter changes for post access

app/controllers/members.js
no refs
- removes empty filter param from url to avoid showing empty params on url
Note: PR to fix failing members list tests, will merge on ✔️
=> Removed empty filter param on members list

app/controllers/members.js
Fixes minor typos in members list code -
- Fixed created_at filter not applied on members list query
- Fixed incorrect order param comparison in force reload
=> Minor typo fixes in members list filtering and query

app/serializers/page.js
refs https://github.com/TryGhost/Team/issues/998
- posts have a new `email_only` property for an alpha feature but that is not a valid property for pages
- our pages model and serializers currently inherit from the post model/serializer so when saving the new property is triggering a "no additional properties" validation error
- updating the pages serializer to remove the new property means the pages add/edit API requests are valid again
=> 🐛 Fixed validation error when saving pages in admin area

app/components/gh-distribution-action-select.hbs, app/components/gh-distribution-action-select.js, app/components/gh-post-settings-menu.hbs, app/components/gh-post-settings-menu.js, app/components/gh-publishmenu-draft.hbs, app/components/gh-publishmenu-draft.js, tests/integration/components/gh-distribution-action-select-test.js
refs https://github.com/TryGhost/Team/issues/947
The PR aims to implement following design to allow the end user selecting the "distribution" option:
@kevinansfield there are couple places I've got stuck with the changes after multiple different approach. Would love your expert help :)
Below are related to changes introduced in `Added publishing action dropdown to publish menu ` commit:
1. The basic test I've tried covering the new component with is failing due to "post" not being an ember model object :thinking: I've taken the pattern from [gh-psm-tags-input-test.js](https://github.com/TryGhost/Admin/blob/faabc6018b01d7839f4b7d98fa3e66442978ae4f/tests/integration/components/gh-psm-tags-input-test.js#L83) test and it doesn't seem to work? Is there a correct pattern to follow when mocking …
=> Moved email-only selector to post publish menu

app/components/modal-post-preview/email.hbs, app/components/modal-post-preview/email.js, app/services/feature.js, app/styles/layouts/editor.css, app/templates/settings/labs.hbs, lib/koenig-editor/addon/components/koenig-card-email-cta.hbs, lib/koenig-editor/addon/options/cards.js
refs https://github.com/TryGhost/Team/issues/993
The new editor card allows you to add styled content along with an optional button that will only be visible to free or paid members when the post is emailed. Useful for encouraging free members to sign up to a paid account for example.
- removed labs flag and conditionals to make the feature is available by default
- cleaned up CSS that re-used the `.email-card` class or was referencing `labs`
=> ✨ Added "Email call to action" card for an email-only CTA targeting free or paid members

app/components/gh-member-settings-form-cp.hbs, app/components/gh-member-settings-form-cp.js
refs https://github.com/TryGhost/Team/issues/873
When we updated the UI to handle the default subscriptions for
Complimentary subscriptions, we didn't update it to use any of the data.
This updates the UI to share as much as possible for the display of
subscriptions information, and only diverges for the menus which have
different actions based on complimentary or not.
This should ensure that we keep the UI in sync for both types of Member.
=> Showed created at dates for complimentary subscriptions

app/components/modals/design/customize.hbs, app/components/modals/design/customize.js, app/components/modals/design/customize/theme-settings.hbs, app/models/custom-theme-setting.js
refs https://github.com/TryGhost/Team/issues/1070
reqs https://github.com/TryGhost/Ghost/pull/13362
- added custom theme setting model
- added fetch of custom theme settings when customize modal is opened
- used loaded theme settings to populate settings list in theme settings tab
- hid the general/theme toggle when no theme settings are present
=> Wired up custom theme settings display

app/adapters/custom-theme-setting-list.js, app/components/custom-theme-settings/select.hbs, app/components/custom-theme-settings/select.js, app/components/modals/design/customize.js, app/components/modals/design/customize/theme-settings.hbs, app/controllers/settings/design/customize.js, app/models/custom-theme-setting-list.js, app/routes/settings/design/customize.js, app/serializers/custom-theme-setting-list.js, app/services/custom-theme-settings.js
refs https://github.com/TryGhost/Team/issues/1070
- adds a `customThemeSettings` service that handles overall setting loading and saving to avoid components having to know any of the intricacies of the model setup
- adds `custom-theme-setting-list` model so that we can save multiple setting records as embedded relations
- custom adapter ensures requests go to the `/custom_theme_settings` base route as a `PUT` request
- custom serializer drops the default `models: []` wrapper in the request data so the format matches the `PUT /settings` endpoint
=> Added save of custom settings from customize design screen

app/controllers/editor.js
refs https://linear.app/tryghost/issue/CORE-79/editing-saving-a-post-that-has-already-been-sent-flashes-sent-as-the
- The mapping was wong in a previous version - when the status changes from 'sent' to 'sent' the notification box should show 'Updated' instead of 'sent', doh!
=> Fixed incorrect status showing up when sent post is updated

app/components/gh-launch-wizard/finalise.js, app/controllers/dashboard.js, app/models/setting.js, app/templates/dashboard.hbs
refs https://github.com/TryGhost/Team/issues/807
refs https://github.com/TryGhost/Ghost/pull/13703
The launch wizard completed flag was previously stored at per user level in accessibility column of user table, so an administrator still got the option to complete the launch wizard even if the owner had completed it previously, which is not expected pattern. This change moves the launch complete flag to be stored in new global setting for a site.
=> Moved launch complete flag to new setting

app/styles/layouts/settings.css
closes https://github.com/TryGhost/Ghost/issues/13598
- dark mode was showing incorrect colours for dropdown
=> :bug: Currency dropdown had incorrect background shade in dark mode

app/styles/components/koenig.css, lib/koenig-editor/addon/components/koenig-editor.hbs, lib/koenig-editor/addon/components/koenig-editor.js, lib/koenig-editor/addon/components/koenig-media-selector-tenor.hbs, lib/koenig-editor/addon/components/koenig-media-selector-tenor.js, lib/koenig-editor/addon/components/koenig-media-selector.hbs, lib/koenig-editor/addon/components/koenig-media-selector.js, lib/koenig-editor/addon/components/koenig-plus-menu.js, lib/koenig-editor/addon/components/koenig-slash-menu.js, lib/koenig-editor/addon/options/cards.js, lib/koenig-editor/app/components/koenig-media-selector-tenor.js, lib/koenig-editor/app/components/koenig-media-selector.js
refs https://github.com/TryGhost/Team/issues/1225
Re-using the existing pattern of creating an image card and having it launch an image selector was proving to have a lot of edge cases when we wanted a more streamlined in-line image selector for gifs.
- added a new `'selector'` type to card definitions
- requires a `selectorComponent` argument that is the name of a component that renders the media and handles search
- updated card components to open the selector component when respective menu item is activated
- updated slash menu to instantly trigger the selector component when the slash command matches a card and is followed by a space so that searches continue inside the selector
- added `<KoenigMediaSelector>` component that wraps the card-definition provided component and handles …
=> Added media selector pattern to editor and used it for gifs

app/services/feature.js
no-issue
We now calculate whether or not a flag is enabled on the server, so this
extra check is redundant. It also means that when we promote a flag to
GA on the server this check will still take places, meaning that we need
to make two commits to promote a flag to GA.
=> Removed development option from feature helper

lib/koenig-editor/addon/components/koenig-basic-html-input.js, lib/koenig-editor/addon/components/koenig-card-toggle.hbs, lib/koenig-editor/addon/components/koenig-card-toggle.js
refs https://github.com/TryGhost/Team/issues/1209
- allows switching to content input from heading by pressing tab
=> Allowed tab switch for heading to content input in toggle card

app/components/modals/post-preview/email.hbs
refs https://github.com/TryGhost/Team/issues/1001
Our email newsletter preview is rendered inside of an iframe with
javascript disabled. When opening links from the preview, the new
window/tab inherits this property - which breaks links to twitter.
=> Allowed popups from email preview to escape sandbox

app/templates/settings/membership.hbs
Creators on Ghost have surpassed $12 million in revenue per year. We're updating the membership settings page to reflect that.
=> Updating revenue number in membership settings

app/controllers/whatsnew.js, app/templates/whatsnew.hbs
refs https://github.com/TryGhost/Toolbox/issues/175
refs https://github.com/TryGhost/Admin/commit/cf78595b1d97c7ce79c0570a42603bcfac803998
- the referenced commit added a warning message to the What's New page
to notify the user that we're going to be requiring MySQL 8 in
production as of v5
- this would also show if the user was already using MySQL 8, which
isn't ideal
- I've added a library to Ghost which will return the specific version
of MySQL used, so we can now detect that
- https://github.com/TryGhost/Ghost/commit/eb68e8d339ae447eafd9aa48d957a607252f7e4f has updated the config endpoint to return `mysql5`, `mysql8` etc,
so we can now change the logic here to reflect that
- this commit also adds another warning if we're in development mode and
using mysql5, as this will not be …
=> Refined database warning message to reflect specific versions

app/components/gh-post-settings-menu.hbs, app/components/gh-post-settings-menu.js, app/components/gh-post-settings-menu/visibility-segment-select.hbs, app/components/gh-post-settings-menu/visibility-segment-select.js, app/components/gh-psm-visibility-input.js, app/components/gh-publishmenu.js, app/controllers/editor.js, app/models/post.js, app/serializers/page.js, app/serializers/post.js, app/validators/post.js, tests/integration/components/gh-psm-visibility-input-test.js
refs TryGhost/Team#1071
Specific tier visibility for a post was previously stored in `visibility` column directly, which had a limitation of 50 charts. Going forward, for the specific tiers visibility of post/page, we use `tiers` array in API that contains list of tiers with access for post. This change -
- replaces `filter` type to `tiers` for visibility
- adds new visibility filter segment component in post settings menu which stores array of tiers instead of nql string for visibility
- updates serializer and model for post/page
- updates tests
=> Updated specific tier visibility handling for posts/pages

app/styles/layouts/dashboard.css
Currently, `.gh-dashboard-chart-box` uses `vw` unit which is dependent from the viewport width. This causes overflow issue when the screen width is very wide. This PR removes the `vw` based width, and makes it dependent from the container width, so that it fills the remaining space correctly.
=> Fix dashboard chart width on wide screens

app/helpers/gravatar.js, app/helpers/members-event-filter.js
A continuation of #2227 that runs the native classes codemod against app/helpers.
This one was really easy, all the of the helpers are already converted!
=> [chore] runs native classes codemod for apps/helpers

app/components/gh-publishmenu.hbs, app/styles/app-dark.css
Ref Issue: [#13700](https://github.com/TryGhost/Ghost/issues/13700)
I've looked into this issue and its because of conflicting CSS styling rules on hover for the two classes associated with the button `gh-btn-black` and `gh-publishmenu-button`:
```
.gh-btn-black:not(.gh-btn-green):not(.gh-btn-blue):not(.gh-btn-red):hover,
.gh-btn-primary:not(.gh-btn-green):not(.gh-btn-blue):not(.gh-btn-red):hover {
background: var(--black) !important;
}
.gh-publishmenu-button:hover {
color: #fff;
background: var(--green) !important; --> This is ignored
}
```
Removed conflicting gh-publishmenu-button CSS styling rules
=> Fix incorrect color on hover for publish and send buttons

app/serializers/application.js, app/serializers/page.js, app/serializers/setting.js, app/serializers/theme.js
A continuation of #2227 that runs the native classes codemod against app/serializers.
Most of the serializers that are trying to be transformed are failing with the same issue:
```
Validation errors: 
[attrs]: Transform not supported - value is of type object. For more details: eslint-plugin-ember/avoid-leaking-state-in-ember-objects
2022-02-02T05:54:58.571Z [warn] [app/serializers/role.js]: FAILURE 
```
=> [chore] runs native classes codemod for apps/serializers

app/components/gh-launch-wizard/finalise.js, app/components/gh-launch-wizard/set-pricing.js, app/components/gh-members-payments-setting.js, app/components/modal-product.js, app/controllers/settings/membership.js, app/serializers/product.js
refs https://github.com/TryGhost/Team/issues/1319
Due to how JS implements numbers, it's possible that when we multiple a number with 2 decimal places by 100 that we do not end up with an integer e.g. 9.95 * 100 = 994.999...
This is not a valid price for the API and so we must round it to the nearest integer. We round off prices both at source as well as in ties serializer to make sure we never send non integer prices to API.
=> 🐛 Fixed sending non-integer prices to tiers api

app/components/modal-product.js, tests/acceptance/settings/membership-test.js
refs https://github.com/TryGhost/Team/issues/1188
- The api throws a validation error when we try to add benefits with an empty name
- Before saving, we remove benefits with an empty name
=> 🐛 Remove empty benefits before saving

app/components/gh-date-picker.hbs, app/components/gh-date-picker.js, app/components/members/filter-value.hbs, app/styles/components/power-calendar.css, tests/integration/components/gh-date-picker-test.js
refs https://github.com/TryGhost/Team/issues/1410
- added block invocation support to `<GhDatePicker>` that exposes the calendar components used inside the datepicker dropdown allowing for customisation of the dropdown content
- updated "last seen" datepicker to use the block invocation support to add buttons that select typical "time ago" dates
=> Added shortcut buttons to "Last seen" members filter datepicker

app/components/gh-launch-wizard/connect-stripe.js, app/components/gh-members-payments-setting.js, app/components/modal-portal-settings.js, app/models/product.js, app/services/members-utils.js
refs https://github.com/TryGhost/Team/issues/1387
This will allow us to move from the portal_products and portal_plans settings to using the visibility property on tiers to determine whether or not a tier should be visible in Portal. This updates admin to handle tier visibility property based on changes in settings. Old portal settings update is temporarily kept in though will not be used for determining visibility going forward. Also removes default product visibility being set on stripe connect.
=> Added tier visibility handling from portal settings

.lint-todo, app/templates/settings/labs.hbs
Multiple tiers is going GA, so there is no need anymore for the beta section to enable it.
=> Removed tiers beta section

app/components/gh-member-settings-form.js, tests/acceptance/members/details-test.js
refs https://github.com/TryGhost/Team/issues/1435
refs https://github.com/TryGhost/Admin/commit/f5f69d01b16cc2ed6c523258cdc47a818da71cd1
A recent change for showing all subscriptions of a member on detail screen introduced a circular json structure with subscription -> tiers -> subscriptions, which throws an error on saving any member with paid subscription on member detail screen.
=> 🐛 Fixed error on saving a paid member

.github/workflows/test.yml
Currently the CI doesn't run in the new `multiple-newsletters` branch.
=> Added `multiple-newsletters` branch to CI trigger

app/components/gh-member-settings-form.hbs, app/components/gh-member-settings-form.js, app/components/settings/members-email-labs/newsletter-management.hbs
refs https://github.com/TryGhost/Team/issues/1554
With multiple newsletters, the subscribed property on a member is replaced by newsletter(s) [] which defines member's subscription instead. This change -
- updates the existing subscription toggle for member on detail screen to work with new backend
- shows the new multiple newsletter subscription UI only if site has more than 1 newsletters
=> Wired member newsletter subscription to existing toggle 

app/components/gh-post-settings-menu/email.js, app/components/modals/email-preview.js, app/components/modals/post-preview/email.js
=> Renamed `/email_preview` endpoint to `/email_previews`

app/router.js, mirage/config/newsletters.js, tests/acceptance/settings/members-email-labs-test.js
- updates newsletter settings route to `/settings/newsletters` for GA
=> Updated route for newsletter settings

.template-lintrc.js, app/components/gh-publishmenu-scheduled.hbs, app/components/gh-publishmenu-scheduled.js, app/components/gh-publishmenu.hbs, app/models/post.js
no issue
If you scheduled a post to a specific newsletter it was no longer visible in the scheduled state of the publish menu making it difficult to know the behaviour when coming back to a scheduled post.
- duplicated the newsletter dropdown from the draft to the scheduled state components and disabled it the same as the other recipient options
- added temporary workaround for missing newsletter embed for the posts endpoint in the API
- adds `newsletterId` attribute to the post model
- uses `post.newsletterId` to find the matching newsletter model from the available newsletters list
=> Added disabled newsletter dropdown to scheduled state of publish menu

app/services/dashboard-stats.js
The exit clause of the mergeDates function should return an array rather
than an object, to ensure that an array is always returned. Because we
are using the concat method when recursing, this continues to work for
longer lists.
=> Fixed mergeDates when only one item in list

app/adapters/post.js, app/components/editor-labs/modals/update-flow.hbs, app/components/gh-editor-post-status.hbs, app/components/gh-posts-list-item.hbs, app/components/gh-posts-list-item.js, app/components/gh-publishmenu.js, app/controllers/editor.js, app/models/post.js, app/utils/publish-options.js
refs https://github.com/TryGhost/Team/issues/1596
This PR updates admin to align with the changes in the backend in https://github.com/TryGhost/Ghost/pull/14798 (not yet merged)
- `post.email_recipient_filter` option and property is renamed to `email_segment`
- `newsletter_id` option is renamed to `newsletter` (and now uses slug instead of id)
- Sending a post via email, means you need to set the `newsletter` option. The `email_segment` option is optional now and defaults to `all`. Not setting `newsletter` means not sending an email, setting `email_segment` is ignored if `newsletter` is missing.
- We can no longer use `email_recipient_filter` (now renamed to `email_segment`) to know whether a post is published/scheduled to be sent as an email. We need to rely on the newsletter relation …
=> Updated publishing with renamed newsletter and email_segment options

app/components/modals/newsletters/new.js
refs https://github.com/TryGhost/Team/issues/1634
- member count on newsletter may not be immediately updated on saving newsletter
- api returns `opted_in_member_count` in response to adding newsletter which admin cannot use atm
- re-fetches newsletters on save so all newsletters get updated member and post counts
=> Fixed subscribe count on adding new newsletter

app/components/gh-post-bookmark.hbs, app/helpers/get-setting.js, app/styles/components/publishmenu.css
no issue
- adds `{{get-setting "key"}}` helper to make settings available in templates without needing a backing class
- updated `<GhPostBookmark>` component
- if post feature image isn't present, fall back to site cover image
- add site icon (if present) and title to the details line
=> Added image fallback and site icon/title to `<GhPostBookmark>`

app/components/editor/modals/publish-flow/confirm.hbs, app/components/editor/modals/publish-flow/confirm.js
refs https://github.com/TryGhost/Admin/commit/d81d3c9d5a4ce3b5e938af25aa45d9ccf40e191b
- keeps text and logic together, avoids duplication of button code just for changing the running/success text
- added a `buttonTextMap` to keep the high-level text states in one place
- added `publishType` getter for easier switching between states in other getters and to have one place for the logic
- updated `confirmButtonText` getter and added `confirmRunningText` and `confirmSuccessText` getters that read from the button text map so the pattern used for getting text to pass as arguments in the template is consistent
=> Moved logic for publish confirm button text states into backing class

app/services/notifications.js, tests/unit/services/notifications-test.js
refs https://github.com/TryGhost/Team/issues/1613
We use `notifications.showAPIError()` in many of our try/catch routines but those can also pick up standard JS errors which can result in ugly and useless messages showing in alerts.
- added a list of known built-in JS error type names to check against and a generic error message to be used in place of ones we know shouldn't be displayed
- in `showAPIError(obj)` check `obj.name` against the known list and swap the message for a generic one
- only the message is swapped, we still log the full/original error to Sentry
- in `handleNotification(msg)` which is the final method used when displaying any alert/notification, extract all words in the supplied message and check that against the known list and swap the message on a match. This handles …
=> Fixed raw JS error messages appearing in alerts

app/components/gh-image-uploader.js, app/styles/layouts/main.css
refs TryGhost/Team#1652
> **Warning**
> Requires https://github.com/TryGhost/Ghost/pull/14918
- Support picking new image types in the favicon image uploader.
- Added support for non-square and not resizable files (e.g., svg files) as favicon (cover background image).
=> 🎨 Reduced favicon requirements

app/components/editor/modals/update-flow.hbs, app/components/editor/publish-buttons.hbs, app/components/editor/publish-management.hbs, app/components/gh-editor-post-status.hbs, app/styles/app-dark.css, app/styles/layouts/editor.css, app/templates/editor.hbs
no issue
- renamed "Update" to "Unpublish" or "Unschedule" to match the available actions
- renamed "Save" to "Update" and made it always visible but disabled when there are no unsaved changes
=> 🎨 Improved save/update button copy in editor

app/components/editor/publish-options/publish-at.hbs, app/components/editor/publish-options/publish-at.js, app/components/gh-date-time-picker.js
no issue
- in sites with a timezone that is negatively offset from UTC at certain times of day when the equivalent UTC date would be the next day, selecting a date when scheduling a post would select a day before the selected date
- fixed the date adjustment when applying the selected date to properly take timezones into account
=> 🐛 Fixed scheduled post datepicker sometimes picking day before selected date

app/components/dashboard/charts/paid-breakdown.js, app/services/dashboard-stats.js
refs https://github.com/TryGhost/Team/issues/1673
When a user switches plan, the paid subscribers delta chart on the dashboard displays the change as a cancellation plus a new subscription. This display is misleading and confusing - instead, plan changes should be excluded from the paid subscribers delta chart.
Awaiting https://github.com/TryGhost/Ghost/pull/15023
=> 🐛 Excluded plan changes from paid subscribers graph in dashboard

app/templates/whatsnew.hbs
When Ghost has an available update, the message we see provides a link to the release on Github for that version. If there is no update available, it would be nice if the version still linked to the relevant release on Github. I often find myself checking the release page out a couple of times each release, to see what has been updated, fixed, added etc... so this is a more convenient way of getting to that page.
=> 🎨 add link to github release for current version

app/components/modal-portal-settings.hbs, app/components/modal-portal-settings.js, app/components/modals/settings/confirm-email.hbs, app/components/modals/settings/verify-email.hbs, app/components/modals/settings/verify-email.js, app/controllers/settings/membership.js, app/models/setting.js, app/routes/settings/membership.js, app/serializers/setting.js
refs https://github.com/TryGhost/Team/issues/584
- No longer uses a API URL + redirect inside verification emails. This is replaced by a new route (`/settings/members/?verifyEmail=token`) that does the API request and shows a modal.
- Removed update button when changing support email address in the Portal settings
- Added `_meta` attribute to settings (uses same pattern as newsletters model)
- When updating the `membersSupportAddress` setting (via the normal edit endpoint), the `sent_email_verification` meta property will get set by the API. When this new property is present, we'll show a warning that the support address requires verification.
=> Updated support email address confirmation flow

app/styles/components/koenig.css, lib/koenig-editor/addon/components/koenig-plus-menu.hbs
Fix the right positioning and size of the icon for mobile display
Addresses https://github.com/TryGhost/Ghost/issues/14948
I also adjusted the breakpoint at 500px to match the rest of the styles in the file.
Below are a couple of example screenshots, of the button before/after clicking. One from the browser responsive view, the other in iOS Safari.
=> Put plus menu button on the screen on mobile

app/controllers/explore.js, app/router.js, app/routes/explore.js, app/styles/app.css, app/styles/layouts/explore.css, app/templates/explore.hbs, tests/unit/routes/explore-test.js
needs https://github.com/TryGhost/Ghost/pull/15103
no issue
- Added `/explore` route which requires min. Admin and is behind a feature flag
- Fetches Admin API key and ID to create a token and return back to Ghost Explore with the correct query params
- Fullscreen UI
=> Ghost Explore integration

app/styles/layouts/main.css, app/styles/layouts/settings.css
No issue
- Fixes the horizontal overflow caused my longer warning/error messages. This means the `<pre>` tag is sized to fit the container and can now be scrolled and read in its entirety.
- Adds some top margin so these errors are not so bunched up to the text & input.
Before:
After:
=> Fixed display of warnings after content import

app/index.html, config/environment.js, ember-cli-build.js, lib/asset-delivery/index.js, lib/koenig-editor/package.json, package.json, yarn.lock
I followed the guide https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md to update properly.
This should fix https://github.com/TryGhost/Admin/pull/1965 and also help us bump other major versions of deps that are using ember-auto-import@2.
=> [chore] update ember-auto-import@1 -> ember-auto-import@2

app/controllers/member.js, app/routes/member.js
refs/closes [Ghost/#12214](https://github.com/TryGhost/Ghost/issues/12214)
Previously, when navigating back from the members page with the
impersonate modal open, opening a new member showed the impersonate modal.
=> Close impersonate modal when navigating away from members page

app/components/gh-token-input.js, app/mixins/shortcuts.js, app/utils/shortcuts.js
Closes TryGhost/Ghost#12294.
Cache registered shortcuts and check KeyboardEvent before dispatching event to the root.
Fixed the bug introduced with TryGhost/Ghost-Admin#1707.
I wish there were a way to test ctrl+v event. But unfortunately, native events are not executed by triggering event in the acceptance tests.
----
=> Dispatch event to root only if the key combo is registered as shortcut

app/controllers/explore.js, app/styles/layouts/explore.css
no issue
- The `adminKey.secret` property is already in the correct format of `admiKey.Id:adminKey.secret` so we were returning the id twice as query param
- Minor style adjustments for Explore
=> Fixed using the correct token for Explore
