- .jshintrc
- .travis.yml
- Gruntfile.js
- package.json
- tests/.jshintrc
refs #23
- add `grunt lint`
- add lint build to Travis matrix
> Add Gruntfile.js, setup linting task and Travis build

- README.md
> add travis build status to readme

- app/components/gh-tag-settings-form.js
- app/components/gh-tag.js
- app/controllers/posts.js
- app/mirage/factories/tag.js
- app/mirage/fixtures/settings.js
- app/models/post.js
- app/models/tag.js
- app/services/feature.js
- app/templates/components/gh-tag.hbs
- app/templates/posts.hbs
- app/templates/settings/labs.hbs
- tests/acceptance/settings/tags-test.js
refs TryGhost/Ghost#6165
- change behavior to use 'visibility' property
- add tests
> internal tags feature

- app/controllers/posts.js
- app/models/post.js
closes https://github.com/TryGhost/Ghost/issues/7002
- move sorting logic out of the controller and into the Post model
This is a quick attempt at implementing the refactoring referenced in https://github.com/TryGhost/Ghost/issues/7002. The client-side sorting is working but we still have the problem of scheduled posts not appearing in the list until you scroll to the very first published post because the server is [returning posts in the wrong order](https://github.com/TryGhost/Ghost/issues/6932).
> Use Ember.Comparable mixin to sort posts

- .travis.yml
- Gruntfile.js
- package.json
refs TryGhost/Ghost#6977
- move buildAboutPage task to client gruntfile
> Grunt buildAboutPage tooling

- package.json
no issue
- update moment manually because greenkeeper didn't pick it up for some reason
> deps: moment@2.14.1

- app/controllers/about.js
- app/controllers/application.js
- app/controllers/error.js
- app/controllers/post-settings-menu.js
- app/controllers/posts.js
- app/controllers/reset.js
- app/controllers/setup.js
- app/controllers/setup/three.js
- app/controllers/setup/two.js
- app/controllers/signin.js
- app/controllers/signup.js
- app/controllers/subscribers.js
- app/controllers/team/index.js
- app/controllers/team/user.js
refs #101, #95
- shim controllers that were missed initially
> More Shimming of Controllers

- app/components/gh-ed-preview.js
- app/components/gh-image-uploader.js
- app/templates/components/gh-ed-preview.hbs
- app/templates/components/gh-image-uploader.hbs
- app/templates/components/modals/upload-image.hbs
- tests/integration/components/gh-image-uploader-test.js
closes TryGhost/Ghost#7064
- pull alt text from parsed markdown
- move text to image uploader component proper
> Fix image component displaying alt text in uploader

- app/mixins/editor-base-route.js
- app/mixins/shortcuts-route.js
- app/mixins/shortcuts.js
Zen styling doesn't apply anymore after the Zelda rewrite
> Remove Zen Styling

- Gruntfile.js
- package.json
refs TryGhost/Ghost#6977
(forgot to include this with the other PR 😁 )
> Move csscomb watch task from server repo

- app/components/gh-navitem-url-input.js
Closes TryGhost/Ghost#7140
* Now checks to see if it is new or not before editing the url
> Fix new url field focus bug

- app/styles/components/power-select.css
- app/styles/layouts/main.css
- Fix positioning bug introduced in #211
- Adjust search results max-height to be based on viewport height
> Minor visual bug fixes

- app/index.html
> remove google font loading from index.html

- app/components/modals/delete-user.js
- app/mirage/config/users.js
- app/templates/team/user.hbs
- tests/acceptance/team-test.js
closes https://github.com/TryGhost/Ghost/issues/7136
- pass user into the modal when displaying
- fix the user->model alias in the modal component
- update mirage user endpoints to respect `?include=count.posts` param
TODO:
> 🐛 fix highlighted number of posts when deleting a user

- app/components/modals/upload-theme.js
- app/controllers/settings/labs.js
refs TryGhost/Ghost#7292, TryGhost/Ghost#7293
- add 'application/x-zip-compressed' to allowed mime-types for import
and theme
> Allow windows zip type to be uploaded

- app/components/gh-file-uploader.js
- app/controllers/settings/labs.js
closes TryGhost/Ghost#7295
- check json content on db import if type is not specified
- ensure file type/extension is being checked in subscriber upload
> Fix json db uploads and add checking for subscriber uploads

- app/components/gh-search-input/trigger.js
closes TryGhost/Ghost#7369
- temporary fix for spacebar selecting until eps 1.0 is finalized
> 🐛 fix typing a space in search input

- package.json
no issue
- fixes missing dependency issues, temporarily points at git repo until version can be published on npm
> deps: ghost-editor@0.0.7

- package.json
👋 the new Ghost editor now includes draggable cards (or one card, a simple embed HTML card). We're a little behind schedule, but other parts are ahead so everything ⚖ 
Refs #7429
Depends on TryGhost/Ghost/pull/7474
This release includes:
- Ghost Editor, this is required to get access to the built in cards
Ghost Editor includes:
- Responsive toolbars 🔨 🔧 
- Both Ember and Plain javascript cards 🎴 
- An embeded HTML card ✍️ 
This is still an early release, but things are moving in the right direction. :)
We're still defining the spec for the UI, so expect drastic changes over the next couple of weeks.
This is going to be a great writing experience and we can't wait to show what we have planned.
> Includes Ghost-Editor 0.0.8

- app/components/gh-nav-menu.js
Ensure nav menu icon uses new assets path.
> Fix path of nav menu ghost icon

- package.json
refs TryGhost/Ghost#7429
depends on https://github.com/TryGhost/Ghost/pull/7516
Finally it's starting to feel like a real editor! Although there will be another version bump over the weekend which improves the toolbar behavior and usability, and enables image uploading.
- Added the start of a new toolbar, what we're (well I am) calling the Owesome bar, not to be confused with the Firefox Awesome bar. It's a cultural thing. (google "O for awesome" if you're curious 🎡 of 💰).
- The idea of dragging and dropping cards has been removed for now, although the code will still be in there as we will support dragging cards around within content fairly shortly. When apps are included a better card interface will be required for a large amount of app created content cards (Oh yeah!)
- Ghost Server …
> Upgraded editor

- package.json
Ghost Editor 0.1.1
Refs: https://github.com/TryGhost/Ghost/issues/7429
Relies on:
Ghost Editor now has all the parts to make the whole, however it's still very much an alpha, most things don't work exactly as planned/
This release adds: 
- Added slash menu (kinda)
- Updated toolbars
- Added soft return
- Improved performance
- Added code block ` ` ` support
- Improved Link functionality
> Ghost Editor 0.1.1

- app/serializers/post.js
- [] The build will pass (run `ember test` from the repo root - will be `core/client` if working from the submodule in Ghost).
closes TryGhost/Ghost#7599
1 test not pass but unrelated with this changes (still not pass even without this changes):
```
not ok 578 Firefox 45.0 - Integration: Component: gh-cm-editor handles editor events
---
message: >
has focused class after focus: expected false to be true
Log: |
...
```
> Fix delete post

- bower.json
- package.json
> Update "ember-cli-mocha" to v0.11.0

- app/routes/editor/edit.js
- app/routes/posts/post.js
refs #https://github.com/TryGhost/Ghost/issues/7494
> ✨  support object id's

- app/styles/components/dropdowns.css
- app/styles/layouts/about.css
- app/styles/layouts/content.css
- app/styles/layouts/editor.css
- app/styles/layouts/main.css
- app/styles/patterns/forms.css
- app/styles/patterns/global.css
- app/templates/about.hbs
- app/templates/posts.hbs
Minor style updates to ghost admin making way for 1.0 and editor. 
- Updated typography
- Imported new brand colours
- Adjusted sizing and spacing in various places
> Editor and 1.0 style updates

- Gruntfile.js
- package.json
refs TryGhost/Ghost#7427
Removes unneccessary grunt dependencies from `package.json` and deletes contributor part in `Gruntfile.js`
> 🔥  Remove grunt contributor

- app/mirage/factories/invite.js
- app/models/invite.js
- app/routes/team/index.js
- app/serializers/invite.js
- app/templates/team/index.hbs
- tests/unit/models/invite-test.js
refs https://github.com/TryGhost/Ghost/issues/7432
- invite.role instead of invite.roles
- be able to serialize/deserialize response from and request to server
- server returns role_id
This is my first touch with Ember, so be nice to me 😃 👻
> 🎨  invites roles table into a field on the invites table

- app/routes/setup.js
refs https://github.com/TryGhost/Ghost/pull/7765
- if we have a `token` query param during setup, exchange it for a proper access token and authenticate the session
> Signup flow token refresh for auto-login

- app/routes/setup.js
no issue
- fix issue introduced in https://github.com/TryGhost/Ghost-Admin/pull/433 that prevented /setup from working if no token was provided
> 🐛 fix non-token signup

- package.json
- tests/acceptance/editor-test.js
> Update "ember-cli-mocha" to v0.13.1

- package.json
> remove node 0.12 from allowed engines in package.json

- app/controllers/settings/general.js
- app/templates/settings/general.hbs
closes TryGhost/Ghost#7746
- Added gh-form-group around PostsPerPage
- Changed focusOut action to validate
- Removed now redundant `checkPostsPerPage()` call
> Show error message for invalid data in PostsPerPage

- app/mirage/fixtures/settings.js
- app/models/setting.js
- app/templates/settings/general.hbs
- tests/acceptance/settings/general-test.js
refs TryGhost/Ghost#7769
Adds a checkbox to disable AMP support in general settings.
> ⚡ ❓  Make AMP optional

- app/adapters/user.js
- app/models/post.js
- app/services/session.js
- fix ember-data complex default value returning in post model
> Fix test warnings

- app/index.html
- app/styles/app.css
- app/styles/components/loading-indicator.css
- app/templates/application.hbs
- package.json
no issue
- use the same loading indicator as used on my.ghost.org
- will display whilst the JS is loading and initializing rather than showing a completely blank screen
> display a spinner whilst the app is loading

- app/components/gh-task-button.js
- app/components/modals/delete-all.js
- app/components/modals/delete-post.js
- app/components/modals/delete-subscriber.js
- app/components/modals/delete-tag.js
- app/components/modals/delete-theme.js
- app/components/modals/delete-user.js
- app/components/modals/invite-new-user.js
- app/components/modals/new-subscriber.js
- app/components/modals/re-authenticate.js
- app/components/modals/transfer-owner.js
- app/components/modals/upload-image.js
- app/templates/components/gh-task-button.hbs
- app/templates/components/modals/delete-all.hbs
- app/templates/components/modals/delete-post.hbs
- app/templates/components/modals/delete-subscriber.hbs
- app/templates/components/modals/delete-tag.hbs
- app/templates/components/modals/delete-theme.hbs
- app/templates/components/modals/delete-user.hbs
- app/templates/components/modals/invite-new-user.hbs
- app/templates/components/modals/new-subscriber.hbs
- app/templates/components/modals/re-authenticate.hbs
- app/templates/components/modals/transfer-owner.hbs
- app/templates/components/modals/upload-image.hbs
- package.json
- tests/integration/components/gh-task-button-test.js
- yarn.lock
refs https://github.com/TryGhost/Ghost/issues/7865
- de-couple gh-task-button from gh-spin-button
- switch all modals over to ember-concurrency and gh-task-button
TODO:
> Start Ember Concurrency refactor

- app/controllers/reset.js
- app/templates/reset.hbs
refs https://github.com/TryGhost/Ghost/issues/7865
- swap promise based action for an ember-concurrency task
> refactor reset password screen to use ember-concurrency

- bower.json
- package.json
- yarn.lock
Weekly manual dependency update whilst Greenkeeper is disabled.
> Minor dependency updates

- app/routes/application.js
- tests/acceptance/authentication-test.js
refs https://github.com/TryGhost/Ghost/issues/5202
- refresh the access token after a successful authenticated application boot so that the session lifetime is continually extended
> refresh access token on app boot (LTS)

- app/styles/components/badges.css
- app/styles/layouts/content.css
- app/styles/layouts/main.css
- app/styles/patterns/global.css
- app/templates/-posts-header.hbs
- app/templates/components/gh-posts-list-item.hbs
- app/templates/posts.hbs
Can be merged as-is or left open, doesn't really matter.
> WIP: New content

- ember-cli-build.js
- package.json
- yarn.lock
Converts our css build tooling from Myth to PostCSS
> Myth => PostCSS

- app/styles/components/modals.css
- app/styles/components/selectize.css
- app/styles/components/settings-menu.css
- app/styles/components/uploader.css
- app/styles/layouts/apps.css
- app/styles/layouts/main.css
- app/styles/layouts/settings.css
- app/styles/patterns/forms.css
- app/styles/patterns/navlist.css
- app/templates/components/gh-file-uploader.hbs
- app/templates/components/gh-timezone-select.hbs
- app/templates/components/modals/delete-theme.hbs
- app/templates/components/modals/upload-theme.hbs
- app/templates/settings/general.hbs
- ember-cli-build.js
- package.json
- tests/acceptance/editor-test.js
- tests/acceptance/settings/general-test.js
- yarn.lock
no issue
- new settings/general styles
- colour updates
- update settings/general acceptance tests to use ember-test-selectors
- implement accordion toggles for settings sections
> Rework settings/general

- app/components/gh-theme-table.js
- app/components/modals/upload-theme.js
- app/controllers/settings/general.js
- app/models/setting.js
- app/models/theme.js
- app/routes/settings/general.js
- app/routes/settings/general/uploadtheme.js
- app/serializers/theme.js
- app/templates/components/gh-theme-table.hbs
- app/templates/settings/general.hbs
- app/templates/settings/general/uploadtheme.hbs
- mirage/config/settings.js
- mirage/config/themes.js
- mirage/fixtures/settings.js
- mirage/fixtures/themes.js
- mirage/models/theme.js
- tests/acceptance/settings/general-test.js
- tests/integration/components/gh-theme-table-test.js
refs https://github.com/TryGhost/Ghost/pull/8022
- use `/themes` API endpoint to fetch list of themes instead of `settings[0].availableThemes`
> fetch themes from /themes endpoint

- package.json
- yarn.lock
This moves the / menu out of the render loop, it should also include all of the stuff that didn't make it into last weeks release for some reason.
This will hopefully be the last PR where the editor is an independent project.
> Ghost Editor 0.1.10

- app/app.js
- app/styles/addons/ghost-editor/ghost-editor.css
- app/styles/addons/ghost-editor/ghost-toolbar.css
- lib/ghost-editor/addon/components/ghost-toolbar-button.js
- lib/ghost-editor/addon/components/ghost-toolbar.js
- lib/ghost-editor/addon/options/default-tools.js
- lib/ghost-editor/addon/templates/components/ghost-editor.hbs
- lib/ghost-editor/addon/templates/components/ghost-toolbar-button.hbs
- lib/ghost-editor/addon/templates/components/ghost-toolbar.hbs
> (Self Merge) Implemented new toolbar styling and layout.

- app/templates/components/gh-theme-table.hbs
- tests/acceptance/settings/design-test.js
- tests/integration/components/gh-theme-table-test.js
Test fixes for changes introduced in https://github.com/TryGhost/Ghost-Admin/commit/ae1007c58d347d9f1dc94f1fed5edb895e280e13
> fix tests for new themes table styles

- app/templates/settings/apps/amp.hbs
closes https://github.com/TryGhost/Ghost/issues/8038
> 🎨 fix incorrect icon on AMP app page

- app/components/gh-cm-editor.js
- app/index.html
- app/routes/application.js
- app/services/feature.js
- app/services/lazy-loader.js
- app/styles/app-dark.css
- tests/integration/services/feature-test.js
- tests/integration/services/lazy-loader-test.js
no issue
- add functionality for night mode feature flag using alternate
stylesheets
TODO:
> Night Mode Feature Flag

- app/controllers/posts-loading.js
- app/controllers/posts.js
- app/routes/posts.js
- app/templates/components/gh-nav-menu.hbs
- app/templates/posts-loading.hbs
- app/templates/posts.hbs
closes https://github.com/TryGhost/Ghost/issues/7860
- add "sort by" dropdown allowing to order posts by earliest or latest publication date
> ✨ add "sort by" dropdown to content screen filters

- app/components/gh-file-uploader.js
- config/deprecation-workflow.js
- lib/gh-koenig/addon/components/gh-koenig.js
- package.json
- yarn.lock
no issue
- cleans up a lot of the deprecation noise in tests
> various test deprecation cleanup

- app/templates/setup/one.hbs
no issue
- add span tag to button content
> 💄 fix button styling on setup/one page

- Gruntfile.js
- package.json
- yarn.lock
WIP!
refs TryGhost/Ghost#7427
- both Ghost and Ghost-Admin ran the watch command in background, that didn't work
- the caller can decide if running the watch command in bg or not
- furthermore, the caller can decide if printing stdout/stderr of the background process
see https://github.com/TryGhost/Ghost/pull/8158
> 🔥  remove bg shell from Gruntfile

- app/templates/components/gh-image-uploader.hbs
- lib/gh-koenig/addon/components/koenig-menu-item.js
- lib/gh-koenig/addon/components/koenig-plus-menu.js
- lib/gh-koenig/addon/components/koenig-slash-menu.js
- lib/gh-koenig/addon/templates/components/koenig-slash-menu.hbs
- tests/acceptance/settings/general-test.js
- tests/integration/components/gh-image-uploader-test.js
Closes https://github.com/TryGhost/Ghost/issues/8164
- When a user clicks on a card within a '/' menu it now executes that tool.
- If a user engages a card with the / menu the content of the paragraph is now inserted into the card.
> 🐜  ⬛️   Card menu fixes:

- app/styles/addons/gh-koenig/koenig-toolbar.css
- lib/gh-koenig/addon/components/koenig-toolbar.js
- lib/gh-koenig/addon/templates/components/koenig-toolbar.hbs
Adds styling for the insert link toolbar component.
closes: https://github.com/TryGhost/Ghost/issues/8109
> ✨  Insert Link styling

- lib/gh-koenig/addon/components/koenig-toolbar.js
(No issue)
Adds a few improvements for link insertion.
- Sanitises links
- Toggles a link so that if there are existing links in the selected text it removes them.
> 🚀 Link improvements

- config/environment.js
- ember-cli-build.js
- package.json
- tests/helpers/start-app.js
- yarn.lock
https://emberjs.com/blog/2017/03/19/ember-2-12-released.html#toc_changes-in-ember-cli-2-12
> deps: ember-cli@2.12.1

- app/components/gh-fullscreen-modal.js
- app/components/gh-profile-image.js
- app/components/gh-tag-settings-form.js
- lib/gh-koenig/package.json
no issue
- fix addon preprocessor deprecation warning during build (was showing prominently every time `grunt dev` was started)
- minor refactors for recent/up-coming deprecations
> Minor refactors / fixes

- app/serializers/user.js
refs https://github.com/TryGhost/Ghost/issues/8258
Nothing to explain here, see referenced issue.
I did not run the tests locally, will wait for travis.
Requires https://github.com/TryGhost/Ghost/pull/8259.
> 🎨  rename last_login to last_seen

- lib/gh-koenig/addon/components/gh-koenig.js
- lib/gh-koenig/addon/components/koenig-card.js
- lib/gh-koenig/addon/templates/components/gh-koenig.hbs
Refs: https://github.com/TryGhost/Ghost/issues/8308
Closes: https://github.com/TryGhost/Ghost/issues/8313
- Places the cursor in the logical place when keying up or down from the card.
- Make sure that the key handlers are available even after the page transitions to edit mode.
> Card range issues

- lib/gh-koenig/addon/components/gh-koenig.js
- lib/gh-koenig/addon/lib/utils.js
No Issue.
Creates a util library for the editor to handle common tasks like:
- Loading the current card from the mobiledoc from an element in the DOM
- Deciding if a card should be closed based on a user click.
> Simplify card selection.

- app/components/gh-editor-title.js
- lib/gh-koenig/addon/components/gh-koenig.js
- lib/gh-koenig/addon/components/koenig-slash-menu.js
- lib/gh-koenig/addon/components/koenig-toolbar.js
- lib/gh-koenig/addon/lib/utils.js
Closes: https://github.com/TryGhost/Ghost/issues/8323
Closes: https://github.com/TryGhost/Ghost/issues/8191
Fixes some of the range issues that we're seeing across browsers also simplifies the positioning code for UI elements.
> 🎁 Fix range issues

- app/controllers/setup/two.js
- app/controllers/signup.js
closes https://github.com/TryGhost/Ghost/issues/8375
- `jQuery.ajax` has removed the `.success` and `.error` methods, replacing them with `.done` and `.fail`
> 🐛 fix setup/signup avatar uploads

- app/styles/components/publishmenu.css
- app/styles/patterns/forms.css
> Fix for Firefox CSS Issues

- app/templates/setup/two.hbs
- tests/acceptance/setup-test.js
No issue
- connect email and name labels to inputs
- change name of hidden inputs so that chrome doesn't incorrect fill fields
> For label and chrome autofill corrections to setup/two

- app/components/gh-user-active.js
closes https://github.com/TryGhost/Ghost/issues/8389
- Change user.image -> user.profileImage
> Display correctly user's avatar

- app/helpers/gh-count-characters.js
- app/styles/layouts/user.css
- app/templates/team/user.hbs
- tests/acceptance/team-test.js
- tests/unit/helpers/gh-count-characters-test.js
closes TryGhost/Ghost#7134
Overhaul of the user settings page to make it more consistent with other settings panels.
The hardly readable validation for user "Full Name" is redundant as well, as the input field for it now has the same styles as the other input fields.
> 🎨  User profile settings page layout updates

- app/components/gh-publishmenu-scheduled.js
no issue
I have to investigate how i came into the situation.
Maybe this needs a fix on the server as well.
> 🐛  fix published_at is null

- app/components/gh-uploader.js
- app/templates/components/gh-progress-bar.hbs
- app/templates/components/gh-uploader.hbs
- tests/integration/components/gh-uploader-test.js
no issue
- filled in tests ready to start work on https://github.com/TryGhost/Ghost/issues/8455
> ✅ add tests for `gh-uploader` component

- app/styles/layouts/main.css
- app/styles/layouts/user.css
- app/templates/posts-loading.hbs
- app/templates/posts.hbs
- app/templates/settings/apps.hbs
- app/templates/settings/apps/amp.hbs
- app/templates/settings/apps/index.hbs
- app/templates/settings/apps/slack.hbs
- app/templates/settings/code-injection-loading.hbs
- app/templates/settings/code-injection.hbs
- app/templates/settings/design-loading.hbs
- app/templates/settings/design.hbs
- app/templates/settings/general-loading.hbs
- app/templates/settings/general.hbs
- app/templates/settings/labs-loading.hbs
- app/templates/settings/labs.hbs
- app/templates/subscribers.hbs
- app/templates/team/index-loading.hbs
- app/templates/team/index.hbs
- app/templates/team/user-loading.hbs
- app/templates/team/user.hbs
- tests/acceptance/team-test.js
refs https://github.com/TryGhost/Ghost/issues/8464
- fix padding on user actions button
- match user screen heading to other screens
- match app screen headers to other screens, update form styles
- change header link colour to match non-link colour
- give canvas top padding a fixed `px` value so header elements always align horizontally
- reduce header font size
> 🎨 team + apps header consistency

- app/models/post.js
- app/models/setting.js
- app/models/user.js
- mirage/factories/user.js
refs https://github.com/TryGhost/Ghost/pull/8490
> 🎨  rename language to locale and use `en` as default locale

- app/controllers/settings/design.js
- tests/acceptance/settings/design-test.js
closes https://github.com/TryGhost/Ghost/issues/8515
- ensure the theme record is removed from the store when deleting because theme IDs get re-used unlike other models
> 🐛 fix issue with re-uploading a deleted theme

- app/styles/layouts/main.css
- app/templates/components/gh-nav-menu.hbs
> Bring back view site link

- app/components/modals/upload-theme.js
- app/models/theme.js
- app/styles/layouts/settings.css
- app/templates/components/modals/upload-theme.hbs
- tests/acceptance/settings/design-test.js
refs TryGhost/Ghost#8222
- there are fatal and normal errors
- fatal === can't activate a theme
- the normal errors are only returned in development mode (!)
> 🎨  improve theme results

- app/styles/components/notifications.css
Not sure if this will have any knock-on effects
> Update ludicrous invisible notifications to be blue instead of white

- app/services/tour.js
- app/styles/app-dark.css
- app/styles/components/power-select.css
- app/styles/components/tour.css
- app/styles/layouts/editor.css
- app/styles/layouts/main.css
- app/styles/patterns/buttons.css
- app/styles/patterns/forms.css
- app/styles/patterns/throbber.css
- app/templates/components/gh-nav-menu.hbs
- app/templates/components/gh-post-settings-menu.hbs
- app/templates/components/gh-tour-item.hbs
Closes https://github.com/TryGhost/Ghost/issues/5168
Also updates Dark mode, Closes https://github.com/TryGhost/Ghost/issues/8560
> New tour styles + Dark mode style updates

- app/templates/subscribers.hbs
closes https://github.com/TryGhost/Ghost/issues/8553
- adds a href for pointer and hover class to subscribers export button
> Add subscribers export button class

- app/templates/subscribers.hbs
No Issue
- class should be gh-btn-hover-blue not gh-btn-hover-green
> Subscribers export button :hover should be blue

- app/components/gh-tag-settings-form.js
- app/controllers/settings/tags/tag.js
- app/routes/settings/tags/tag.js
- tests/acceptance/settings/tags-test.js
refs https://github.com/TryGhost/Ghost/issues/7141
- rollback attributes and clear errors when navigating from tag meta settings to main settings pane
- rollback attributes and clear errors when navigating away from the tag route or switching between tags
> 🐛 fix hidden validation errors on tag settings menu

- app/mixins/editor-base-controller.js
refs TryGhost/Ghost#8458
- bypass collision detection for the situation where a user is editing a scheduled post whilst it transitions from scheduled->published on the server
I'm not 100% on this being the correct solution here as it feels bad to disable the collision detection in this scenario.
It could be improved by adding another test to see if the server's `updated_at` is later than the `published_at` value but I'm not sure how reliable that will be because the scheduler is not guaranteed to be that accurate.
> 🐛 fix collision error when saving after scheduled->published transition 

- app/models/post.js
closes TryGhost/Ghost#8603
- see https://github.com/TryGhost/Ghost/issues/8603#issuecomment-309538395
- see comment in code base
> 🐛  fix date with seconds

- app/controllers/settings/general.js
closes https://github.com/TryGhost/Ghost/issues/8545
> 🐛  fix image upload for icons: reset input

- app/mixins/editor-base-controller.js
- app/routes/editor/edit.js
- app/routes/editor/new.js
- app/templates/editor/edit.hbs
Reverts TryGhost/Ghost-Admin#748
See https://github.com/TryGhost/Ghost/issues/8525
> Revert "always give editor text area focus by default"

- app/components/gh-profile-image.js
- app/templates/components/gh-profile-image.hbs
- tests/integration/components/gh-profile-image-test.js
closes TryGhost/Ghost#8612
- added a check for privacy.useGravatar flag (simply useGravatar on client side)
- checked: tests are OK
> Additional check of privacy.useGravatar for gh-profile-image component

- app/styles/layouts/users.css
closes https://github.com/TryGhost/Ghost/issues/8661
> 🎨 fix case inconsistency in team labels

- app/controllers/setup/three.js
refs https://github.com/TryGhost/Ghost/issues/8692
- fixes the guard on setup/three against inviting the owner user created on setup/two (we were sending invites for every e-mail in the list rather than only valid e-mails)
- adds a check to see if we get any invalid errors from the server and will show those separately to the `x emails failed to send` alert
> 🐛 fix guard for inviting owner in setup/three

- app/templates/reset.hbs
closes https://github.com/TryGhost/Ghost/issues/8688
- match input fields HTML to other icon inputs
> 🎨 fix missing lock icons on password reset form

- app/templates/posts.hbs
closes https://github.com/TryGhost/Ghost/issues/8689
- remove titlecase and switch `posts` to `stories`
> 🎨 fix wording and capitalisation on empty stories screen

- app/components/gh-markdown-editor.js
closes https://github.com/TryGhost/Ghost/issues/8657
- add checks for the toolbar being present before attempting to set classes on the buttons
> 🐛 fix broken editor at mobile sizes

- app/components/gh-alert.js
- tests/acceptance/ghost-desktop-test.js
- tests/integration/components/gh-alert-test.js
closes https://github.com/TryGhost/Ghost/issues/8680
> 🎨 use blue instead of yellow for warning alerts

- app/models/user.js
- app/styles/layouts/users.css
- app/templates/-user-list-item.hbs
refs https://github.com/TryGhost/Ghost/issues/8652
TODO:
> [WIP] 🎨 show "locked" badge in team list

- tests/acceptance/settings/slack-test.js
refs https://github.com/TryGhost/Ghost-Admin/commit/ece1d8cef1659c8ec32711f5341e48356a68e07c
- alert was switched for a notification so tests needed updating
> ✅ fix slack tests

- app/routes/team/index.js
- app/templates/team/index.hbs
closes TryGhost/Ghost#8773
- swap old custom `PaginationMixin` for `ember-infinity`
> 🐛 fix infinite scroll on team page

- app/components/gh-profile-image.js
- app/controllers/setup/two.js
- app/controllers/signup.js
- app/templates/components/gh-profile-image.hbs
- bower.json
- ember-cli-build.js
closes https://github.com/TryGhost/Ghost/issues/6661
- refactor `gh-profile-image` component to use native browser functionality
- remove `jquery-file-upload` bower dependency
> Remove usage of jquery-file-upload

- app/components/gh-editor-post-status.js
- app/templates/editor/edit.hbs
refs https://github.com/TryGhost/Ghost/issues/8932
- show "Saving..." text when autosave or manual save tasks are running
> 🐛 Fix post saving indicator only indicating autosaves

- app/templates/settings/apps/index.hbs
- app/templates/settings/apps/unsplash.hbs
no issue
- descriptions should be consistent between index and app screens
- field titles should have a consistent naming scheme
> Apps wording consistency

- app/styles/app-dark.css
- app/styles/components/settings-menu.css
- app/styles/patterns/forms.css
> Checkboxes now have greater contrast when unchecked to make them more visible

- app/styles/layouts/content.css
- app/styles/layouts/main.css
closes TryGhost/Ghost#8962
- fix inability to close menu after clicking "more" in mobile quick-nav (credit @nithindavid)
- fix alignment of story headers in stories list
- fix horizontal scroll when main nav is open
> 🐛 Fixed various iOS issues

- app/controllers/settings/general.js
- app/models/setting.js
- app/styles/patterns/global.css
- app/templates/settings/general.hbs
refs https://github.com/TryGhost/Ghost/issues/9001
- show private feed url if private blogging is enabled
> Private RSS Feed Url

- app/components/gh-uploader.js
closes https://github.com/TryGhost/Ghost/issues/9120
- use `ember-concurrency` to enqueue uploads in `{{gh-uploader}}`
- set simultaneous upload limit to 2
To test this out:
1. open web inspector's Network tab and change the throttle to Fast 3g
2. use the image toolbar button to select 4 or more large-ish images
3. watch the network inspector - there should only be 2 upload requests in progress at one time and the progress bar displayed in the admin should reflect the overall upload status
> Limit simultaneous upload requests

- app/templates/setup/two.hbs
- app/templates/signup.hbs
refs TryGhost/Ghost#9150
😱 Updated two placeholder, which were still showing the old password length requirement.
> Fixed placeholder for password input fields

- lib/asset-delivery/index.js
refs #9178
- needs to be merged together with the server side PR (https://github.com/TryGhost/Ghost/pull/9308)
- we have moved the admin folder location from server/admin to server/web/admin
> Changed asset delivery to web/admin/views

- .travis.yml
> Recommend Node v8

- yarn.lock
> Fix merge conflict text in yarn.lock

- app/styles/components/koenig-content.css
- app/styles/components/koenig.css
- app/styles/layouts/editor.css
- lib/koenig-editor/addon/templates/components/koenig-card-image.hbs
- lib/koenig-editor/addon/templates/components/koenig-card-markdown.hbs
Including:
- basic text styles (paragraph, heaedings)
- blockquotes
- inline and block code
- links
- card basics
- vertical rhythm
> Basic styles for Koenig Beta

- app/styles/components/koenig-content.css
- app/styles/components/koenig.css
- app/styles/patterns/_shame.css
- lib/koenig-editor/addon/components/koenig-card-html.js
- lib/koenig-editor/addon/components/koenig-card-image.js
- lib/koenig-editor/addon/components/koenig-card-markdown.js
- lib/koenig-editor/addon/templates/components/koenig-card.hbs
- lib/koenig-editor/addon/templates/components/koenig-link-input.hbs
- lib/koenig-editor/addon/templates/components/koenig-link-toolbar.hbs
- lib/koenig-editor/addon/templates/components/koenig-toolbar.hbs
Related: https://github.com/TryGhost/Spirit/pull/6
> Koenig styles

- lib/koenig-editor/addon/components/koenig-card-image.js
- lib/koenig-editor/addon/templates/components/koenig-card-image.hbs
> Koenig - Making full width images work with closed sidebar

- package.json
- yarn.lock
Closes #9808
- Bumps ghost-spirit to 0.0.35
> 🐛 Fixed video size in the editor

- lib/koenig-editor/addon/components/koenig-editor.js
closes https://github.com/TryGhost/Ghost/issues/9825
- the <code>`</code> key on German keyboard layouts is a dead key and so does not trigger the typical keyboard events our editor relies on
- added custom keyboard event listeners to watch for specific keyboard event sequences triggered by using the dead key + spacebar to insert a <code>`</code>
- Linux unfortunately does not trigger events that can be used to track the sequence so this will not work there although it is easier to set up keyboard layouts without dead keys on Linux
TODO:
> 🐛 Fixed ` not triggering code text expansions on German keyboards (Win/macOS only)

- app/components/modal-delete-integration.js
- app/controllers/settings/integration.js
- app/routes/settings/integration.js
- app/templates/components/modal-delete-integration.hbs
- app/templates/settings/integration.hbs
Just a WIP to get some feedback on my :fire: ember stuff
Adds delete integration modal, and delete button on the integration page to trigger it.
Missing tests
> ✨ Added ability to delete integrations

- app/controllers/setup/three.js
> Apply security patches to 1.x

- app/components/gh-nav-menu.js
- app/templates/components/gh-nav-menu.hbs
refs TryGhost/Ghost#10136
- Handled active nav state to stay integrations when custom integration view is opened
> Added active nav state on sidebar for custom integration view

- package.json
- yarn.lock
refs. https://github.com/TryGhost/Team/issues/148
- fix vertical rhythm for divs and headings
> Updating Spirit to 0.0.48

- app/routes/signup.js
- mirage/config/authentication.js
refs https://github.com/TryGhost/Ghost/issues/10286
- not used
- looking for more information? visit https://github.com/TryGhost/Ghost/pull/10291
> Removed `invitedBy` from signup routes

- app/components/gh-feature-flag.js
- app/controllers/settings/labs.js
- app/models/setting.js
- app/services/feature.js
- app/services/settings.js
- app/styles/app-dark.css
- app/styles/app.css
- app/styles/layouts/labs.css
- app/templates/components/gh-feature-flag.hbs
- app/templates/settings/labs.hbs
no issue
- Added new members settings/toggle to labs
depends on - https://github.com/TryGhost/Ghost/pull/10537
> Added members feature to labs

- .travis.yml
no issue
- matches Ghost's Travis env
- removes custom yarn install
> Switched Travis dist to xenial

- app/helpers/event-name.js
> Fix typo in webhook event name

- app/components/gh-uploader.js
- app/controllers/settings/labs.js
- app/templates/settings/labs.hbs
no issue
- The server never supported uploading yml files
> 🐛 Fixed routes uploader validation allowing .yml files

- app/controllers/member.js
- app/models/member-subscription.js
- app/models/member.js
- app/routes/member.js
- app/templates/member.hbs
- app/transforms/member-subscription.js
- Updated members model to add subscriptions
- Added subscription transforms
- Updated member screen to show real data from API
> Updated member management section

- app/styles/components/power-select.css
- app/styles/layouts/labs.css
- app/styles/spirit/_hovers.css
- app/templates/members.hbs
- app/templates/settings/labs.hbs
no refs.
- refined Members Labs setting styles for night shift
- added hover state to Members list table cells
> Members refinements

- app/routes/application.js
refs https://github.com/TryGhost/Ghost/issues/9546
To be merged once https://github.com/TryGhost/Ghost/pull/10694 is in master.
> Allowed editors to see notifications

- app/components/gh-date-time-picker.js
- app/components/gh-error-message.js
- app/components/gh-member-avatar.js
- app/components/gh-nav-menu.js
- app/components/gh-navitem.js
- app/components/gh-search-input.js
- app/components/gh-task-button.js
- app/components/gh-token-input/tag-token.js
- app/components/gh-unsplash-photo.js
- app/controllers/settings/integration.js
- app/controllers/staff/user.js
- lib/koenig-editor/addon/components/koenig-card-code.js
- lib/koenig-editor/addon/components/koenig-card-gallery.js
- lib/koenig-editor/addon/components/koenig-card-html.js
- lib/koenig-editor/addon/components/koenig-card-image.js
- lib/koenig-editor/addon/components/koenig-card-markdown.js
- lib/koenig-editor/addon/components/koenig-card.js
- package.json
- yarn.lock
no issue
- update dependency `eslint-plugin-ghost` to v0.3.0
- includes new rules from `eslint-plugin-ember` 6.3.0-6.7.0
- fixed linting failures for new rules
> Update dependency eslint-plugin-ghost to v0.3.0

- .github/CONTRIBUTING.md
- README.md
- SECURITY.md
- app/controllers/setup/three.js
- app/services/tour.js
- app/templates/about.hbs
- app/templates/components/gh-nav-menu.hbs
- app/templates/settings/design.hbs
- app/templates/settings/general.hbs
- app/templates/settings/integrations.hbs
- app/templates/settings/labs.hbs
- tests/acceptance/settings/design-test.js
> Updated links to docs

- app/routes/posts.js
closes https://github.com/TryGhost/Ghost/issues/11057
- removed static "replace" configuration of posts/pages query params
- used the router service to register a `willTransition` event handler which handles conditional replaceState transition behaviour only when filters are changed whilst already on the posts/pages route
> 🐛 Fixed browser back button behaviour after clicking "x posts" on tags screen

- app/routes/members.js
- app/templates/settings/labs.hbs
- tests/acceptance/members-test.js
no-issue
This removes the need for `enableDeveloperExperiments` flag for members
> Enabled members by default

- app/helpers/event-name.js
requires https://github.com/TryGhost/Ghost/pull/11230
- allows member webhooks to be created
> Added "Member added" event to webhooks list

- package.json
> Version bump to 2.37.0

- app/templates/settings/labs.hbs
fa2fe870c1e2e34d1436808f11ebd5b0c5173274
> Refined copy for members settings

- app/components/gh-members-list-item.js
- app/styles/layouts/members.css
- app/styles/layouts/user.css
- app/styles/patterns/forms.css
- app/styles/spirit/_media-queries.css
- app/templates/components/gh-members-lab-setting.hbs
- app/templates/components/gh-members-list-item.hbs
- app/templates/members.hbs
- fixed Firefox input bug for form groups
- fixed members list responsive styles
- moved from rem based responsive limits to pixel based
> V3 css fixes

- app/styles/layouts/editor.css
- app/styles/spirit/_koenig.css
no issue.
- updated basic typographic style of Koenig to match better with Casper 3.0
- fixed vertical spacings of paragraphs and lists
- changed color of code text to make it more brand agnostic
> 🎨 Refreshed Koenig content style

- app/components/gh-post-settings-menu.js
- app/controllers/editor.js
- app/models/post.js
- app/templates/components/gh-post-settings-menu.hbs
- app/validators/post.js
- mirage/factories/post.js
refs https://github.com/TryGhost/Ghost/pull/11335
> Added post email settings

- app/styles/layouts/settings.css
no issue.
- fixed sizing issue of textarea being too wide in Code injection for long lines
> 🐛 Fixed code injection input sizing

- app/styles/layouts/editor.css
- app/styles/spirit/_koenig.css
no issue.
- fixed editor post title placeholder font-weight
- fixed spacing between editor post title and first paragraph/card
> Fix editor post title styles

- app/components/gh-members-no-members.js
- app/controllers/members.js
- app/styles/components/notifications.css
- app/styles/layouts/content.css
- app/styles/patterns/buttons.css
- app/templates/components/gh-members-no-members.hbs
- app/templates/members.hbs
- Adds ability to make yourself a member
- Adds ability to import CSV member
- Link to add member manually
:warning: Needs proper styling
TODO:
@peterzimon let me know if you'd like to work on styles yourself and would appreciate a wording check :)
> ✨ Improved adding first members on no-members screen

- app/components/gh-navitem.js
- app/controllers/settings/design.js
- app/models/navigation-item.js
- app/models/setting.js
- app/templates/components/gh-navitem.hbs
- app/templates/settings/design.hbs
- app/transforms/navigation-settings.js
- mirage/fixtures/settings.js
- tests/acceptance/settings/design-test.js
- tests/unit/controllers/settings/design-test.js
refs: https://github.com/TryGhost/Ghost/pull/11409
- Added a new UI for a second set of navigation links
- This should support most concepts of nav, e.g. left and right, or header and footer
- This PR mostly updates the design and nav components to cope with a second set of nav
@kevinansfield 👋 shoving this up now that it seems to be 100% working to get feedback on approach - ember is not my usual bag - mostly not sure about true/falsy values in this context or whether it should be passing the model. Totes aware I need to write tests 😬will get right on that.
> ✨ Added Secondary Navigation

- app/components/gh-members-chart.js
- app/styles/app-dark.css
- app/styles/layouts/members.css
- app/templates/components/gh-members-chart.hbs
- app/templates/members.hbs
> Added members chart v1

- app/controllers/settings/general.js
- app/models/setting.js
- app/styles/layouts/settings.css
- app/templates/settings/general.hbs
Depends on - https://github.com/TryGhost/Ghost/pull/11408
- Reads new brand primary color setting and adds UI to modify/update it behind the dev flag
> ✨ Added new brand color publication setting

- app/components/modal-upgrade-host-limit.js
- app/controllers/editor.js
- app/services/ajax.js
- app/templates/components/modal-upgrade-host-limit.hbs
- app/templates/editor.hbs
depends on - https://github.com/TryGhost/Ghost/pull/11439
Adds host limit upgrade popup in case publishing a post with email newsletter exceeds total number of members allowed by the plan. Handles new 403-HostLimitError by server
> Added host limit checks for sending email

- .travis.yml
no issue
- we want to test on all supported Node versions
> Added Node 10 testing to CI

- mirage/config.js
- mirage/config/labels.js
- tests/acceptance/members-test.js
> Fixed tests for labels

- app/components/gh-publishmenu-draft.js
- app/components/modal-confirm-email-send.js
- app/controllers/editor.js
- app/templates/components/gh-publishmenu-draft.hbs
- app/templates/components/gh-publishmenu-scheduled.hbs
- app/templates/components/modal-confirm-email-send.hbs
> Fixed email messaging for publish and send as Editor

- app/components/gh-billing-iframe.js
- app/components/gh-nav-menu.js
- app/controllers/billing.js
- app/router.js
- app/routes/billing.js
- app/templates/billing.hbs
- app/templates/components/gh-billing-iframe.hbs
- app/templates/components/gh-nav-menu.hbs
> Added billing route w/ billing iframe

- app/components/gh-billing-iframe.js
no-issue
This just keeps the admin in line with the changes made in
https://github.com/TryGhost/Ghost/pull/11559/files
> Updated URL and response handling for identity token

- .github/workflows/test.yml
> Switched to built-in Node.js for tests

- app/components/gh-members-lab-setting.hbs
- app/components/gh-members-lab-setting.js
- app/models/setting.js
- app/styles/layouts/labs.css
- app/styles/patterns/buttons.css
Stripe connect design refinements
> Stripe connect design

- app/components/gh-members-lab-setting.hbs
- app/components/gh-members-lab-setting.js
- app/components/modal-members-modal-settings.hbs
- app/components/modal-members-modal-settings.js
- app/models/setting.js
- app/services/settings.js
- Adds new modal settings option in members settings
- Allows customization of modal settings for membersjs
- Uses new memebrsjs settings which owner/admin can change
> Added new members modal settings behind dev flag

- app/components/gh-navitem.hbs
- app/components/gh-navitem.js
- app/controllers/settings/design.js
- app/templates/settings/design.hbs
closes https://github.com/TryGhost/Ghost/issues/11590
- Dirty attribute flag was set incorrectly on focus out from label/url fields as no check with existing was used
- Checks against existing nav item value before setting dirty attribute on focus out
> 🐛 Fixed incorrect save warning on design settings

- app/components/gh-members-lab-setting.hbs
- app/components/gh-members-lab-setting.js
- app/components/modal-members-modal-settings.hbs
- app/components/modal-members-modal-settings.js
- app/models/setting.js
- app/services/settings.js
no issue
- reverts commit c46fcec5b28d89b2b1133fbdcb806378a37ded14 with modifications for naming
- Adds new portal settings UI in Labs -> Members setting
- Allows customization of new `portal-*` settings upstream
- Updates settings service to include `portal` group
- Updates settings modal to include new `portal-*` settings
> Added new modal settings behind dev flag

- app/components/gh-members-lab-setting.hbs
- app/components/gh-site-iframe.hbs
- app/components/gh-site-iframe.js
- app/components/modal-members-modal-settings.hbs
- app/components/modal-members-modal-settings.js
- app/styles/app-dark.css
- app/styles/app.css
- app/styles/layouts/portal-settings.css
no issue
- Adds live preview of members.js modal UI to the new settings modal behind dev flag
- Uses gh-site-iframe to render site in preview mode
> Added live preview to members settings modal

- app/components/gh-members-lab-setting.js
> 🐛 Fix missing currency for yearly plan in Labs subscription price

- app/components/gh-members-lab-setting.hbs
- app/components/gh-members-lab-setting.js
- app/styles/patterns/forms.css
refs https://github.com/TryGhost/Ghost/issues/11765
This adds error handling to the stripe plan prices to ensure they are set for at least 1 USD (or other currency) or more.
> Added basic handling for invalid plan amount

- app/components/modal-members-modal-settings.hbs
- app/components/modal-members-modal-settings.js
- app/models/setting.js
- app/styles/layouts/portal-settings.css
no issue
- Adds new Look & Feel section to portal settings to control accent color, button style, text and icon
- Adds Links section to portal settings to show static links to control popup behavior
- Adds the 3 new portal settings to setting model
> Added new look feel and links section to modal settings

- app/components/gh-post-settings-menu.js
- app/components/gh-tag-settings-form.hbs
- app/components/gh-tag-settings-form.js
closes https://github.com/TryGhost/Ghost/issues/11385
- Removed typo from tags metadata preview
- Updates og and twitter description to use correct fallbacks for posts/pages
- Updates og and twitter description to use correct fallback for tags
- Updates og and twitter title to use correct name format for tags
> Fix broken structured previews

- app/components/gh-feature-flag.hbs
- app/components/gh-members-lab-setting.hbs
- app/components/gh-members-lab-setting.js
- app/templates/settings/labs.hbs
- tests/acceptance/settings/labs-test.js
closes https://github.com/TryGhost/Ghost/issues/12052
> Fixed issue with mailgunBaseUrl not being set by default

- app/components/modal-members-modal-settings.hbs
- app/components/modal-members-modal-settings.js
no issue
- Adds mapping for default svg icons to keys
- Updates custom icon check to not include default icons
- Updated settings update to save default icon key on update
> Updated default icon handling for portal settings

- app/components/gh-portal-links.hbs
- app/components/gh-portal-links.js
- app/components/modal-members-modal-settings.hbs
- app/components/modal-members-modal-settings.js
- app/styles/layouts/portal-settings.css
refs https://github.com/TryGhost/members.js/issues/80
- This adds the link/attribute switcher and chooser directly to Admin in Portal preview area
- Thinks links/attributes section was previously shown as a Portal page
> Added Portal links section in preview area

- app/components/modal-members-modal-settings.hbs
- app/components/modal-members-modal-settings.js
- app/styles/layouts/portal-settings.css
refs https://github.com/TryGhost/members.js/issues/79
- Updated interaction for custom icon flow as per design spec in issue
> Refined portal custom icon flow

- app/components/gh-members-lab-setting.hbs
- app/components/gh-members-lab-setting.js
- app/controllers/settings/labs.js
- app/models/setting.js
- app/routes/settings/labs.js
- app/styles/layouts/labs.css
- app/templates/settings/labs.hbs
depends on - https://github.com/TryGhost/Ghost/pull/12161
> Added support address fields

- app/components/gh-nav-menu.hbs
- app/components/gh-nav-menu.js
- app/styles/layouts/main.css
Not related to any issue.
- Configured the dropdown to auto position itself vertically and enabled the renderInPlace flag. 
- Removed unused function ```userDropdownPosition```
- Changed overflow value to visible to ensure the entire content space was visible
> Fixed account menu spacing issue

- app/components/gh-members-lab-setting.hbs
- app/components/gh-members-lab-setting.js
- app/components/modal-portal-settings.hbs
- app/components/modal-portal-settings.js
- app/controllers/settings/labs.js
- app/controllers/settings/labs/members.js
- app/router.js
- app/routes/settings/labs.js
- app/routes/settings/labs/members.js
- app/styles/layouts/labs.css
- app/styles/layouts/portal-settings.css
- app/styles/layouts/settings.css
- app/styles/patterns/buttons.css
- app/templates/settings/labs.hbs
- app/templates/settings/labs/members.hbs
- tests/acceptance/members-test.js
- tests/acceptance/settings/labs-test.js
Moved Members related settings in Labs to its own page to improve the overall UX and make it more consistent with the rest of the Admin.
> Moved members settings to new page

- app/adapters/post.js
- app/components/gh-editor-post-status.js
- app/components/gh-posts-list-item.hbs
- app/components/gh-posts-list-item.js
- app/components/gh-publishmenu-draft.hbs
- app/components/gh-publishmenu-draft.js
- app/components/gh-publishmenu-scheduled.hbs
- app/components/gh-publishmenu-scheduled.js
- app/components/gh-publishmenu.hbs
- app/components/gh-publishmenu.js
- app/components/modal-confirm-email-send.hbs
- app/components/modal-confirm-email-send.js
- app/controllers/editor.js
- app/models/post.js
- app/serializers/page.js
- app/serializers/post.js
- Adds option to select free/paid/all/none for members to send newsletters
> ✨ Allowed sending newsletter to free members only

- app/components/gh-publishmenu-draft.hbs
- app/components/gh-publishmenu-draft.js
- app/components/gh-publishmenu-scheduled.hbs
- app/components/gh-publishmenu-scheduled.js
- app/components/gh-publishmenu.hbs
- app/components/gh-publishmenu.js
- app/styles/components/publishmenu.css
- Updates default publish menu member newsletter selection based on member count
- Adds count to members in draft publish menu
- Disables checkbox based on count in publish menu
> Added member counts to newsletter publish menu

- app/components/gh-members-lab-setting.hbs
- app/components/modal-email-design-settings.hbs
- app/components/modal-email-design-settings.js
- app/models/setting.js
no-issue
This will allow users to customise the footer of their newsletter emails using plaintext
> Added initial newsletter footer setting

- app/components/modal-post-email-preview.hbs
- app/components/modal-post-email-preview.js
- app/styles/app-dark.css
- app/styles/layouts/preview-email.css
Made post email preview design consistent with the new email settings design preview. 
- changed background
- added fake container windows and faux sender/recipient content
- updated mobile and dark mode
> Update post email preview design

- app/components/modal-portal-settings.hbs
- app/components/modal-portal-settings.js
- app/models/setting.js
- app/styles/layouts/portal-settings.css
Enables users to set up redirect links after a successful signup in Portal.
> Portal redirects on signup

- app/adapters/api-key.js
- app/components/modal-regenerate-token.hbs
- app/components/modal-regenerate-token.js
- app/controllers/staff/user.js
- app/routes/staff/user.js
- app/styles/layouts/user.css
- app/styles/patterns/forms.css
- app/templates/staff/user.hbs
- mirage/config/users.js
refs TryGhost/Ghost#12373
:warning: depends on TryGhost/Ghost#12374
> Added the Personal Tokens feature

- app/components/gh-url-input.hbs
- app/components/gh-url-input.js
- app/components/modal-portal-settings.hbs
- app/components/modal-portal-settings.js
> Allowed users to paste absolute URLS for signup redirects

- app/components/gh-url-input.hbs
- app/components/gh-url-input.js
- app/components/modal-portal-settings.hbs
- app/components/modal-portal-settings.js
> Added support for external urls for redirect

- app/components/gh-member-settings-form.hbs
- app/components/gh-member-settings-form.js
no-issue
This is only displayed when it is present, which is only when the user
has actively canceled.
> Added cancellation reason to subscription UI

- app/components/gh-member-settings-form.hbs
- app/components/gh-member-settings-form.js
refs https://github.com/TryGhost/Ghost/issues/12256
- Replace `_` in stripe's status with space to setup proper status label for subscriptions
> Updated stripe status label handling in subscriptions

- app/components/modal-email-design-settings.hbs
- app/components/modal-email-design-settings.js
- app/styles/components/modals.css
- app/styles/layouts/members.css
- app/styles/layouts/preview-email.css
Style and copy updates in email settings preview
> Email settings preview refinements

- app/components/gh-member-settings-form.hbs
- app/models/member.js
- app/styles/layouts/members.css
- app/styles/patterns/forms.css
- app/templates/member.hbs
No-ref
- Added "Emails received", "Emails opened", and "Avg. open rate" to member details
- Adjusted visual display of avatar, name and email
- Rearranged Name and Email fields to reduce height
- Changed height of the notes textarea
> Included basic stats on member details page

- app/components/modal-import-members.hbs
- app/components/modal-import-members.js
- app/components/modal-import-members/csv-file-mapping.js
- app/styles/layouts/members.css
> Updated UI for empty member import

- app/components/gh-publishmenu.js
- app/components/modal-confirm-email-send.js
- app/controllers/members.js
> [WIP] Replaced usage of paid param with a filter on status

- app/styles/app-dark.css
- app/styles/components/settings-menu.css
- app/styles/layouts/settings.css
- app/styles/layouts/tags.css
- app/styles/spirit/_colors-dark.css
- app/styles/spirit/_custom-styles-dark.css
- app/templates/editor.hbs
No issue
- Proposed color refresh for dark mode
- Improved overall styling for code injection in post settings and tag settings and added dark mode
**Current:** 
**Proposed:**
> Updated dark mode colors

- app/components/gh-event-timeline.hbs
- app/components/gh-event-timeline.js
- app/controllers/dashboard.js
- app/services/members-stats.js
- app/templates/dashboard.hbs
- app/utils/currency.js
This adds the initial setup for the event timeline on the dashboard.
> Dashboard event timeline

- app/components/gh-members-chart.hbs
- app/components/gh-members-chart.js
- app/services/members-stats.js
- app/templates/dashboard.hbs
- Added MRR chart for last 30 days
- Added initial chart for Total member count
> Added initial charts for dashboard

- app/components/gh-members-chart.js
- app/controllers/dashboard.js
- app/services/members-stats.js
- app/templates/dashboard.hbs
> Fixed empty state error for mrr chart

- app/controllers/dashboard.js
- app/templates/dashboard.hbs
> Added top members by email open rate to dashboard

- app/controllers/dashboard.js
- app/templates/dashboard.hbs
- Adds basic percentage growth stat for mrr on dashboard
> Updated mrr stats on dashboard

- app/components/gh-members-chart.js
- app/controllers/dashboard.js
- app/services/members-stats.js
- app/templates/dashboard.hbs
no refs
- Setting chart options in case of nightShift change was missing options param for new charts
> Updated stats on dashboard

- app/controllers/dashboard.js
- app/templates/dashboard.hbs
- Added growth stats for member counts
- Cleaned up growth stats for mrr
> Updated growth stats on dashboard

- app/controllers/dashboard.js
- app/services/members-stats.js
- Fixed calculation for total/paid member count to use last value from outside range
- Fixed stats data override in dashboard
> Cleaned calculation for total/paid member count

- app/components/gh-nav-menu/main.js
- app/components/modal-new-integration.hbs
- app/components/modal-new-integration.js
- app/components/modal-upgrade-host-limit.hbs
- app/controllers/application.js
- app/controllers/integrations.js
- app/routes/integrations/zapier.js
- app/services/billing.js
- app/templates/integrations.hbs
Hi @kevinansfield, I've made a bunch of minor updates to Ghost admin for limits, including displaying an error in the new integration modal as discussed.
I am fairly confident these changes are OK, except one - how I'm transitioning back out of the Zapier integration when that is disabled:
https://github.com/TryGhost/Admin/compare/limits?expand=1#diff-7a4baaa138f0ae7231091aea5dc6ee3dd735f11a5d36a614805e85d27db5d5aaR42-R47
It works and doesn't error so I can just merge, but wanted to make sure it went past your nose
> Misc Updates for Limits

- app/components/modal-regenerate-token.hbs
- app/controllers/staff/user.js
- app/styles/layouts/apps.css
- app/templates/staff/user.hbs
issue https://github.com/TryGhost/Team/issues/497
> Updated the staff access token to use the existing patterns

- app/components/modal-invite-new-user.hbs
- app/components/modal-invite-new-user.js
- app/styles/layouts/users.css
- app/styles/patterns/boxes.css
- app/styles/spirit/_custom-styles.css
- app/templates/staff/index.hbs
- mirage/config/roles.js
- package.json
- tests/acceptance/staff-test.js
- yarn.lock
Refs https://github.com/TryGhost/Team/issues/572
- Replaced dropdown in invite-user modal with radio buttons
- Added description for each user role
- Added icon to provide more info on hover for each role
- Got rid of unused box styling
- Fixed left-tooltip positioning
> Clarified staff user roles in Admin

- app/components/gh-products-price-billingperiod.hbs
- app/components/gh-products-price-billingperiod.js
- app/components/modal-product-price.hbs
- app/components/modal-product-price.js
- app/controllers/settings/product.js
- app/controllers/settings/products.js
- app/helpers/currency-symbol.js
- app/models/product.js
- app/models/stripe-price.js
- app/router.js
- app/routes/settings/product.js
- app/routes/settings/product/new.js
- app/routes/settings/products.js
- app/templates/settings/product.hbs
- app/templates/settings/products.hbs
- app/transforms/stripe-price.js
refs https://github.com/TryGhost/Team/issues/627
Wires up the Product settings with data from API
> Wired products data to Product settings screen

- app/components/gh-launch-wizard/finalise.js
- app/components/gh-launch-wizard/set-pricing.hbs
- app/components/gh-launch-wizard/set-pricing.js
- app/components/gh-member-settings-form-cp.hbs
- app/components/modal-free-membership-settings.hbs
- app/components/modal-free-membership-settings.js
- app/components/modal-portal-settings.hbs
- app/components/modal-portal-settings.js
- app/components/modal-product-price.hbs
- app/controllers/launch.js
- app/controllers/settings/products.js
- app/services/members-utils.js
- app/styles/layouts/members.css
- app/styles/layouts/products.css
- app/templates/launch.hbs
- app/templates/settings/products.hbs
refs https://github.com/TryGhost/Team/issues/637
Adds custom prices handling for Portal settings
> Handled custom prices in portal settings

- app/components/modal-free-membership-settings.hbs
- app/components/modal-free-membership-settings.js
- app/controllers/settings/products.js
- app/models/setting.js
- app/templates/settings/products.hbs
refs https://github.com/TryGhost/Team/issues/637
With custom products it's possible to change the name and description of any price. This assumes that people would want to change the same properties of a Free membership, and wires up the values for free membership price settings to API
> Wired free membership settings to API

- app/components/modal-upgrade-host-limit-custom-theme.hbs
- app/controllers/settings/theme.js
- app/routes/settings/theme/uploadtheme.js
- app/templates/settings/theme.hbs
- app/templates/settings/theme/uploadtheme.hbs
no issue
- Addresses https://github.com/TryGhost/Admin/commit/16debb75a994f16ff5079f2f2896ed9958e4cbbe#r49241896
- Uses limit service to display the configured error message
> Display error message from limit service on theme upload

- app/adapters/product.js
- app/components/gh-launch-wizard/connect-stripe.js
- app/components/gh-launch-wizard/finalise.js
- app/components/gh-launch-wizard/set-pricing.js
- app/components/gh-member-settings-form-cp.js
- app/components/gh-members-payments-setting.js
- app/components/gh-membership-products-alpha.hbs
- app/components/gh-membership-products-alpha.js
- app/components/gh-portal-links.hbs
- app/components/gh-portal-links.js
- app/components/modal-portal-settings.hbs
- app/components/modal-portal-settings.js
- app/components/modal-product.hbs
- app/components/modal-product.js
- app/controllers/settings/membership.js
- app/helpers/gh-price-amount.js
- app/models/product.js
- app/styles/layouts/products.css
- app/templates/settings/membership.hbs
- app/transforms/stripe-price.js
- Adds new multiple tiers(products) flow behind dev flag
- Updates handling of product/prices to use new updated API with support for monthly/yearly_price
> Added new multiple tiers UI flow behind dev flag

- app/components/gh-file-input.js
- app/components/gh-uploader.hbs
- app/components/gh-uploader.js
- app/components/modal-email-design-settings-labs.hbs
- app/components/modal-email-design-settings-labs.js
- app/components/modal-email-design-settings.hbs
- app/components/modal-email-design-settings.js
- app/models/setting.js
- app/styles/components/modals.css
- app/styles/layouts/members.css
- app/styles/patterns/buttons.css
- app/templates/settings/members-email.hbs
- public/assets/icons/align-center.svg
- public/assets/icons/align-left.svg
refs https://github.com/TryGhost/Team/issues/755
reqs https://github.com/TryGhost/Ghost/pull/13006
- updated settings model to match new server-side settings
- updated email customisation modal behind the dev experiments flag
- adjusted layout to move to a fixed top bar and scrollable sidebar
- added image upload, toggles and selections for new settings
- updated preview to match selected settings
> ✨ Added settings for newsletter header, title style, and feature image

- app/components/gh-feature-flag.js
- app/services/feature.js
- app/templates/settings/labs.hbs
- Added toggle UI for the match helper
@kevinansfield I'm trying to setup an example for how to add feature flags 😬 is there anything about this that could or should be improved?
Note this PR introduced the Alpha feature section on the labs page
> Adding Match Helper UI

- app/components/gh-member-settings-form-cp.hbs
- app/components/gh-member-settings-form-cp.js
- app/components/modal-member-product.hbs
- app/components/modal-member-product.js
- app/styles/components/modals.css
- app/styles/layouts/members.css
- app/styles/patterns/forms.css
- public/assets/icons/check.svg
- Updated comped subscription handling with multiple products
> Add UI for complimentary products with multiple products feature

- app/components/gh-benefit-item.hbs
- app/components/gh-benefit-item.js
- app/components/gh-membership-products-alpha.hbs
- app/components/modal-product.js
- app/controllers/settings/membership.js
- app/models/product-benefit-item.js
- app/styles/layouts/products.css
- app/transforms/product-benefits.js
- app/validators/product-benefit-item.js
refs https://github.com/TryGhost/Team/issues/792
> Wired benefits section to API

- app/components/modal-reset-all-passwords.hbs
- app/components/modal-reset-all-passwords.js
- app/controllers/staff/index.js
- app/styles/layouts/users.css
- app/templates/staff/index.hbs
issue https://github.com/TryGhost/Team/issues/750
pr https://github.com/TryGhost/Ghost/pull/13005
> ✨ Added the "reset all passwords" user interface

- app/components/gh-members-recipient-select.js
- app/components/gh-members-segment-select.js
- app/components/gh-post-settings-menu-labs.hbs
- app/components/gh-post-settings-menu-labs.js
- app/components/gh-post-settings-menu.hbs
- app/components/gh-post-settings-menu.js
- app/models/post.js
- app/transforms/visibility-string.js
- app/validators/post.js
- Added back product options to members segment select
- Added back ability to set post access to segments
- Enabled product options for email recipient segment
> Re-enable multiple products segmentation on post and email

- app/components/gh-image-uploader.js
> Updated image uploader to accept webp images

- app/templates/settings/labs.hbs
refs https://github.com/TryGhost/Team/issues/613
refs https://github.com/TryGhost/Ghost.org/pull/104
> Updated docs URL for OAuth alpha feature

- app/components/gh-members-filter-labs.hbs
- app/components/gh-members-filter-labs.js
- app/styles/layouts/main.css
Fixed z position of members filter dropdown by replacing its component for basic dropdown.
> Members filter basic dropdown

- app/services/feature.js
- app/templates/settings/labs.hbs
refs https://github.com/TryGhost/Team/issues/1067
- To be used whilst developing the auto-login functionality so we can
test this on production sites.
> Added `membersAutoLogin` labs flag

- app/components/gh-launch-wizard/connect-stripe.js
- app/components/gh-launch-wizard/set-pricing.js
- app/components/gh-members-payments-setting.js
- app/components/gh-members-recipient-select.js
- app/components/gh-members-segment-select.js
- app/components/gh-membership-products-alpha.hbs
- app/components/gh-portal-links.js
- app/components/gh-product-card.hbs
- app/components/gh-product-card.js
- app/components/modal-member-product.js
- app/components/modal-portal-settings.js
- app/components/modal-product.hbs
- app/components/modal-product.js
- app/controllers/dashboard.js
- app/controllers/offer.js
- app/controllers/offers.js
- app/controllers/settings/membership.js
- app/helpers/gh-price-amount.js
- app/models/product.js
- app/styles/layouts/products.css
- app/templates/settings/membership.hbs
- app/utils/currency.js
refs https://github.com/TryGhost/Team/issues/1037
Adds new Free tier card when tiers feature is enabled, allowing site owners to add custom description and benefits for free tier for Portal/theme.
> Added description and benefits for free tier

- .eslintignore
- .gitignore
- package.json
- yarn.lock
no issue
- bumped `ember-source`, `ember-data`, and `ember-cli` to latest 3.24.x versions
> Updated Ember dependencies to 3.24

- app/components/modal-product.hbs
- app/components/modal-product.js
- app/models/product.js
- app/templates/settings/membership.hbs
refs https://github.com/TryGhost/Team/issues/1168
> Wire up welcome page urls

- app/services/feature.js
- app/templates/settings/labs.hbs
- lib/koenig-editor/addon/components/koenig-card-email-cta.hbs
Settings panel should be turned on by default. This PR removes the alpha flag and corresponding conditions for it.
> Remove alpha flag for Editor settings panel

- app/components/gh-membership-products-alpha.hbs
- app/components/gh-membership-products-alpha.js
- app/components/gh-product-card.hbs
- app/components/modal-product.hbs
- app/components/modals/offers/unarchive.hbs
- app/components/modals/tiers/archive.hbs
- app/components/modals/tiers/archive.js
- app/components/modals/tiers/unarchive.hbs
- app/components/modals/tiers/unarchive.js
- app/components/settings/members/archive-tier.hbs
- app/components/settings/members/archive-tier.js
- app/styles/components/modals-new.css
- app/styles/layouts/products.css
refs https://github.com/TryGhost/Team/issues/1252
Allows site owners to archive tiers that are not in use anymore from the Admin.
> Added (un)archiving option for tiers UI

- app/components/gh-contentfilter.hbs
- app/components/gh-nav-menu.hbs
- app/components/gh-nav-menu.js
- app/components/gh-nav-menu/footer.hbs
- app/components/gh-nav-menu/main.hbs
- app/components/gh-posts-list-item.hbs
- app/components/modals/post-preview.hbs
- app/components/modals/post-preview.js
- app/controllers/posts-loading.js
- app/controllers/posts.js
- app/routes/posts.js
- app/styles/components/settings-menu.css
- app/styles/layouts/content.css
- app/styles/layouts/editor.css
- app/styles/layouts/main.css
- app/templates/application.hbs
- app/templates/editor.hbs
- app/templates/posts-loading.hbs
- app/templates/posts.hbs
- tests/acceptance/content-test.js
Updates Admin UX for Contributors
When logged in as a Contributor:
- removes sidebar, added floating account menu and dark-mode switch to right side. Updated mobile menu accordingly
- all post by the given user is listed in the Post list
- changed post filtering
- hides email columns in post list
- removes publishmenu for Contributors in Post preview modal
- visual tweaks
> Contributors updates

- app/styles/layouts/post-preview.css
This PR fixes the issue of post preview header pixel jump when switching between preview windows.
> Fix post preview header pixel jump

- app/transforms/facebook-url-user.js
- app/transforms/json-string.js
- app/transforms/member-product.js
- app/transforms/member-subscription.js
- app/transforms/moment-date.js
- app/transforms/moment-utc.js
- app/transforms/navigation-settings.js
- app/transforms/product-benefits.js
- app/transforms/raw.js
- app/transforms/slack-settings.js
- app/transforms/stripe-price.js
- app/transforms/twitter-url-user.js
A continuation of #2227 that runs the native classes codemod against app/transforms
> [chore] runs native classes codemod for apps/transform

- app/controllers/settings/membership.js
refs https://github.com/TryGhost/Team/issues/1319
> Rounded monthly/yearly prices

- app/controllers/editor.js
Required as a part of https://github.com/TryGhost/Admin/pull/2245/
> [chore] updates app/controllers/editor.js to use native classes

- app/components/gh-members-list-item-column.hbs
- app/components/gh-members-list-item-column.js
- app/components/members/filter-value.hbs
- app/components/members/filter-value.js
- app/components/members/filter.hbs
- app/components/members/filter.js
- app/components/tiers/segment-select.hbs
- app/components/tiers/segment-select.js
- app/controllers/members.js
- app/styles/components/filter-builder.css
- mirage/config/members.js
- mirage/models/product.js
- tests/acceptance/members/filter-test.js
refs https://github.com/TryGhost/Team/issues/1029
> Added a "Tier" filter to available member filters

- .lint-todo
- app/components/gh-member-activity-feed.hbs
- app/components/gh-member-details-activity.hbs
- app/components/gh-member-details.hbs
- app/components/gh-member-details.js
- app/components/gh-member-settings-form.hbs
- app/components/gh-member-settings-form.js
- app/components/gh-nav-menu/main.hbs
- app/components/member/activity-feed.hbs
- app/helpers/first-name.js
- app/routes/member.js
- app/styles/app-dark.css
- app/styles/layouts/main.css
- app/styles/layouts/member-activity.css
- app/styles/layouts/members.css
- app/styles/patterns/buttons.css
- app/styles/patterns/forms.css
- app/styles/patterns/global.css
- app/templates/member.hbs
- app/templates/members-activity.hbs
- public/assets/icons/eye.svg
- public/assets/icons/member-add.svg
- public/assets/icons/pin.svg
No issue
- Changed the Member details page to be more scalable and flexible, depending on whether creators are using subscriptions, emails, and stats.
> 🎨 Updated Member page layout

- app/components/members/filter.js
- app/services/feature.js
- app/templates/settings/labs.hbs
- tests/acceptance/members/filter-test.js
no issue
- allows for filtering members by additional fields using a date picker with `before`, `on or before`, `after`, and `on or after` queries
> ✨ Added "Created", "Paid start date", and "Next billing date" date-based filters to members list screen

- .lint-todo
- app/components/gh-members-list-item.hbs
- app/components/gh-members-list-item.js
- app/components/gh-membership-products-alpha.hbs
- app/components/gh-membership-products-alpha.js
- app/components/gh-post-settings-menu/visibility-segment-select.hbs
- app/components/gh-product-card.hbs
- app/components/modal-portal-settings.js
- app/components/modals/tiers/archive.js
- app/components/settings/members/archive-tier.js
- app/controllers/members.js
- app/controllers/settings/membership.js
- app/templates/settings/membership.hbs
refs https://github.com/TryGhost/Team/issues/1035
> Added default status/tier on members table

- .lint-todo
- app/components/gh-member-settings-form.hbs
- app/components/gh-member-settings-form.js
- app/components/modal-member-product.hbs
- app/components/modal-member-product.js
- app/styles/layouts/members.css
- ember-cli-build.js
- mirage/config/members.js
- mirage/factories/subscription.js
- mirage/models/member.js
- mirage/models/subscription.js
- mirage/serializers/member.js
- mirage/serializers/subscription.js
- tests/acceptance/members/details-test.js
- tests/acceptance/members/filter-test.js
refs https://github.com/TryGhost/Team/issues/1141
- The canceled subscriptions provide a more complete picture of the activity of a member.
> ✨ Added canceled subscriptions in member detail screen

- app/components/modal-email-design-settings.hbs
- app/styles/components/koenig.css
- app/styles/layouts/editor.css
- app/styles/layouts/members.css
Contains typography refinements and updates for the editor
> Typography updates

- .lint-todo
- app/components/modal-product.hbs
- app/components/modal-product.js
- app/styles/layouts/products.css
- tests/acceptance/settings/membership-test.js
Updated the preview block of offer creation screen to match the new style of Portal.
> Updated Portal mock for offers

- app/components/dashboard/dashboard-v5.hbs
- app/components/dashboard/v5/charts/anchor.hbs
- app/components/dashboard/v5/charts/anchor.js
- app/components/dashboard/v5/charts/engagement.hbs
- app/components/dashboard/v5/charts/engagement.js
- app/components/dashboard/v5/charts/mrr.hbs
- app/components/dashboard/v5/charts/mrr.js
- app/components/dashboard/v5/charts/overview.hbs
- app/components/dashboard/v5/charts/overview.js
- app/components/dashboard/v5/charts/paid-breakdown.hbs
- app/components/dashboard/v5/charts/paid-breakdown.js
- app/components/dashboard/v5/charts/paid-mix.hbs
- app/components/dashboard/v5/charts/paid-mix.js
- app/components/dashboard/v5/parts/metric.hbs
- app/services/dashboard-mocks.js
- app/services/dashboard-stats.js
- app/styles/app-dark.css
- app/styles/layouts/dashboard-v5.css
This pull request contains changes to bring the design closer to a releasable state. We're focusing on bringing the design from a Skateboard to a Bike 🚀 
As well as the design/front-end side, there are a few technical things to ensure works:
- Make sure all data is dynamic
- Make sure the code is in good shape
- Ensure no big bugs
For the design, this pull request is for just the initial switch over to the new layout. We can merge this in once we're happy enough that this is a step forward. They'll be more commits/changes in the future so this doesn't have to hang around until release.
> New design layout to bring new Dashboard closer to release

- app/components/gh-members-no-members.js
- app/components/settings/members-email-labs/newsletter-management.hbs
- app/components/settings/members-email-labs/newsletter-management.js
- app/models/newsletter.js
- adds newsletter subscribe and posts count on list screen
- updates default newsletter for "Add yourself" member feature
> Refined newsletter management and default member newsletters

- app/components/dashboard/v5/charts/paid-breakdown.js
- app/components/dashboard/v5/charts/paid-mix.js
- app/services/dashboard-mocks.js
- app/services/dashboard-stats.js
⚠️ Depends on: https://github.com/TryGhost/Ghost/pull/14547
- Updates the dashboard stats service to use `/stats/subscriptions/`
- Wires up the paid mix chart
- Wires up the paid breakdown chart
> Wire up subscription stats

- app/components/gh-launch-wizard/connect-stripe.js
- app/components/gh-members-payments-setting.js
refs https://github.com/TryGhost/Team/issues/1147
This endpoint is deprecated
> Removed usage of hasActiveStripeSubscriptions API

- app/adapters/newsletter.js
- app/components/modals/newsletters/edit.js
- app/components/modals/newsletters/new.js
refs https://github.com/TryGhost/Team/issues/1571
- When creating a new newsletter, the counts were not loaded
- When updating a newsletter, the counts were not updated
- Requires https://github.com/TryGhost/Ghost/pull/14696
> Fixed newsletter includes when adding or editing

- .lint-todo
- app/components/gh-members-payments-setting.js
- app/models/setting.js
- app/templates/settings/general.hbs
- mirage/fixtures/settings.js
- tests/integration/components/dashboard/latest-member-activity-test.js
Cleanup of soon to be removed or renamed settings
> Settings cleanup

- app/controllers/application.js
- app/styles/layouts/main.css
- app/templates/application.hbs
refs https://github.com/TryGhost/Toolbox/issues/330
refs https://github.com/TryGhost/Admin/commit/e1e5caac3d7e838770ea6bf364d3b48e9f50e87a
- this adds a banner to the top of Admin with a link to upgrade Ghost on
hosted environments that provide a link
- mostly copied from the referenced commit and then updated for v4
> Added Ghost update banner for hosted environments

- .lint-todo
- app/controllers/settings/labs.js
- app/models/setting.js
- app/services/feature.js
- app/services/settings.js
- app/templates/settings/labs.hbs
- app/templates/signin.hbs
- this didn't work the way we wanted to
- removing this will free up the namespaces to start over
> Removed oauth experiment

- app/services/feature.js
- app/templates/settings/labs.hbs
refs https://github.com/TryGhost/Team/issues/1680
- allows toggling newsletter paywall feature from labs
> Added flag for newsletter paywall feature

- app/services/feature.js
- app/templates/settings/labs.hbs
no issue
Added alpha feature flag for Ghost Explore
> Added `explore` alpha feature flag

- app/helpers/event-name.js
refs https://github.com/TryGhost/Ghost/blob/main/core/server/services/webhooks/listen.js#L18
- update AVAILABLE_EVENTS to latest ghost webhooks.
> Added missing schedule events to webhook dropdown

- app/services/tenor.js
- lib/koenig-editor/addon/components/koenig-card-image/selector-tenor.hbs
- lib/koenig-editor/addon/components/koenig-card-image/selector-tenor.js
- lib/koenig-editor/addon/components/koenig-card-image/selector-tenor/gif.js
Fixes the Tenor integration
Address #14980
> Updated Tenor API to v2
